const features: TsumuFeature = {
  'fg-1': '男の子のツム',
  'fg-2': '女の子のツム',
  'fhp-1': 'ハピネスツム',
  'fcat-1': 'プリンセスのツム',
  'fcat-2': 'プリンスのツム',
  'fcat-3': 'ヴィランズツム',
  'fcat-4': 'ハロウィンのツム',
  'fc-1': '白いツム',
  'fc-2': '黒いツム',
  'fc-3': '黄色いツム',
  'fc-4': '青いツム',
  'fc-5': '緑のツム',
  'fc-6': '赤いツム',
  'fc-7': '茶色いツム',
  'fc-8': '紫のツム',
  'fc-9': '肌色のツム',
  'fc-10': 'ピンクのツム',
  'fh-1': '白い手のツム',
  'fh-2': '黒い手のツム',
  'fh-3': '黄色い手のツム',
  'fsp-1': 'えりが見えるツム',
  'fsp-2': 'ツノのあるツム',
  'fsp-3': '海に住むツム',
  'fsp-4': 'ヒレのあるツム',
  'fsp-5': 'くちばしのあるツム',
  'fsp-6': '三つ目の宇宙人',
  'fha-1': '白い髪のツム',
  'fha-2': '毛のはねたツム',
  'fha-3': '毛を結んだツム',
  'fha-4': '毛が3本のツム',
  'fca-1': 'リボンをつけたツム',
  'fca-2': '冠をつけたツム',
  'fca-3': '花をつけたツム',
  'fca-4': '帽子をかぶったツム',
  'fey-1': 'まゆ毛のあるツム',
  'fey-2': 'まつ毛のあるツム',
  'fey-3': '白目が見えるツム',
  'fea-1': '耳が丸いツム',
  'fea-2': '耳がとがったツム',
  'fea-3': '耳が垂れたツム',
  'fea-4': '耳がピンクのツム',
  'fn-1': '鼻が三角のツム',
  'fn-2': '鼻が黒いツム',
  'fn-3': '鼻がピンクのツム',
  'fch-1': 'ほっぺが赤いツム',
  'fch-2': 'ヒゲのあるツム',
  'fmo-1': '口が見えるツム',
  'fty-1': 'イヌのツム',
  'fty-2': 'ネコ科のツム',
  'fty-3': 'うさぎのツム',
  'fty-4': 'トリのツム',
  'f-1': 'ミッキーのツム',
  'f-2': 'ミニーのツム',
  'f-3': 'ドナルドのツム',
  'fse-0': 'ミッキー＆フレンズのツム',
  'fse-1': 'ピクサーの仲間のツム',
  'fse-2': 'チップとデールのツム',
  'fse-3': 'トイストーリーシリーズ',
  'fse-4': 'モンスターズインクシリーズ',
  'fse-5': 'スターウォーズシリーズ',
  'fse-6': 'マーベルシリーズ',
  'fse-7': 'アナと雪の女王シリーズ',
  'fse-8': 'くまのプーさんシリーズ',
  'fse-9': '美女と野獣シリーズ',
  'fse-10': 'アラジンシリーズ',
  'fse-11': 'リロ＆スティッチシリーズ',
  'fse-12': 'リトルマーメイドシリーズ',
  'fse-13': 'ラプンツェルシリーズ',
  'fse-14': 'キングダムハーツシリーズ',
  'fi-1': 'イニシャルAのツム',
  'fi-2': 'イニシャルBのツム',
  'fi-3': 'イニシャルDのツム',
  'fi-4': 'イニシャルJのツム',
  'fi-5': 'イニシャルMのツム',
  'fi-6': 'イニシャルNのツム',
  'fi-7': 'イニシャルPのツム',
  'fi-8': 'イニシャルSのツム',
  'fi-9': 'イニシャルTのツム',
  'fsk-1': '消去系スキルのツム',
  'fsk-2': '画面中央消去スキルのツム',
  'fsk-3': '画面中央',
  'fsk-4': '横ライン消去スキルのツム',
  'fsk-5': '縦ライン消去スキルのツム',
  'fsk-6': '斜め消去スキルのツム',
  'fsk-7': 'ランダム消去スキルのツム',
  'fsk-8': '恋人を呼ぶスキルのツム',
  'fsk-9': '友だちを呼ぶスキルのツム',
  'fsk-10': 'ハートが出るスキルのツム',
  'fsk-11': 'ボムを出すスキルのツム',
  'fsk-12': '変化系スキルのツム',
  'fsk-13': '大ツムを発生させるツム',
  'fsk-14': 'コウモリが出るツム',
  'fsk-15': 'かぼちゃが出るツム',
  'fsk-16': 'クロスライン消去スキルのツム',
  'fsk-17': '逆T字消去数キルのツム',
  'fsk-18': '数カ所消去するスキルツム',
  'fsk-19': '特殊消去系スキルのツム',
  'fsk-20': '時間を止めるスキルのツム',
  'fsk-21': 'しっぽを振るスキルのツム',
  'fsk-22': 'サークル消去スキルのツム',
  'fsk-23': 'ジグザグ消去スキルのツム',
  'fsk-24': 'Z字消去スキルのツム',
  'fsk-25': '3方向消去スキルのツム',
  'fsk-26': 'アーチ消去スキルのツム',
  'fsk-27': 'S字消去スキルのツム',
  'fsk-28': 'Vライン消去スキルのツム',
  'fsk-29': '十字消去スキルのツム',
  'fsk-30': 'フィーバーに突入できるツム',
  'fsk-31': 'タップ消去スキルのツム',
  'fsk-34': '何が起こるかわからない',
};

const tsumuData: TsumuType[] = [
  {
    id: 'tm-1',
    name: 'ミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Rcixh13JufUqpEMqrYQpzC3ag5G0wbTP',
    features: ['fn-2', 'fh-1', 'fg-1', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fsk-3'],
  },
  {
    id: 'tm-2',
    name: 'ミニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1q3NV9z0X75vSgbg0TwSkDs1gUkN2gOrQ',
    features: ['fn-2', 'fca-1', 'fh-1', 'fch-1', 'fg-2', 'f-2', 'fi-5', 'fc-2', 'fea-1', 'fsk-8', 'fsk-10', 'fey-2'],
  },
  {
    id: 'tm-3',
    name: 'ドナルド',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1S3WsqpHW31vYGt4gHZ3MlgVKkhchQti5',
    features: ['fha-2', 'fca-1', 'fh-1', 'fg-1', 'fca-4', 'fch-1', 'fmo-1', 'fsp-5', 'fc-1', 'fi-3', 'f-3'],
  },
  {
    id: 'tm-4',
    name: 'デイジー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1ZnafWOkJXKrfFns5n7ucrJ2iV3km035M',
    features: ['fca-1', 'fh-1', 'fg-2', 'fch-1', 'fmo-1', 'fsp-5', 'fc-1', 'fsk-8', 'fi-3', 'fsk-10', 'fey-2'],
  },
  {
    id: 'tm-5',
    name: 'グーフィー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1KNNxRkQ8-GLqJ0t8bB6cIjde9VdYPpUK',
    features: ['fn-2', 'fha-2', 'fh-1', 'fg-1', 'fsk-7', 'fca-4', 'fea-3', 'fc-2', 'fey-3', 'fty-1', 'fha-4'],
  },
  {
    id: 'tm-6',
    name: 'プルート',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1nc-oDjvjW5Bd-sFMaNKJ4PtEYuH-KWXR',
    features: ['fn-2', 'fi-7', 'fg-1', 'fc-3', 'fea-3', 'fey-3', 'fty-1', 'fsk-4', 'fh-3'],
  },
  {
    id: 'tm-7',
    name: 'チップ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1nG4wThL-WjQ7IDFj3FZqP8t_0FDSErIT',
    features: ['fn-2', 'fg-1', 'fc-7', 'fch-1', 'fn-1', 'fea-2', 'fsk-10', 'fsk-9', 'fea-4'],
  },
  {
    id: 'tm-8',
    name: 'デール',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Vzkx0foVOqwIvmf1C-vZTxw7slnbRW1M',
    features: ['fg-1', 'fc-7', 'fch-1', 'fc-3', 'fea-2', 'fn-3', 'fsk-10', 'fi-3', 'fsk-9', 'fea-4'],
  },
  {
    id: 'tm-9',
    name: 'プー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1_wlPpL0XXEas9Bg9gvCT52qA4UYWp1XV',
    features: ['fi-7', 'fg-1', 'fey-1', 'fc-3', 'fn-1', 'fea-1', 'fsk-20', 'fh-3'],
  },
  {
    id: 'tm-10',
    name: 'ピグレット',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Y2-pYaZqA9vVDYM2-n1jNiwi7dkV7ICL',
    features: ['fi-7', 'fg-1', 'fey-1', 'fch-1', 'fn-1', 'fea-2', 'fn-3', 'fea-4', 'fc-10'],
  },
  {
    id: 'tm-11',
    name: 'ティガー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1f2KoeEk70Ffgm1w5oRiQ6hn1yvlqe8bb',
    features: ['fsk-7', 'fg-1', 'fey-1', 'fc-3', 'fn-1', 'fch-2', 'fea-1', 'fn-3', 'fsk-21', 'fi-9', 'fty-2', 'fh-3'],
  },
  {
    id: 'tm-12',
    name: 'イーヨー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1X16-Ic46nxwbWlFv3IhqLZHZfJy7tBCc',
    features: ['fha-2', 'fg-1', 'fey-1', 'fea-3', 'fc-4', 'fc-8', 'fea-4'],
  },
  {
    id: 'tm-13',
    name: 'ルー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=198wKLeKszK2yCUtdkRzCR3K3K0otgstl',
    features: ['fha-2', 'fg-1', 'fey-1', 'fc-7', 'fn-1', 'fsk-5', 'fea-2', 'fea-1', 'fea-4'],
  },
  {
    id: 'tm-14',
    name: 'クリストファーロビン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1g90y0rElb7O0LEgxLSZa-7WSTkTBIhOA',
    features: ['fg-1', 'fey-1', 'fc-7', 'fch-1', 'fc-9', 'fea-1'],
  },
  {
    id: 'tm-15',
    name: 'スティッチ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1WP_Q3ZUMLvwdFdrFyqdgCqRYUrCuve-0',
    features: ['fha-2', 'fg-1', 'fi-8', 'fmo-1', 'fea-2', 'fsk-5', 'fc-4'],
  },
  {
    id: 'tm-16',
    name: 'スクランプ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=18Kd8cRpj5cqUOQeXut8guQ4Jf-31pKCU',
    features: ['fca-1', 'fha-2', 'fc-5', 'fg-2', 'fi-8', 'fmo-1', 'fsk-34', 'fc-4', 'fha-3'],
  },
  {
    id: 'tm-17',
    name: 'エンジェル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1HRwCGE6PGxLuZRKYQEfvEJW3-ZsBTHDv',
    features: ['fi-1', 'fg-2', 'fch-1', 'fmo-1', 'fea-2', 'fsk-8', 'fsk-10', 'fey-2', 'fc-10', 'fea-4'],
  },
  {
    id: 'tm-18',
    name: 'ウッディ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1auzz6I_UwkxTKMe-yH9x5ZgsyUORn8Xy',
    features: ['fse-1', 'fi-7', 'fg-1', 'fey-1', 'fca-4', 'fc-7', 'fc-9', 'fea-1', 'fsk-3'],
  },
  {
    id: 'tm-19',
    name: 'バズライトイヤー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=18cp1K1E-hD5guM44BEUJ2Aj2m3B5dHDT',
    features: ['fi-2', 'fse-1', 'fh-1', 'fg-1', 'fey-1', 'fc-9', 'fc-8', 'fsk-29'],
  },
  {
    id: 'tm-20',
    name: 'ジェシー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1OwvDa84ZWGzgx8hiVqW3Nh67k4wEKAIO',
    features: ['fca-1', 'fse-1', 'fc-6', 'fey-1', 'fca-4', 'fg-2', 'fch-1', 'fc-9', 'fea-1', 'fsk-3', 'fha-3', 'fey-2', 'fi-4'],
  },
  {
    id: 'tm-21',
    name: 'ロッツォ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1KxtO1YB8yNrvjLTbfTuGy7Lvm2SfdfQY',
    features: ['fse-1', 'fc-6', 'fg-1', 'fey-1', 'fch-1', 'fn-1', 'fcat-3', 'fea-1', 'fsk-4', 'fea-4', 'fc-10'],
  },
  {
    id: 'tm-22',
    name: 'レックス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1O-9Rgsi8vYw5pBGhyMx1iRRvDWqU3_Do',
    features: ['fse-1', 'fc-5', 'fg-1', 'fmo-1', 'fsk-18'],
  },
  {
    id: 'tm-23',
    name: 'アリス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=182gqOQOtlDPrHlyQZL-_3NXdFFTmvDoc',
    features: ['fca-1', 'fi-1', 'fg-2', 'fc-3', 'fch-1', 'fc-9', 'fsk-13', 'fea-1', 'fey-2'],
  },
  {
    id: 'tm-24',
    name: '白うさぎ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1I1bOuKJf_na4X2rZeiM23oQEldObINNc',
    features: ['fha-2', 'fh-1', 'fg-1', 'fch-1', 'fi-8', 'fn-1', 'fea-2', 'fc-1', 'fn-3', 'fty-3', 'fsk-20', 'fea-4'],
  },
  {
    id: 'tm-25',
    name: 'チェシャ猫',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1y2is7qg4-IHA-7zG0KipxLI_7rpoE1kP',
    features: ['fha-2', 'fc-6', 'fsk-7', 'fg-1', 'fey-1', 'fch-1', 'fn-1', 'fea-2', 'fc-10', 'fn-3', 'fsk-21', 'fea-4', 'fty-2'],
  },
  {
    id: 'tm-26',
    name: 'ヤングオイスター',
    imgUrl: 'http://drive.google.com/uc?export=view&id=11vDfh-X4IF_f1nT56qGCxR07inwbFCic',
    features: ['fey-1', 'fca-4', 'fch-1', 'fmo-1', 'fsp-3', 'fc-8', 'fc-10'],
  },
  {
    id: 'tm-27',
    name: 'マイク',
    imgUrl: 'http://drive.google.com/uc?export=view&id=10RLziS6Q2pUVFRtGyGvtqMUKEPKyBUYJ',
    features: ['fse-1', 'fc-5', 'fg-1', 'fi-5', 'fsk-5', 'fsp-2', 'fey-3', 'fsk-9'],
  },
  {
    id: 'tm-28',
    name: 'サリー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1ZFktESD6TzFRTGqWrkRuhm8-z6oDHGsu',
    features: ['fse-1', 'fg-1', 'fey-1', 'fn-1', 'fi-8', 'fsk-13', 'fsp-2', 'fc-4'],
  },
  {
    id: 'tm-29',
    name: 'ランドール',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Wf6drXROSs9kEDyRtXpayb1zxOhIM_qU',
    features: ['fse-1', 'fha-2', 'fg-1', 'fmo-1', 'fcat-3', 'fey-3', 'fc-4', 'fc-8', 'fha-4'],
  },
  {
    id: 'tm-30',
    name: 'バンビ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1O0Q05oAw70m34YXS9Sf1v13YN8OoL9nk',
    features: ['fi-2', 'fn-2', 'fha-2', 'fg-1', 'fc-7', 'fc-3', 'fsk-18', 'fcat-2', 'fey-2', 'fh-3'],
  },
  {
    id: 'tm-31',
    name: 'とんすけ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=18tsrjF76XJHxTedcYP7D2nMlte-5yl6I',
    features: ['fh-1', 'fg-1', 'fn-1', 'fn-3', 'fsk-3', 'fsk-8', 'fi-9', 'fty-3', 'fsk-10', 'fea-4'],
  },
  {
    id: 'tm-32',
    name: 'ミスバニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1mfqp8XiNpN1mXQuf5Bvdh1oEsxxQOiBP',
    features: ['fi-2', 'fg-2', 'fc-3', 'fch-1', 'fn-1', 'fi-5', 'fsk-11', 'fn-3', 'fty-3', 'fey-2', 'fh-3', 'fea-4'],
  },
  {
    id: 'tm-33',
    name: 'エルサ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1q0JScWtjVT03x4ZHKUA3TliC9geMabEW',
    features: ['fha-2', 'fca-2', 'fey-1', 'fg-2', 'fc-9', 'fea-1', 'fey-3', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-34',
    name: 'アナ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1fMv9rIqWYQvExp04Rbq65BmrYgREyBLs',
    features: ['fi-1', 'fey-1', 'fc-7', 'fg-2', 'fc-9', 'fea-1', 'fey-3', 'fha-3', 'fsk-10', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-35',
    name: 'オラフ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1OyjrUJB0HLMXnVvTTSNgFkn9eoQEONMU',
    features: ['fha-2', 'fsk-6', 'fg-1', 'fey-1', 'fmo-1', 'fc-1', 'fha-4'],
  },
  {
    id: 'tm-36',
    name: 'スヴェン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=19zm3zVRSgGKp1nUOP1SVbSY1YUBrHoVf',
    features: ['fg-1', 'fey-1', 'fc-7', 'fi-8', 'fmo-1', 'fea-2', 'fsp-2', 'fsk-4'],
  },
  {
    id: 'tm-37',
    name: 'サプライズエルサ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1ZnJJHfqsNWInSOIPKvhflypBvwUy702Y',
    features: ['fha-2', 'fey-1', 'fg-2', 'fc-9', 'fi-8', 'fea-1', 'fca-3', 'fey-3', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-38',
    name: 'バースデーアナ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1nKHi9zIXIgXpp1SzaZYEW_Oj5NGL01TX',
    features: ['fi-2', 'fi-1', 'fca-1', 'fey-1', 'fc-7', 'fg-2', 'fc-9', 'fea-1', 'fca-3', 'fey-3', 'fha-3', 'fsk-10', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-39',
    name: 'アリエル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1I13JdG8iZGuZTJi_yxmCFlNQkCUYR5aj',
    features: ['fi-1', 'fsk-22', 'fc-6', 'fha-2', 'fg-2', 'fch-1', 'fc-9', 'fsp-4', 'fea-1', 'fsp-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-40',
    name: 'フランダー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=18C2mqgN-kIky9p_JcKeysf19MMEo79Rj',
    features: ['fg-1', 'fey-1', 'fch-1', 'fc-3', 'fmo-1', 'fsp-4', 'fsp-3', 'fsk-4', 'fsk-9'],
  },
  {
    id: 'tm-41',
    name: 'セバスチャン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1THB2VnEkOPgEuiU5wFYPQwPZGESrRdCH',
    features: ['fc-6', 'fsk-7', 'fg-1', 'fey-1', 'fch-1', 'fi-8', 'fmo-1', 'fsp-3'],
  },
  {
    id: 'tm-42',
    name: 'トリトン王',
    imgUrl: 'http://drive.google.com/uc?export=view&id=19hmh0i9qcLptiUcbVXHVefZoIcpOPNCz',
    features: ['fca-2', 'fg-1', 'fey-1', 'fc-9', 'fsp-4', 'fsk-5', 'fch-2', 'fc-1', 'fn-3', 'fsp-3', 'fha-1', 'fi-9'],
  },
  {
    id: 'tm-43',
    name: 'ラプンツェル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=10Fl2ggfacPCfoDHRC6MqnsAytLKJOZLe',
    features: ['fey-1', 'fg-2', 'fc-3', 'fc-9', 'fea-1', 'fca-3', 'fsk-8', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-44',
    name: 'パスカル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Hfb7VoA0rfB7VDLuRvjwTpB1XV-PBJYT',
    features: ['fi-7', 'fc-5', 'fg-1', 'fmo-1', 'fey-3'],
  },
  {
    id: 'tm-45',
    name: '野獣',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1vW7nCs4uXJyaCUbRVkbIGDhH5YDU56kL',
    features: ['fi-2', 'fsk-6', 'fg-1', 'fey-1', 'fc-7', 'fc-3', 'fea-3', 'fch-2', 'fsp-2', 'fcat-2', 'fea-4', 'fh-3'],
  },
  {
    id: 'tm-46',
    name: 'ベル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1JzyWb6L7eysxG1XjC6bY5tNNDGdibAnb',
    features: ['fi-2', 'fey-1', 'fc-7', 'fg-2', 'fch-1', 'fc-9', 'fea-1', 'fsk-8', 'fha-3', 'fsk-10', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-47',
    name: 'マックィーン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1C_aQLMoC3BavuVCPLtB8XyOL01Nz_I90',
    features: ['fse-1', 'fc-6', 'fg-1', 'fsk-31', 'fch-1', 'fi-5', 'fey-3', 'fh-2'],
  },
  {
    id: 'tm-48',
    name: 'メーター',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1aMbGoOxn5z0del4sHk_ThbFSPQCWrzT4',
    features: ['fse-1', 'fsk-7', 'fg-1', 'fc-7', 'fmo-1', 'fi-5', 'fey-3', 'fh-2', 'fsk-21'],
  },
  {
    id: 'tm-49',
    name: 'ジャスミン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1eySS5Ysv-aSaKuKfbKBxm8Ftdp1KkMvm',
    features: ['fca-2', 'fey-1', 'fc-7', 'fg-2', 'fch-1', 'fc-9', 'fsk-4', 'fc-2', 'fea-1', 'fsk-8', 'fha-3', 'fey-2', 'fcat-1', 'fi-4'],
  },
  {
    id: 'tm-50',
    name: 'アラジン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1A9cu3fkH01wfwmeVzXmB9AgIc5duZp2x',
    features: ['fi-1', 'fg-1', 'fey-1', 'fca-4', 'fc-9', 'fc-2', 'fea-1', 'fcat-2', 'fsk-9'],
  },
  {
    id: 'tm-51',
    name: 'ジーニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1ViyKZEJ8GFEt6GMsajqQ9ZvkL4gdzE6e',
    features: ['fha-2', 'fg-1', 'fey-1', 'fea-2', 'fch-2', 'fsk-34', 'fc-4', 'fha-3'],
  },
  {
    id: 'tm-52',
    name: 'ピノキオ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1qoILIzKHgYSNRtf8flg_mFyBuAwEz-vO',
    features: ['fi-7', 'fg-1', 'fey-1', 'fca-4', 'fch-1', 'fc-3', 'fc-9', 'fea-1'],
  },
  {
    id: 'tm-53',
    name: 'ベイマックス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1yUwyLBjmXSZL08cMT22eYOd0K9DHDrPc',
    features: ['fi-2', 'fh-1', 'fg-1', 'fsk-13', 'fc-1'],
  },
  {
    id: 'tm-54',
    name: 'マレフィセント',
    imgUrl: 'http://drive.google.com/uc?export=view&id=17-IWosmp0sefqZCm72vpHFtyEcJeKfBG',
    features: ['fh-1', 'fey-1', 'fca-4', 'fg-2', 'fi-5', 'fc-2', 'fcat-3', 'fc-1', 'fsp-2', 'fey-2'],
  },
  {
    id: 'tm-55',
    name: 'ダンボ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1HXxHxTxUMUHzt1wecLX8I16DSyfyl_Am',
    features: ['fg-1', 'fca-4', 'fch-1', 'fea-3', 'fsk-5', 'fc-4', 'fi-3', 'fea-4'],
  },
  {
    id: 'tm-56',
    name: 'ティンカーベル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1wG8PI5vGoTe_Ws-Rq-Fy2-B0MXlAbHGK',
    features: ['fi-2', 'fey-1', 'fg-2', 'fc-3', 'fc-9', 'fsk-4', 'fea-1', 'fha-3', 'fi-9', 'fey-2'],
  },
  {
    id: 'tm-57',
    name: 'レディ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1-ayYy5Sz2XeTvWxQET5dPTsDmgiGnYbY',
    features: ['fn-2', 'fg-2', 'fch-1', 'fc-3', 'fn-1', 'fea-3', 'fty-1', 'fey-2', 'fh-3'],
  },
  {
    id: 'tm-58',
    name: 'マリー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1wl7r9SO63iXpv2hPbONLVOQADQICTvZq',
    features: ['fca-1', 'fha-2', 'fh-1', 'fch-1', 'fg-2', 'fn-1', 'fi-5', 'fea-2', 'fch-2', 'fc-1', 'fn-3', 'fsk-11', 'fha-3', 'fey-2', 'fty-2', 'fea-4'],
  },
  {
    id: 'tm-59',
    name: 'オーロラ姫',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1RjwRu7gm2P7yzKsH3mrZftnWv6uospmm',
    features: ['fi-2', 'fi-1', 'fi-7', 'fca-2', 'fey-1', 'fg-2', 'fch-1', 'fc-9', 'fc-3', 'fsk-8', 'fsk-10', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-60',
    name: '白雪姫',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1k04jcVZOy1di1KPW2WCEwXNgQt2EGZLb',
    features: ['fca-1', 'fg-2', 'fch-1', 'fc-9', 'fi-8', 'fc-2', 'fea-1', 'fsk-9', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-61',
    name: 'ナラ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1D8hREIQYXqkaISxFuu_m0tvrytjlw6ob',
    features: ['fey-1', 'fc-7', 'fg-2', 'fc-3', 'fi-6', 'fea-1', 'fn-3', 'fsk-8', 'fsk-10', 'fh-3', 'fsk-9', 'fty-2'],
  },
  {
    id: 'tm-62',
    name: 'シンバ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1APWLYV0Pl73Iinac-zqtybJKfRw-AV6t',
    features: ['fha-2', 'fg-1', 'fey-1', 'fc-7', 'fc-3', 'fi-8', 'fea-1', 'fn-3', 'fsk-3', 'fcat-2', 'fh-3', 'fty-2'],
  },
  {
    id: 'tm-63',
    name: 'スカー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1ETXipSsfEGDWgMvjlK5LHefyn71Ho0kA',
    features: ['fn-2', 'fha-2', 'fg-1', 'fey-1', 'fc-7', 'fi-8', 'fcat-3', 'fch-2', 'fea-1', 'fsk-4', 'fty-2'],
  },
  {
    id: 'tm-64',
    name: 'アースラ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1__6CvgK3IrVQm9egzuavOarQhD41rto6',
    features: ['fha-2', 'fsk-22', 'fi-1', 'fey-1', 'fg-2', 'fcat-3', 'fea-1', 'fc-1', 'fsp-3', 'fc-8', 'fha-1', 'fey-2'],
  },
  {
    id: 'tm-65',
    name: '女王',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1yj3t1nCtg-fFjcNk4zbvr3AxD0z7Vtfo',
    features: ['fca-2', 'fey-1', 'fg-2', 'fc-9', 'fcat-3', 'fsk-11', 'fsp-1', 'fey-2', 'fi-4'],
  },
  {
    id: 'tm-66',
    name: 'マレフィセントドラゴン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=10P7cdrW6kzBxZDdryhDVafSHC1dxpIiQ',
    features: ['fn-2', 'fg-2', 'fmo-1', 'fi-5', 'fc-2', 'fcat-3', 'fch-2', 'fsp-2', 'fh-2', 'fi-3'],
  },
  {
    id: 'tm-67',
    name: 'フィニック',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1ybAc_y_2L5xJpx5KkzO6PFY3r-pmRmJ9',
    features: ['fn-2', 'fg-1', 'fey-1', 'fc-7', 'fc-3', 'fn-1', 'fea-2', 'fsk-5', 'fsp-1', 'fea-4'],
  },
  {
    id: 'tm-68',
    name: 'ニック',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1HuD2-S63ckqEtGOLVOzih1NfgWuISaNi',
    features: ['fn-2', 'fsk-7', 'fg-1', 'fey-1', 'fc-7', 'fn-1', 'fi-6', 'fea-2', 'fsp-1'],
  },
  {
    id: 'tm-69',
    name: 'ジュディ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1DYn61bmjNZs7mQpHXVb9mLzAWgNpMDUh',
    features: ['fh-1', 'fey-1', 'fca-4', 'fg-2', 'fc-2', 'fea-2', 'fn-3', 'fsk-3', 'fc-4', 'fh-2', 'fty-3', 'fea-4', 'fey-2', 'fi-4'],
  },
  {
    id: 'tm-70',
    name: 'シンデレラ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1jRhP3cMs6vxzQK2EXLWNlkNUjbk_6DY4',
    features: ['fh-1', 'fey-1', 'fg-2', 'fc-3', 'fch-1', 'fi-8', 'fc-9', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-71',
    name: 'フェアリーゴッドマザー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1LylUnQPgSOlecUJpVCSLjg-Bm2DpXvmC',
    features: ['fca-1', 'fey-1', 'fca-4', 'fg-2', 'fch-1', 'fsk-9', 'fc-9', 'fc-4', 'fha-1', 'fsk-10'],
  },
  {
    id: 'tm-72',
    name: 'マッドハッター',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1tqdBhgQFm1ctAKCnUwBP_hhV1szjEDcU',
    features: ['fha-2', 'fg-1', 'fey-1', 'fca-4', 'fc-5', 'fc-9', 'fi-5', 'fea-1', 'fc-4', 'fha-1'],
  },
  {
    id: 'tm-73',
    name: 'ハートの女王',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1CMeeVne5xaFwBp3ltOcOw_XSjO-9x9Ne',
    features: ['fha-2', 'fca-2', 'fsp-1', 'fey-1', 'fg-2', 'fc-9', 'fcat-3', 'fea-1', 'fha-3'],
  },
  {
    id: 'tm-74',
    name: 'ドリー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=11aSsTemw1h3HPTnsL-LCInR9GhuDwAhG',
    features: ['fsk-24', 'fse-1', 'fg-2', 'fmo-1', 'fsp-4', 'fey-3', 'fc-4', 'fsp-3', 'fi-3', 'fh-3'],
  },
  {
    id: 'tm-75',
    name: 'ニモ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1HsmXiGoM7JobXmAO4p6ciFTA8v6jpiZz',
    features: ['fse-1', 'fg-1', 'fi-6', 'fsp-4', 'fmo-1', 'fey-3', 'fsp-3', 'fsk-4'],
  },
  {
    id: 'tm-76',
    name: 'クラッシュ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1DAgee3JQcKljwJ_Chs1TXunNnKyTzUiZ',
    features: ['fse-1', 'fc-5', 'fmo-1', 'fsp-4', 'fsk-5', 'fey-3', 'fsp-3', 'fsk-9'],
  },
  {
    id: 'tm-77',
    name: 'クルエラ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1NVOade2md6p4XIvjnDAtww0Zzdr2Xezf',
    features: ['fha-2', 'fey-1', 'fg-2', 'fch-1', 'fc-9', 'fcat-3', 'fc-2', 'fc-1', 'fi-3', 'fha-1', 'fsk-27', 'fey-2'],
  },
  {
    id: 'tm-78',
    name: 'フック船長',
    imgUrl: 'http://drive.google.com/uc?export=view&id=173L5RXRbm7QCG0VDuuyG96ZbGOaJyoMD',
    features: ['fc-6', 'fg-1', 'fey-1', 'fca-4', 'fc-9', 'fcat-3', 'fsk-5', 'fch-2'],
  },
  {
    id: 'tm-79',
    name: 'ジャファー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=18V2Fj4Kc4EFMH6WtM8wD5ZJHtqdYNLML',
    features: ['fc-6', 'fg-1', 'fey-1', 'fca-4', 'fc-9', 'fcat-3', 'fch-2', 'fsk-16', 'fi-4'],
  },
  {
    id: 'tm-80',
    name: 'モアナ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1bdv7g5Zc7g3_jgjcBkAbvN04_JllNb2Q',
    features: ['fha-2', 'fey-1', 'fc-7', 'fg-2', 'fch-1', 'fc-9', 'fi-5', 'fc-2', 'fsk-11', 'fea-1', 'fca-3', 'fsk-4', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-81',
    name: 'マウイ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1nBNtz3Xi0O4d24hiC3m_ygzmjgsKkc2i',
    features: ['fha-2', 'fg-1', 'fey-1', 'fc-7', 'fc-9', 'fi-5', 'fc-2', 'fsk-5', 'fea-1', 'fsk-34'],
  },
  {
    id: 'tm-82',
    name: 'ヘラクレス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1ucFqfxvZrGB91td1ILRFncxYuee7OtzF',
    features: ['fha-2', 'fg-1', 'fey-1', 'fc-7', 'fc-3', 'fc-9', 'fea-1', 'fsk-4'],
  },
  {
    id: 'tm-83',
    name: 'フィリップ王子',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1kw96R0j5MjV1599XiaYYVF48ZQq4gZzR',
    features: ['fi-7', 'fc-6', 'fg-1', 'fey-1', 'fca-4', 'fc-9', 'fea-1', 'fsk-3', 'fcat-2', 'fsp-1'],
  },
  {
    id: 'tm-84',
    name: 'ハデス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=10VUQCnZsi7xUYb6Cna8Pa3uv7aCUlgBO',
    features: ['fha-2', 'fg-1', 'fey-1', 'fcat-3', 'fea-2', 'fey-3', 'fc-4', 'fsk-29'],
  },
  {
    id: 'tm-85',
    name: 'ガストン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1J2o0g4gkTCEmCFolHp6uPeoQoP2Fv31-',
    features: ['fca-1', 'fsp-1', 'fg-1', 'fey-1', 'fc-9', 'fcat-3', 'fc-2', 'fea-1', 'fha-3', 'fsk-4'],
  },
  {
    id: 'tm-86',
    name: 'ルミエール',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1M6chI6t84qzRA6kXrkrj15yP_Am-V1vg',
    features: ['fsk-7', 'fg-1', 'fey-1', 'fh-1', 'fc-3', 'fc-1', 'fsk-30', 'fh-3'],
  },
  {
    id: 'tm-87',
    name: 'フリンライダー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1AX4Md3gaJIi6S_0DQ_y7t173YjYK8Fza',
    features: ['fg-1', 'fey-1', 'fc-7', 'fc-9', 'fch-2', 'fea-1', 'fsk-8', 'fcat-2', 'fsp-1'],
  },
  {
    id: 'tm-88',
    name: 'マキシマス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Yok3yOecKMpW36ND_Ft4n5O7p1juXyRE',
    features: ['fsk-6', 'fh-1', 'fg-1', 'fey-1', 'fi-5', 'fea-2', 'fc-1', 'fha-1', 'fea-4'],
  },
  {
    id: 'tm-89',
    name: 'ムーラン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1IgETglj3kR8-FRLLiW-8mPgHmA4XUaAT',
    features: ['fey-1', 'fg-2', 'fch-1', 'fc-9', 'fi-5', 'fc-2', 'fea-1', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-90',
    name: 'ポカホンタス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1r7ydRWCn7aFsCtZZYWxiNjeeFuilW2kQ',
    features: ['fi-7', 'fey-1', 'fc-7', 'fg-2', 'fch-1', 'fc-9', 'fc-2', 'fea-1', 'fsk-8', 'fsk-20', 'fcat-1'],
  },
  {
    id: 'tm-91',
    name: 'クルーズラミレス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=10SvxnpZNF_E7UEMjxgNVxH2h-kRB6i68',
    features: ['fse-1', 'fsk-6', 'fg-2', 'fc-3', 'fey-3', 'fh-2', 'fsk-9'],
  },
  {
    id: 'tm-92',
    name: 'ピーターパン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Maj2Xu8vfKA1ERxFiNYloRj-UAVbbJnJ',
    features: ['fi-7', 'fg-1', 'fey-1', 'fca-4', 'fch-1', 'fc-3', 'fc-9', 'fc-5', 'fc-7', 'fsk-5', 'fea-1', 'fsk-9'],
  },
  {
    id: 'tm-93',
    name: 'トランプ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1NWSe_sD7UYnuO4VOdT74_YDKrWiBw4dg',
    features: ['fn-2', 'fha-2', 'fg-1', 'fey-1', 'fn-1', 'fea-3', 'fc-2', 'fsk-8', 'fty-1', 'fsk-10', 'fsk-4', 'fi-9', 'fea-4'],
  },
  {
    id: 'tm-94',
    name: 'ブルーフェアリー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1xIgDVS-RP3HXDejKSRw6rK3Mo_rXk5KY',
    features: ['fi-2', 'fey-1', 'fg-2', 'fc-3', 'fch-1', 'fc-9', 'fsk-11', 'fey-2'],
  },
  {
    id: 'tm-95',
    name: 'ティモシー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1w-AtwKUy_QHUbTwNGnNgz6np9NELptwU',
    features: ['fn-2', 'fh-1', 'fg-1', 'fca-4', 'fsk-9', 'fc-7', 'fn-1', 'fi-5', 'fsk-11', 'fch-2', 'fea-2', 'fea-1', 'fi-9', 'fea-4'],
  },
  {
    id: 'tm-96',
    name: 'パッチ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1z2ofuiafGrPUuG1Yag_3d-BHuGVWhIcf',
    features: ['fn-2', 'fi-7', 'fh-1', 'fg-1', 'fey-1', 'fch-1', 'fea-3', 'fc-1', 'fty-1', 'fsk-4', 'fea-4'],
  },
  {
    id: 'tm-97',
    name: '王子',
    imgUrl: 'http://drive.google.com/uc?export=view&id=12zOD8EzPsc2z8ds7pfFvCLkPxVoc5Y4i',
    features: ['fi-7', 'fg-1', 'fey-1', 'fca-4', 'fc-9', 'fea-1', 'fc-4', 'fsk-8', 'fcat-2', 'fsp-1', 'fsk-10'],
  },
  {
    id: 'tm-98',
    name: 'ブー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1TqfijljtoH9U0W2lQfBYiNGV9FgYAYeL',
    features: ['fi-2', 'fse-1', 'fey-1', 'fca-4', 'fg-2', 'fch-1', 'fc-9', 'fsk-13', 'fmo-1', 'fi-5', 'fey-3', 'fsk-9', 'fey-2', 'fh-3'],
  },
  {
    id: 'tm-99',
    name: 'フラワー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1l1pGV3wZpSXBypxeSOKYpFR9A2DPkWzV',
    features: ['fn-2', 'fha-2', 'fg-1', 'fch-1', 'fn-1', 'fc-2', 'fea-1', 'fh-2', 'fey-2'],
  },
  {
    id: 'tm-100',
    name: 'ダッチェス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1GV3H4rm__Ltfcu85BN9scyfXSOR99_Lg',
    features: ['fha-2', 'fh-1', 'fey-1', 'fg-2', 'fch-1', 'fn-1', 'fea-2', 'fch-2', 'fc-1', 'fn-3', 'fsk-8', 'fi-3', 'fey-2', 'fty-2', 'fea-4'],
  },
  {
    id: 'tm-101',
    name: 'ロビンフッド',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1f-jhUmunu8y4oTsHBFTeivltgmNNbTrr',
    features: ['fn-2', 'fha-2', 'fg-1', 'fc-7', 'fca-4', 'fn-1', 'fea-2', 'fsk-5', 'fsp-1'],
  },
  {
    id: 'tm-102',
    name: 'ゴーテル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1887VbziGk3hL6TQcHuRFV99KRO_avL3Z',
    features: ['fha-2', 'fey-1', 'fch-1', 'fg-2', 'fcat-3', 'fc-2', 'fi-5', 'fea-1', 'fey-3', 'fey-2'],
  },
  {
    id: 'tm-103',
    name: 'ハム',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1cgccQwExTypu73TJUZQkKnqoT6YjhHNT',
    features: ['fse-1', 'fg-1', 'fey-1', 'fch-1', 'fea-2', 'fn-3', 'fsk-4', 'fea-4'],
  },
  {
    id: 'tm-104',
    name: 'ティモン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1rT4zPWjpNl52BsmVL27O0FSAti869LJJ',
    features: ['fg-1', 'fey-1', 'fc-7', 'fsk-9', 'fsk-13', 'fea-3', 'fey-3', 'fi-9'],
  },
  {
    id: 'tm-105',
    name: 'ラフィキ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1dvoC5zfarRqnvz5oGcH1dQIxZoCatpbO',
    features: ['fha-2', 'fg-1', 'fn-1', 'fch-2', 'fha-1', 'fsk-18'],
  },
  {
    id: 'tm-106',
    name: 'クリストフ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1BBgUfKMKg2xf6MtCGYwDFMSWkQHEDyao',
    features: ['fi-2', 'fg-1', 'fey-1', 'fch-1', 'fc-3', 'fc-9', 'fea-1', 'fsk-4'],
  },
  {
    id: 'tm-107',
    name: 'ラジャー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1KomF_cIFzU-cPtokkkRbbCD88WtdOhXD',
    features: ['fha-2', 'fh-1', 'fg-1', 'fey-1', 'fc-3', 'fn-1', 'fea-2', 'fn-3', 'fsk-1', 'fsk-4', 'fty-2'],
  },
  {
    id: 'tm-108',
    name: 'レミー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1oV7R8ZFObNDaAD_dEBXNwpbSoy7zMe3F',
    features: ['fse-1', 'fg-1', 'fca-4', 'fmo-1', 'fc-2', 'fea-2', 'fea-1', 'fch-2', 'fn-3', 'fsk-30', 'fea-4'],
  },
  {
    id: 'tm-109',
    name: 'フリック',
    imgUrl: 'http://drive.google.com/uc?export=view&id=13gFbjyhJXEyehy7ATS2nrdEk4ohBjXb2',
    features: ['fse-1', 'fg-1', 'fey-1', 'fmo-1', 'fc-4', 'fsk-10'],
  },
  {
    id: 'tm-110',
    name: 'ガントゥ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1j91wLD2Z1vTp10MWJXcb3RGHVLOqYvBr',
    features: ['fg-1', 'fmo-1', 'fea-3', 'fc-2', 'fcat-3', 'fsp-2', 'fh-2', 'fsk-1', 'fsk-4'],
  },
  {
    id: 'tm-111',
    name: 'ワート',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1pjda_dE3eDNyLBAat-mUJXyK2XKioH_j',
    features: ['fha-2', 'fi-1', 'fg-1', 'fey-1', 'fc-3', 'fsk-5', 'fea-1', 'fsk-1', 'fsp-1'],
  },
  {
    id: 'tm-112',
    name: 'マーリン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1ef8V6fJ6uiYq6iCzP5a9yMjio9CbPn3i',
    features: ['fha-2', 'fg-1', 'fey-1', 'fca-4', 'fi-5', 'fea-1', 'fch-2', 'fc-4', 'fha-1', 'fsp-1'],
  },
  {
    id: 'tm-113',
    name: 'ダンテ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=16W0R1YKkHvfvj3sVgQklwafHNCgSjLDq',
    features: ['fn-2', 'fha-2', 'fse-1', 'fg-1', 'fey-1', 'fn-1', 'fmo-1', 'fea-3', 'fc-2', 'fea-2', 'fsk-1', 'fty-1', 'fi-3', 'fh-2', 'fea-4'],
  },
  {
    id: 'tm-114',
    name: 'ジョン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1uPqH6mi-BdXuXldFBPLMoiKrZGZ_-On0',
    features: ['fsk-7', 'fg-1', 'fey-1', 'fc-7', 'fca-4', 'fea-1', 'fsk-1', 'fsk-9'],
  },
  {
    id: 'tm-115',
    name: 'ウェンディ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1-ZstReTB4FsilfbldK0y9ItJeS5M2zw2',
    features: ['fca-1', 'fey-1', 'fc-7', 'fg-2', 'fch-1', 'fi-5', 'fea-1', 'fsk-3', 'fsk-1', 'fha-3', 'fsk-9', 'fey-2'],
  },
  {
    id: 'tm-116',
    name: 'フロロー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1l0xZhl4bq1R-Lt4S6yPRH6wuyuuB86S5',
    features: ['fg-1', 'fey-1', 'fca-4', 'fcat-3', 'fsk-5', 'fea-1', 'fsk-1', 'fha-1', 'fsp-1'],
  },
  {
    id: 'tm-117',
    name: 'クリスマスミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1QzDhEs1w_dqFxFbLojbyroJOcb2ac6gY',
    features: ['fn-2', 'fh-1', 'fg-1', 'fca-4', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fsk-3'],
  },
  {
    id: 'tm-118',
    name: 'クリスマスミニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=10_4Ra6D--hLihHpfc87kjmsq2rz-Xasw',
    features: ['fn-2', 'fca-1', 'fh-1', 'fg-2', 'fch-1', 'f-2', 'fi-5', 'fc-2', 'fea-1', 'fsk-8', 'fsk-10', 'fey-2'],
  },
  {
    id: 'tm-119',
    name: 'コンサートミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1qTO9ZYH0ZOaWZLPcOKpa7cjye9AFLVjT',
    features: ['fn-2', 'fh-1', 'fg-1', 'fca-4', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fc-1', 'fsp-1'],
  },
  {
    id: 'tm-120',
    name: 'クリスマスデイジー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1GfB5AOHhTpHKg9AauMzGfgE81O6cz5Bq',
    features: ['fca-1', 'fh-1', 'fca-4', 'fch-1', 'fg-2', 'fmo-1', 'fsp-5', 'fc-1', 'fsk-8', 'fi-3', 'fsk-10', 'fey-2'],
  },
  {
    id: 'tm-121',
    name: 'クリスマスドナルド',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1dl2s1Kv5tWuUC7WJOVu-QZ02rhSJOHo-',
    features: ['fha-2', 'fca-1', 'fh-1', 'fg-1', 'fca-4', 'fch-1', 'fmo-1', 'fsp-5', 'fc-1', 'fi-3', 'f-3'],
  },
  {
    id: 'tm-122',
    name: 'クリスマスプルート',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1CwxMzuWet5HHRYLrG487Gh3yDeFgoc8G',
    features: ['fca-1', 'fi-7', 'fg-1', 'fca-4', 'fc-3', 'fea-3', 'fsp-2', 'fey-3', 'fty-1', 'fsk-4', 'fh-3'],
  },
  {
    id: 'tm-123',
    name: 'クリスマスグーフィー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1GZJ8Dof9EW-uZWKS7dkNlfHprg_ZYMSd',
    features: ['fn-2', 'fha-2', 'fsk-7', 'fg-1', 'fsp-1', 'fca-4', 'fea-3', 'fc-2', 'fch-2', 'fey-3', 'fty-1', 'fha-4'],
  },
  {
    id: 'tm-124',
    name: 'バレンタインミニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Y7NHN4n8od9UJ5UA721bjNRQUBZoknxZ',
    features: ['fca-1', 'fh-1', 'fc-7', 'fg-2', 'fch-1', 'f-2', 'fi-5', 'fea-1', 'fsk-8', 'fsk-10', 'fey-2'],
  },
  {
    id: 'tm-125',
    name: 'バレンタインデイジー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1K-OOcX-t_sHJwBW5HxL8OV7OUT3lH2c7',
    features: ['fca-1', 'fc-7', 'fch-1', 'fg-2', 'fc-3', 'fmo-1', 'fsp-5', 'fsk-8', 'fi-3', 'fsk-10', 'fey-2', 'fh-3'],
  },
  {
    id: 'tm-126',
    name: 'かぼちゃミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1-h8umDIAOZXjiwcHQZJDk70ffXjLCGpf',
    features: ['fn-2', 'fi-7', 'fh-1', 'fg-1', 'fca-4', 'fc-3', 'fi-5', 'f-1', 'fea-1', 'fcat-4', 'fsk-30', 'fsk-15'],
  },
  {
    id: 'tm-127',
    name: 'かぼちゃミニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1-iY-E26WsS4W4glpKL0TLXDizLmPtRaI',
    features: ['fn-2', 'fca-1', 'fi-7', 'fh-1', 'fca-4', 'fg-2', 'fch-1', 'f-2', 'fi-5', 'fea-1', 'fcat-4', 'fsk-15', 'fey-2', 'fc-10', 'fea-4'],
  },
  {
    id: 'tm-128',
    name: 'ホーンハットミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1wZxCakffnHXMoKLcxJyseIUpnyKlW0jS',
    features: ['fn-2', 'fc-6', 'fh-1', 'fg-1', 'fsk-14', 'fca-4', 'fmo-1', 'fi-5', 'fc-2', 'fsk-11', 'fea-1', 'f-1', 'fsp-2', 'fsk-15', 'fi-9'],
  },
  {
    id: 'tm-129',
    name: 'キャットハットミニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1IFKwM5AYERY2JM5tkIBMCvg6MJnV_qSO',
    features: ['fn-2', 'fca-1', 'fh-1', 'fsk-14', 'fca-4', 'fg-2', 'fch-1', 'f-2', 'fi-5', 'fea-2', 'fch-2', 'fsk-15', 'fsk-8', 'fc-8', 'fsk-10', 'fey-2', 'fty-2', 'fea-4'],
  },
  {
    id: 'tm-130',
    name: 'かぼちゃチップ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1RshmtzVbt8Oeil4Q_JgsgUUHZgKDoldl',
    features: ['fn-2', 'fg-1', 'fca-4', 'fch-1', 'fsk-9', 'fc-3', 'fn-1', 'fmo-1', 'fc-7', 'fcat-4', 'fsk-15', 'fsk-10'],
  },
  {
    id: 'tm-131',
    name: 'おばけデール',
    imgUrl: 'http://drive.google.com/uc?export=view&id=14D6lgoU81zLtzz5VQ7ILko-P7OcdtNYH',
    features: ['fg-1', 'fsk-14', 'fea-2', 'fc-1', 'fn-3', 'fcat-4', 'fsk-15', 'fsk-10', 'fi-3', 'fsk-9'],
  },
  {
    id: 'tm-132',
    name: 'ウサプー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1zlEXS0KG7aSDwLEJcmiB8uXS9kDzVj9E',
    features: ['fi-2', 'fi-7', 'fg-1', 'fey-1', 'fca-4', 'fc-3', 'fn-1', 'fsk-11', 'fc-4', 'fty-3', 'fh-3'],
  },
  {
    id: 'tm-133',
    name: 'ウサティガー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=12kkOqqZ1JbzUXydXGCJmTWx6zLPJBbs_',
    features: ['fi-2', 'fsk-26', 'fg-1', 'fey-1', 'fca-4', 'fc-3', 'fn-1', 'fch-2', 'fn-3', 'fty-3', 'fh-3', 'fi-9', 'fea-4', 'fty-2'],
  },
  {
    id: 'tm-134',
    name: 'ハチプー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1todVIkKIaJ5WQIPN8-7OH4FUw07cHJXH',
    features: ['fi-2', 'fi-7', 'fg-1', 'fey-1', 'fca-4', 'fc-3', 'fn-1', 'fea-1', 'fsp-2', 'fsk-20', 'fh-3'],
  },
  {
    id: 'tm-135',
    name: 'ハワイアンスティッチ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1c33OrFKQt6smMqnyVG2astd4zu5O2w1w',
    features: ['fsk-26', 'fha-2', 'fg-1', 'fi-8', 'fmo-1', 'fea-2', 'fca-3', 'fc-4', 'fsp-1'],
  },
  {
    id: 'tm-136',
    name: 'ジャック',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1ISTqjJ_0botiy4mW4oIKw0agCUG51iDI',
    features: ['fn-2', 'fh-1', 'fg-1', 'fsk-14', 'fi-8', 'fmo-1', 'fc-1', 'fcat-4', 'fi-4'],
  },
  {
    id: 'tm-137',
    name: 'サリー(NBC)',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1YAJYdY6IMNx7ib-Os4kQ1C1rppb_fz_0',
    features: ['fc-6', 'fc-5', 'fg-2', 'fi-8', 'fmo-1', 'fcat-4', 'fc-4', 'fey-2', 'fsk-16'],
  },
  {
    id: 'tm-138',
    name: 'ゼロ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1UtD94YrkZVbxSjZRfczp9LPPPWcWVbba',
    features: ['fg-1', 'fea-2', 'fc-1', 'fcat-4', 'fty-1'],
  },
  {
    id: 'tm-139',
    name: 'ロマンスアリエル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1ATB8D0AuDUuxFi8cX4Dpo3JBxlascFDt',
    features: ['fca-1', 'fi-1', 'fc-6', 'fha-2', 'fg-2', 'fch-1', 'fc-9', 'fsp-4', 'fea-1', 'fsk-8', 'fsp-3', 'fha-3', 'fsk-10', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-140',
    name: 'ソーサラーミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=176sfL_DfsUt3y4XjcN_Rv9bIKbCcjBmY',
    features: ['fn-2', 'fca-1', 'fh-1', 'fg-1', 'fsk-31', 'fca-4', 'fi-8', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fsp-1'],
  },
  {
    id: 'tm-141',
    name: 'ペリー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=111-sTYbe0CgCSrJVlRkdkH05f1KmwcZ4',
    features: ['fha-2', 'fi-7', 'fc-5', 'fg-1', 'fmo-1', 'fsp-5', 'fey-3', 'fc-4', 'fha-4', 'fsk-18'],
  },
  {
    id: 'tm-142',
    name: 'ヨーダ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1HoRLUEZKC971NuUhrgLUYrF00ZRBxk_A',
    features: ['fea-2', 'fsk-20', 'fc-5', 'fg-1'],
  },
  {
    id: 'tm-143',
    name: 'R2-D2',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1iwS5d1ZXx4V3dFtAMppnLyK_fDK_0OUq',
    features: ['fh-1', 'fg-1', 'fsk-33', 'fc-1', 'fc-4'],
  },
  {
    id: 'tm-144',
    name: 'ルーク',
    imgUrl: 'http://drive.google.com/uc?export=view&id=17LvUMeSTIsSNqVeoYlnDG0b0j_dAHDf3',
    features: ['fg-1', 'fca-4', 'fc-3', 'fc-9', 'fi-8', 'fc-1', 'fh-2', 'fsk-16'],
  },
  {
    id: 'tm-145',
    name: 'ダースベイダー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1MoTtmZQ-nxKocOe8DReLDBt7sc1izY87',
    features: ['fn-2', 'fg-1', 'fca-4', 'fmo-1', 'fcat-3', 'fc-2', 'fh-2', 'fi-3'],
  },
  {
    id: 'tm-146',
    name: 'BB-8',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1D7mdnNzoXfEbmaSbP-OophvveegOrSvT',
    features: ['fi-2', 'fg-1', 'fc-1', 'fsk-32', 'fsk-4'],
  },
  {
    id: 'tm-147',
    name: 'クラリス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1VOtumtFX2vcJwCBMWGFFpwcQhMH5zoWE',
    features: ['fsk-9', 'fg-2', 'fch-1', 'fc-3', 'fn-1', 'fc-7', 'fea-2', 'fca-3', 'fsk-10', 'fey-2', 'fh-3', 'fea-4'],
  },
  {
    id: 'tm-148',
    name: 'モカ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1mWNsi7H8zchiU5qmm6dyB0CRbJssImSK',
    features: ['fn-2', 'fg-1', 'fc-7', 'fmo-1', 'fi-5', 'fea-1'],
  },
  {
    id: 'tm-149',
    name: 'プリン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1VdhMQRbW1llkqQQXP_aFidZbXnyzfBLF',
    features: ['fn-2', 'fca-1', 'fi-7', 'fc-7', 'fg-2', 'fmo-1', 'fea-1', 'fsk-3', 'fsk-8', 'fsk-10', 'fey-2'],
  },
  {
    id: 'tm-150',
    name: 'ブライドラプンツェル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1oRLYBNGzWDbgLUols6HSntEAzaL8UJ4A',
    features: ['fi-2', 'fca-2', 'fey-1', 'fc-7', 'fg-2', 'fc-9', 'fsk-5', 'fea-1', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-151',
    name: 'カイロレン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1OcPgkHD3HfCummX_twlaavsgEw72C2xT',
    features: ['fn-2', 'fsk-17', 'fg-1', 'fca-4', 'fcat-3', 'fc-2', 'fh-2'],
  },
  {
    id: 'tm-152',
    name: 'レイ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1GzJI1pb4tyhdxDvLch-0rRQN4GE3y92q',
    features: ['fey-1', 'fc-7', 'fg-2', 'fca-4', 'fc-9', 'fsk-4', 'fey-2'],
  },
  {
    id: 'tm-153',
    name: 'おしゃれマッドハッター',
    imgUrl: 'http://drive.google.com/uc?export=view&id=14V1sdGYLDciCnJ_1TWIu-sXRxDv0HmXw',
    features: ['fca-1', 'fha-2', 'fc-6', 'fh-1', 'fg-1', 'fey-1', 'fca-4', 'fi-5', 'fc-1', 'fsk-25', 'fi-9'],
  },
  {
    id: 'tm-154',
    name: 'ワンダーランドアリス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1dzuNPJsuzJXa7gfJroOSns-hp9swW32g',
    features: ['fca-1', 'fch-1', 'fg-2', 'fc-3', 'fc-9', 'fea-1', 'fey-2'],
  },
  {
    id: 'tm-155',
    name: 'モーグリ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1rCU_x_qOlGFjl3R8UJduq93RuSOX0Azm',
    features: ['fha-2', 'fg-1', 'fey-1', 'fc-9', 'fi-5', 'fc-2', 'fsk-4', 'fsk-9'],
  },
  {
    id: 'tm-156',
    name: 'エリザベススワン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1nQpVnFY5E90k0FYuhDVgev66WnrEKGAb',
    features: ['fha-2', 'fey-1', 'fca-4', 'fg-2', 'fch-1', 'fc-7', 'fi-8', 'fc-9', 'fea-1', 'fsk-8', 'fsp-1', 'fsk-10', 'fey-2'],
  },
  {
    id: 'tm-157',
    name: 'ジャックスパロウ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1vC9Ho2GP8oeoGjJH2HzWd3LzCgE2IEy5',
    features: ['fsk-6', 'fg-1', 'fey-1', 'fca-4', 'fc-7', 'fc-9', 'fi-8', 'fch-2', 'fha-3', 'fi-4'],
  },
  {
    id: 'tm-158',
    name: 'デイヴィジョーンズ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1jYQsY2sjvcmYhgy7nYIHs-d3bKM-XY0G',
    features: ['fg-1', 'fca-4', 'fc-7', 'fcat-3', 'fch-2', 'fsk-3', 'fsp-3', 'fi-3', 'fi-4'],
  },
  {
    id: 'tm-159',
    name: 'パレードミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1bT5dJ6BtugmFGcKCzc5cFxywV7hDa4zX',
    features: ['fn-2', 'fca-1', 'fi-7', 'fh-1', 'fg-1', 'fsp-1', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fsk-30', 'fsk-4'],
  },
  {
    id: 'tm-160',
    name: 'パレードティンク',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1rWHCdRa7SV7DSqfwDEEBbZIr-DXl8hi7',
    features: ['fca-1', 'fi-7', 'fey-1', 'fg-2', 'fch-1', 'fc-9', 'fc-3', 'fsk-4', 'fsk-11', 'fea-1', 'fsk-30', 'fha-3', 'fi-9', 'fey-2'],
  },
  {
    id: 'tm-161',
    name: '蒸気船ミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=11lHi0P5zs92c4aPgc7wk-QDS8nqTJ-PF',
    features: ['fn-2', 'fg-1', 'fca-4', 'fi-8', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fc-1', 'fsk-32', 'fh-2', 'fi-4'],
  },
  {
    id: 'tm-162',
    name: '蒸気船ピート',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1TyENIbWXAcwKihtRFxO0gm_wvF8UWKH-',
    features: ['fn-2', 'fi-7', 'fg-1', 'fca-4', 'fi-8', 'fcat-3', 'fc-2', 'fea-2', 'fch-2', 'fc-1', 'fsk-5', 'fh-2', 'fty-2', 'fi-4'],
  },
  {
    id: 'tm-163',
    name: '蒸気船ミニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=156XO85S2Fkx4sQCRRdmyIEkBuwO2q73i',
    features: ['fn-2', 'fsk-7', 'fca-4', 'fg-2', 'fi-8', 'f-2', 'fi-5', 'fc-2', 'fea-1', 'fc-1', 'fca-3', 'fsk-8', 'fh-2', 'fey-2', 'fi-4'],
  },
  {
    id: 'tm-164',
    name: 'K2SO',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Gvn1ZHuWScXPxiSWCWYV0VWwcVkO8tdI',
    features: ['fn-2', 'fg-1', 'fmo-1', 'fc-2', 'fsk-3', 'fh-2'],
  },
  {
    id: 'tm-165',
    name: 'ジェダイルーク',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1brjKK2NVCcg_ECa7m2YKGpZCrOGsQAjH',
    features: ['fg-1', 'fey-1', 'fca-4', 'fc-7', 'fc-9', 'fh-2', 'fsk-9', 'fi-4'],
  },
  {
    id: 'tm-166',
    name: 'ハンソロ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1wf2Bun6XR2Lh-n4ozZYZs-gkSUw66k24',
    features: ['fg-1', 'fey-1', 'fc-7', 'fc-9', 'fi-8', 'fea-1', 'fsk-3', 'fsk-9'],
  },
  {
    id: 'tm-167',
    name: 'チューバッカ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Jk4jvHVkem_qufWUDCzREz83NjXt5ugQ',
    features: ['fn-2', 'fha-2', 'fg-1', 'fc-7', 'fn-1', 'fmo-1', 'fch-2', 'fsk-4'],
  },
  {
    id: 'tm-168',
    name: 'ベイマックス2.0',
    imgUrl: 'http://drive.google.com/uc?export=view&id=12vyEz6WAcDutg-5DpBDahMDsq90_aKGY',
    features: ['fi-2', 'fc-6', 'fg-1', 'fca-4', 'fsk-4'],
  },
  {
    id: 'tm-169',
    name: 'ヒロ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1V907RhhVuWSOuH5MtYEet4XmCRu95yqC',
    features: ['fg-1', 'fey-1', 'fca-4', 'fc-8', 'fsk-4', 'fsk-9'],
  },
  {
    id: 'tm-170',
    name: 'ホイップ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1u6_DxrNeM4UOuBGIZKM_p1YHvzShvlet',
    features: ['fh-1', 'fg-1', 'fsk-7', 'fn-1', 'fmo-1', 'fea-1', 'fc-1', 'fsk-8'],
  },
  {
    id: 'tm-171',
    name: 'パフィー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=11uhD87F-tuQF7xJA9DghgPNTdMBYtzO6',
    features: ['fca-1', 'fi-7', 'fh-1', 'fg-2', 'fn-1', 'fmo-1', 'fea-1', 'fc-1', 'fsk-8', 'fsk-10', 'fey-2'],
  },
  {
    id: 'tm-172',
    name: '三銃士ミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=139Sd54dG4V1Vi9dVrF-KsWNMjHiLd4_Z',
    features: ['fn-2', 'fsk-6', 'fh-1', 'fg-1', 'fca-4', 'fi-8', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fsk-5', 'fsp-1', 'fsk-9'],
  },
  {
    id: 'tm-173',
    name: '三銃士ドナルド',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1_zLTNi9fPexQaUpsCMEBCKoKMP7ZrDlK',
    features: ['fha-2', 'fh-1', 'fg-1', 'fsk-7', 'fca-4', 'fch-1', 'fi-8', 'fmo-1', 'fi-5', 'fsp-5', 'fc-1', 'fi-3', 'fsp-1', 'f-3'],
  },
  {
    id: 'tm-174',
    name: '三銃士グーフィー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=10M62ZsmeHP7jfIIIBqHvp_WyARJV_uX3',
    features: ['fn-2', 'fsk-24', 'fh-1', 'fg-1', 'fca-4', 'fi-8', 'fi-5', 'fea-3', 'fc-2', 'fey-3', 'fty-1', 'fsp-1'],
  },
  {
    id: 'tm-175',
    name: 'お姫様デイジー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1QJpFtmeKm8mHA2qDO5mLgKSv8eUKPyJt',
    features: ['fca-1', 'fi-7', 'fca-2', 'fh-1', 'fsp-1', 'fg-2', 'fch-1', 'fmo-1', 'fc-2', 'fsp-5', 'fc-1', 'fsk-8', 'fi-3', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-176',
    name: '忍者ドナルド',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1b6Oaa9Kwc1jzUCp3TcpO_P2D8cxQqyLI',
    features: ['fha-2', 'fca-1', 'fh-1', 'fg-1', 'fch-1', 'fi-6', 'fmo-1', 'fsk-11', 'fsp-5', 'fc-1', 'fsk-23', 'fi-3', 'fha-3', 'f-3'],
  },
  {
    id: 'tm-177',
    name: 'キュートアナ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1wW0LHk3tw8MHgTeOTZgcRKWgcaLXyl42',
    features: ['fi-1', 'fey-1', 'fc-7', 'fg-2', 'fc-9', 'fsk-4', 'fea-1', 'fey-3', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-178',
    name: 'キュートエルサ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1LIA2TCZSJScB2-Wmxc23OxUxpbaVOe8Y',
    features: ['fey-1', 'fg-2', 'fc-9', 'fea-1', 'fey-3', 'fsk-19', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-179',
    name: 'サマーオラフ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1ndpQTNnsIvr_BNIgxVzhyNOCA-FcbC7O',
    features: ['fg-1', 'fey-1', 'fca-4', 'fi-8', 'fmo-1', 'fc-1'],
  },
  {
    id: 'tm-180',
    name: 'ファンタズミックミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1WiDJuf3n0ontT4PSVSIdaK_Cog9M5u_x',
    features: ['fn-2', 'fca-1', 'fh-1', 'fg-1', 'fey-1', 'fca-4', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fsk-30', 'fsp-1'],
  },
  {
    id: 'tm-181',
    name: 'ソラ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1LT8eOE4FjdZYXEUo4scCJNCv4lXfLAX6',
    features: ['fha-2', 'fca-2', 'fh-1', 'fg-1', 'fey-1', 'fc-7', 'fc-9', 'fi-8', 'fsp-1', 'fsk-10'],
  },
  {
    id: 'tm-182',
    name: 'リク',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1T6xFxhDSv1uONK_iPr-nOMOUpvIKBu5B',
    features: ['fha-2', 'fg-1', 'fey-1', 'fsk-31', 'fc-9', 'fc-1', 'fh-2', 'fha-1', 'fsp-1', 'fsk-10'],
  },
  {
    id: 'tm-183',
    name: 'ロマンス野獣',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1u5J58Z1SCS8boF2pYG7Jm-H4EK_ERkAS',
    features: ['fi-2', 'fha-2', 'fg-1', 'fey-1', 'fc-7', 'fch-2', 'fsp-2', 'fsk-3', 'fcat-2'],
  },
  {
    id: 'tm-184',
    name: 'ロマンスベル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1wE5B0Xp9vSf4JlXmOZMjkTPdyMPgKGhI',
    features: ['fi-2', 'fca-1', 'fha-2', 'fey-1', 'fg-2', 'fch-1', 'fc-9', 'fea-1', 'fsk-8', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-185',
    name: 'ハッピーラプンツェル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1SJ4KG3DJRghiGpA_CMRbLugKiiTmyOKf',
    features: ['fey-1', 'fg-2', 'fc-3', 'fc-9', 'fea-1', 'fca-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-186',
    name: 'ヤングジャックスパロウ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=12SiMILXdLc0qzBt0BvaA1JVqRr3PYW2U',
    features: ['fha-2', 'fg-1', 'fey-1', 'fca-4', 'fc-5', 'fsk-31', 'fc-9', 'fi-8', 'fch-2', 'fha-3'],
  },
  {
    id: 'tm-187',
    name: 'サラザール',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1EXqO9RUfAALZdpmGmXaUiUpWPPICMZK3',
    features: ['fha-2', 'fsk-6', 'fi-1', 'fh-1', 'fg-1', 'fey-1', 'fi-8', 'fcat-3', 'fc-2', 'fea-1', 'fsp-3'],
  },
  {
    id: 'tm-188',
    name: '鍵犬',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1LBQBYSD1b9HbDwGUVsrieX0Mthh7nw-K',
    features: ['fn-2', 'fha-2', 'fh-1', 'fg-1', 'fey-1', 'fea-3', 'fch-2', 'fc-1', 'fsk-3', 'fty-1', 'fi-3'],
  },
  {
    id: 'tm-189',
    name: 'パイレーツミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=183QWs7CRvBTWv84dzCmb-7GPs9FHWUDG',
    features: ['fn-2', 'fi-7', 'fc-6', 'fh-1', 'fg-1', 'fey-1', 'fca-4', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fsk-3', 'fsp-1'],
  },
  {
    id: 'tm-190',
    name: 'パイレーツスティッチ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=195wifQoHVMdHVvlS1K8zA7LCBkBsWbsL',
    features: ['fi-7', 'fg-1', 'fca-4', 'fi-8', 'fmo-1', 'fc-2', 'fsk-5', 'fea-2', 'fc-4'],
  },
  {
    id: 'tm-191',
    name: 'パイレーツクラリス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1t7zCi9IWYvT8nbZFdC4-GprzJdMo9SPa',
    features: ['fi-7', 'fsk-7', 'fca-4', 'fg-2', 'fch-1', 'fc-3', 'fn-1', 'fn-3', 'fca-3', 'fc-8', 'fsk-9', 'fey-2', 'fh-3'],
  },
  {
    id: 'tm-192',
    name: 'MUマイク',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Hy4GvfoVLT2Hq3vR_xidkyOKSLwCoOdh',
    features: ['fse-1', 'fg-1', 'fc-5', 'fca-4', 'fi-5', 'fsk-5', 'fsp-2', 'fey-3'],
  },
  {
    id: 'tm-193',
    name: 'ジェットパックエイリアン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1zWz1iZWZUKprp0CEfxF3UC7uayR-YBPs',
    features: ['fi-1', 'fse-1', 'fc-5', 'fsp-6', 'fmo-1', 'fea-2', 'fey-3', 'fsp-2', 'fi-4'],
  },
  {
    id: 'tm-194',
    name: 'ウォーリー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=13vhoeHRFyR8u4i9qkvLdX_rKKiVLBnit',
    features: ['fse-1', 'fh-1', 'fg-1', 'fc-3', 'fey-3'],
  },
  {
    id: 'tm-195',
    name: 'カールじいさん',
    imgUrl: 'http://drive.google.com/uc?export=view&id=18yp4JC4pJqcr9O_e4lLpFLBQfebT2tri',
    features: ['fse-1', 'fca-1', 'fha-2', 'fg-1', 'fey-1', 'fc-9', 'fea-1', 'fc-1', 'fha-1', 'fsk-4'],
  },
  {
    id: 'tm-196',
    name: 'ハロウィンソラ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1SNACuuJOZH6yMtrgrR2QGtePMVd12fXm',
    features: ['fha-2', 'fca-2', 'fh-1', 'fg-1', 'fsk-14', 'fc-7', 'fc-9', 'fi-8', 'fmo-1', 'fsk-11', 'fcat-4', 'fsp-2', 'fsk-15', 'fsp-1', 'fsk-10'],
  },
  {
    id: 'tm-197',
    name: 'まきまきドナルド',
    imgUrl: 'http://drive.google.com/uc?export=view&id=12IKBX1aFzHqPZr1oXv_a8ywCqMN7KZdm',
    features: ['fha-2', 'fh-1', 'fg-1', 'fc-3', 'fmo-1', 'fi-5', 'fsk-13', 'fsp-5', 'fc-1', 'fcat-4', 'fsk-15', 'fi-3', 'fsk-10', 'f-3'],
  },
  {
    id: 'tm-198',
    name: 'ねじねじグーフィー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1FPsicpBvK2VpAhWiV40xbtVbQLLZXLoB',
    features: ['fha-2', 'fg-1', 'fi-6', 'fea-3', 'fc-2', 'fcat-4', 'fey-3', 'fsk-15', 'fty-1', 'fsk-4', 'fsk-10', 'fh-2'],
  },
  {
    id: 'tm-199',
    name: 'パンプキンキング',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1yhS0APqaqLHX8B1uvwCy9OKAXwpKg-3l',
    features: ['fi-7', 'fg-1', 'fsk-14', 'fc-7', 'fn-1', 'fmo-1', 'fcat-4', 'fsk-15'],
  },
  {
    id: 'tm-200',
    name: 'ブギー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1-VudrKNum_DkvOl6YxZPq6UCu0K38enK',
    features: ['fi-2', 'fh-1', 'fg-1', 'fsk-7', 'fmo-1', 'fcat-3', 'fc-1', 'fcat-4', 'fsk-10'],
  },
  {
    id: 'tm-201',
    name: 'ごきげんプー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1JMqudnYMzUm_neZG7FDWS7ZKtWGOHfYs',
    features: ['fi-7', 'fg-1', 'fey-1', 'fc-3', 'fn-1', 'fmo-1', 'fea-1', 'fsp-1', 'fsk-10', 'fh-3'],
  },
  {
    id: 'tm-202',
    name: 'さむがりピグレット',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1jFjpdkHouQxpUy12Umvb2_dLFZi8_S4G',
    features: ['fi-7', 'fg-1', 'fey-1', 'fch-1', 'fn-1', 'fi-8', 'fea-2', 'fn-3', 'fea-4', 'fc-10'],
  },
  {
    id: 'tm-203',
    name: 'オウル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1a6R0E-5Dp5PVje9q-dQGMDj5zNMMi2j3',
    features: ['fg-1', 'fey-1', 'fc-7', 'fc-3', 'fmo-1', 'fsk-11', 'fsp-5'],
  },
  {
    id: 'tm-204',
    name: 'ランピー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1N9TFf81OUxAwFrXsnzMUmHlsK9CPPY2k',
    features: ['fha-2', 'fg-1', 'fey-1', 'fsk-18', 'fsk-13', 'fea-3', 'fc-8', 'fsk-9', 'fea-4', 'fc-10'],
  },
  {
    id: 'tm-205',
    name: 'ドロッセル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1-FSK--0NPXqdGOcNTSy-s4GX7eTijWdo',
    features: ['fh-1', 'fg-2', 'fc-1', 'fsk-3', 'fi-3', 'fha-1', 'fha-3', 'fsk-9'],
  },
  {
    id: 'tm-206',
    name: 'ハッピー白雪姫',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1DWHyezD0d4hJRXe7SSOM02QilYopD4gI',
    features: ['fca-1', 'fey-1', 'fg-2', 'fch-1', 'fc-9', 'fi-8', 'fc-2', 'fsk-3', 'fsp-1', 'fsk-9', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-207',
    name: 'ホリデーベイマックス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1XS2JhU0TQd-z1N8nZr-GYfwmUppVOMF-',
    features: ['fi-2', 'fc-6', 'fh-1', 'fg-1', 'fca-4', 'fc-1'],
  },
  {
    id: 'tm-208',
    name: 'ホリデーマリー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1f1IFAvNh9m7Ss4LrovVEus7jm7aD8dpu',
    features: ['fca-1', 'fha-2', 'fca-4', 'fg-2', 'fch-1', 'fn-1', 'fi-5', 'fsk-11', 'fch-2', 'fc-1', 'fea-2', 'fn-3', 'fey-2', 'fha-3', 'fsk-10', 'fea-4', 'fty-2'],
  },
  {
    id: 'tm-209',
    name: 'ホリデードナルド',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1v4YEealdxe9fFznZ9vbdLNO2xQ6L1Ton',
    features: ['fha-2', 'fc-6', 'fh-1', 'fg-1', 'fca-4', 'fch-1', 'fmo-1', 'fsp-5', 'fch-2', 'fc-1', 'fi-3', 'f-3'],
  },
  {
    id: 'tm-210',
    name: 'ウィンターシンデレラ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=16VEqEWE29kNLS6XMbxyHdhrDy6krW84q',
    features: ['fsp-1', 'fey-1', 'fg-2', 'fch-1', 'fc-9', 'fc-3', 'fi-8', 'fsk-8', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-211',
    name: 'ウィンターオーロラ姫',
    imgUrl: 'http://drive.google.com/uc?export=view&id=18Llrcyg0nka5yAecQcegk7LIQ2ZUDO6J',
    features: ['fi-2', 'fi-1', 'fi-7', 'fca-2', 'fey-1', 'fg-2', 'fch-1', 'fc-9', 'fc-3', 'fsp-1', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-212',
    name: 'ウィンターベル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=15AsVC0Y1brMjt3bMLBZawJHEWHCtthIK',
    features: ['fi-2', 'fc-6', 'fey-1', 'fca-4', 'fg-2', 'fch-1', 'fc-9', 'fsk-8', 'fha-3', 'fsk-10', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-213',
    name: 'アイドルチップ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1If2FfIc7NhrKQehm312JhgfxCvbPhtpz',
    features: ['fn-2', 'fca-1', 'fi-1', 'fg-1', 'fch-1', 'fn-1', 'fea-2', 'fsk-5', 'fc-4', 'fsk-30', 'fi-3', 'fsk-9', 'fea-4'],
  },
  {
    id: 'tm-214',
    name: 'アイドルデール',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1mPNfq2btKLqxmJgpfpeLvUKkegdi0Kz8',
    features: ['fi-1', 'fca-1', 'fg-1', 'fch-1', 'fea-2', 'fc-8', 'fn-3', 'fsk-30', 'fi-3', 'fsk-4', 'fsk-9', 'fea-4'],
  },
  {
    id: 'tm-215',
    name: 'プラクティカル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Rr1IZP9C7qZY1N2WPnQfOMP0TjlkCOnJ',
    features: ['fi-7', 'fh-1', 'fg-1', 'fey-1', 'fca-4', 'fch-1', 'fn-1', 'fea-2', 'fn-3', 'fea-4', 'fc-10'],
  },
  {
    id: 'tm-216',
    name: 'ビッグバッドウルフ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1hRlH6a5SZnq3OihzpkfqYyIRH3h9_hLl',
    features: ['fn-2', 'fi-2', 'fha-2', 'fh-1', 'fg-1', 'fca-4', 'fc-7', 'fc-3', 'fcat-3', 'fea-2', 'fch-2', 'fsk-19'],
  },
  {
    id: 'tm-217',
    name: 'イェンシッド',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1DQXVzu7pME6XJGuJI-YVVLO3az8jbg3o',
    features: ['fg-1', 'fey-1', 'fca-4', 'fc-9', 'fi-8', 'fch-2', 'fea-1', 'fc-4'],
  },
  {
    id: 'tm-218',
    name: 'チェルナボーグ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1APNe_pxZWvgMh4o4AC-KfI2YEWJzbL7i',
    features: ['fg-1', 'fey-1', 'fn-1', 'fmo-1', 'fcat-3', 'fea-2', 'fsk-5', 'fsp-2', 'fc-4'],
  },
  {
    id: 'tm-219',
    name: 'D23スペシャルミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1HrUzp4enDTubbydiiZNu6sawz3zT2l_R',
    features: ['fn-2', 'fca-1', 'fh-1', 'fg-1', 'fsk-7', 'fca-4', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fsk-30', 'fsk-8', 'fc-4', 'fi-3', 'fsp-1', 'fsk-9'],
  },
  {
    id: 'tm-220',
    name: 'ウッディ保安官',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1pDK_QETfebvFOHDBp8BPyL9V16Bpufuh',
    features: ['fse-1', 'fi-7', 'fg-1', 'fey-1', 'fca-4', 'fch-1', 'fc-7', 'fc-9', 'fi-8', 'fsk-5', 'fea-1', 'fsk-9'],
  },
  {
    id: 'tm-221',
    name: 'スペースレンジャーバズ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1QTdq3H4eOcfsDIyRMQKguYGk7LKlxk6z',
    features: ['fi-2', 'fse-1', 'fsk-22', 'fh-1', 'fg-1', 'fey-1', 'fc-9', 'fi-8', 'fmo-1', 'fsk-13', 'fc-8', 'fsk-9'],
  },
  {
    id: 'tm-222',
    name: 'ザーグ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1hP95QwqUj4e2MQEyGr1NT6s-1YUfDOg4',
    features: ['fse-1', 'fh-1', 'fg-1', 'fmo-1', 'fcat-3', 'fsp-2', 'fc-8', 'fsp-1', 'fsk-18'],
  },
  {
    id: 'tm-223',
    name: 'ミゲル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1m-LzLMTix8azxrezwlMQ84wkh9mGpmgQ',
    features: ['fse-1', 'fha-2', 'fg-1', 'fey-1', 'fc-7', 'fc-9', 'fi-5', 'fc-2', 'fea-1', 'fsk-3'],
  },
  {
    id: 'tm-224',
    name: 'ホリデーオラフ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1ZslVv5sU82XKiohh_f5zNsChED1Vylii',
    features: ['fha-2', 'fg-1', 'fey-1', 'fmo-1', 'fc-1', 'fha-4', 'fsk-4'],
  },
  {
    id: 'tm-225',
    name: '警察官ジュディ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1W8Th6bGao3F8n8k0ZMPJquWJYyW4bTAA',
    features: ['fi-7', 'fh-1', 'fey-1', 'fg-2', 'fmo-1', 'fc-2', 'fea-2', 'fsk-3', 'fn-3', 'fh-2', 'fey-2', 'fty-3', 'fsp-1', 'fsk-9', 'fea-4', 'fi-4'],
  },
  {
    id: 'tm-226',
    name: '警察官ニック',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1By1scIdgdk2gRCYeRrXIJuPfeqaI0FGe',
    features: ['fn-2', 'fi-7', 'fg-1', 'fey-1', 'fc-7', 'fn-1', 'fi-6', 'fmo-1', 'fea-2', 'fsk-3', 'fsp-1', 'fsk-9'],
  },
  {
    id: 'tm-227',
    name: 'クロウハウザー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1dgaJ3ILi7vlmKmO5qS1GHpaiR8i2LT5i',
    features: ['fty-2', 'fg-1', 'fey-1', 'fc-3', 'fea-2', 'fsp-1', 'fsk-10', 'fh-3'],
  },
  {
    id: 'tm-228',
    name: 'フラッシュ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1QTUR2yvpa0R8qlQb6uUX4FspdIAQhYDs',
    features: ['fha-2', 'fey-3', 'fg-1', 'fey-1'],
  },
  {
    id: 'tm-229',
    name: 'スプリングミスバニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1suCdO8QMoY9to-0TBxVJ_UgrjFYQjH1u',
    features: ['fi-2', 'fca-2', 'fg-2', 'fch-1', 'fc-3', 'fi-8', 'fn-1', 'fsk-13', 'fi-5', 'fsk-11', 'fea-2', 'fca-3', 'fn-3', 'fey-2', 'fty-3', 'fsk-10', 'fea-4', 'fh-3'],
  },
  {
    id: 'tm-230',
    name: 'アイアンマン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1vj2VjNu50XZdorRZ4d9k3nX_DWogFP2V',
    features: ['fi-1', 'fc-6', 'fsk-7', 'fg-1', 'fca-4', 'fc-3', 'fmo-1'],
  },
  {
    id: 'tm-231',
    name: 'スパイダーマン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1R-PORJYEGd-Bkjs3_kzLdRfvIXrGsFkB',
    features: ['fc-6', 'fg-1', 'fca-4', 'fch-1', 'fi-8'],
  },
  {
    id: 'tm-232',
    name: 'キャプテンアメリカ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1dVTipd_iF7Tc9Lx0orrN8K2jvTzgjA51',
    features: ['fi-1', 'fg-1', 'fca-4', 'fsk-23', 'fea-1', 'fc-4'],
  },
  {
    id: 'tm-233',
    name: 'サノス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1JCD4ZjJXnGGCwcCsuTTalMZ3UB-wox_v',
    features: ['fg-1', 'fca-4', 'fc-3', 'fi-8', 'fcat-3', 'fsk-3', 'fc-4', 'fc-8', 'fi-9', 'fh-3'],
  },
  {
    id: 'tm-234',
    name: 'ホセ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1QXIrftxHlLZ-3lELPVuw_Yk1D04PMScT',
    features: ['fca-1', 'fha-2', 'fg-1', 'fc-5', 'fca-4', 'fmo-1', 'fsp-5', 'fsk-9', 'fh-3', 'fi-4'],
  },
  {
    id: 'tm-235',
    name: 'パンチート',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1O2hKRihz_yrqj0cd27PGYzxMZ0XigTOs',
    features: ['fha-2', 'fi-7', 'fc-6', 'fh-1', 'fg-1', 'fca-4', 'fmo-1', 'fsp-5', 'fha-4', 'fsk-9', 'fsk-4'],
  },
  {
    id: 'tm-236',
    name: 'ブライドアリエル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1lvl4M32C2SwHQJC79FPUDLB_MozGQpns',
    features: ['fi-2', 'fi-1', 'fc-6', 'fca-2', 'fg-2', 'fch-1', 'fc-9', 'fea-1', 'fsk-8', 'fsk-10', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-237',
    name: 'ティアナ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=11BlB-EeGvXITUqkOJ55VtgKCEYyRYfc9',
    features: ['fha-2', 'fca-2', 'fey-1', 'fc-7', 'fg-2', 'fc-9', 'fc-2', 'fsk-5', 'fea-1', 'fsk-8', 'fha-3', 'fi-9', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-238',
    name: 'ブライドジャスミン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1xrglrZwV-AVGfEUBMw6DoIrgQ30mvF4_',
    features: ['fi-2', 'fey-1', 'fc-7', 'fg-2', 'fch-1', 'fc-9', 'fsk-18', 'fc-2', 'fca-3', 'fsk-8', 'fha-3', 'fsk-10', 'fey-2', 'fcat-1', 'fi-4'],
  },
  {
    id: 'tm-239',
    name: 'メリダ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1GW_qZVm8_lOrIAIE-Qrbgdbp4XCrd2Uj',
    features: ['fha-2', 'fse-1', 'fey-1', 'fg-2', 'fch-1', 'fc-9', 'fi-5', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-240',
    name: 'エスメラルダ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1N0sa2AjlJ7sTZJGYUacdZYgHJVsj_Jhh',
    features: ['fsk-6', 'fha-2', 'fey-1', 'fc-7', 'fg-2', 'fc-2', 'fea-1', 'fsk-1', 'fey-2'],
  },
  {
    id: 'tm-241',
    name: 'トップハットジーニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1RUk3vEv_uwnK4h9W-c9IMdCkOUhO1Zud',
    features: ['fca-1', 'fg-1', 'fey-1', 'fca-4', 'fea-2', 'fch-2', 'fc-4', 'fsp-1', 'fi-9'],
  },
  {
    id: 'tm-242',
    name: '魔人ジャファー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1-MRYtu4Y2eBhUrqZd-XxX0tcREfmxE1w',
    features: ['fc-6', 'fg-1', 'fey-1', 'fch-1', 'fi-5', 'fcat-3', 'fea-2', 'fch-2', 'fsk-5', 'fha-3', 'fi-4'],
  },
  {
    id: 'tm-243',
    name: 'アリ王子',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1k5udBnTJrn-nQFz87V8tFAmzZVxcne7i',
    features: ['fi-1', 'fi-7', 'fsk-17', 'fg-1', 'fey-1', 'fca-4', 'fc-1', 'fsk-8', 'fcat-2'],
  },
  {
    id: 'tm-244',
    name: 'ソフィア',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Lyg7Q8WCmbJcfKCJxs8vE0Sa2gP2-F2N',
    features: ['fha-2', 'fca-2', 'fey-1', 'fc-7', 'fg-2', 'fch-1', 'fc-9', 'fi-8', 'fsk-9', 'fea-1', 'fsk-10', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-245',
    name: 'ユーモラスドロッセル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1R1meEjYyhjrsUW-PCUse7fBolatnwXH-',
    features: ['fh-1', 'fg-2', 'fsk-13', 'fsk-11', 'fea-1', 'fc-1', 'fi-3', 'fha-1', 'fsk-9'],
  },
  {
    id: 'tm-246',
    name: '怖がらせ屋サリー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=14uQsTYuFHk_KfNzDBae8Vne2gnmkk9oL',
    features: ['fse-1', 'fg-1', 'fey-1', 'fn-1', 'fi-8', 'fmo-1', 'fsp-2', 'fc-4'],
  },
  {
    id: 'tm-247',
    name: 'ハッピーマイク',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1O9iH8J2QxL1JO021mgOtm1uNZxQvc26I',
    features: ['fse-1', 'fc-5', 'fg-1', 'fmo-1', 'fi-5', 'fsp-2', 'fey-3', 'fsk-4', 'fsk-9'],
  },
  {
    id: 'tm-248',
    name: 'ミスターインクレディブル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1tBYxQiO9bdFiGDe6QTExNggn2IIkYhAz',
    features: ['fse-1', 'fi-7', 'fha-2', 'fg-1', 'fc-3', 'fc-9', 'fi-5', 'fea-1', 'fey-3', 'fsk-3', 'fh-2'],
  },
  {
    id: 'tm-249',
    name: 'ミセスインクレディブル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1pE_effB-MVsF3ZcsAbcrrj1BH1LA0Tcv',
    features: ['fse-1', 'fi-7', 'fha-2', 'fc-7', 'fg-2', 'fc-9', 'fi-5', 'fea-1', 'fey-3', 'fh-2', 'fsk-16'],
  },
  {
    id: 'tm-250',
    name: 'ジャックジャック',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1qov3e0vm8-ieGZMG0W6TrEFtk5ZZhfJG',
    features: ['fse-1', 'fi-7', 'fha-2', 'fg-1', 'fch-1', 'fc-9', 'fea-1', 'fey-3', 'fi-4'],
  },
  {
    id: 'tm-251',
    name: 'あばれんぼスティッチ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=12mBz8sJ8bHdyTitOhuI_l2-JWsTfa8R6',
    features: ['fha-2', 'fi-1', 'fg-1', 'fi-8', 'fmo-1', 'fea-2', 'fsp-2', 'fc-4', 'fsp-1'],
  },
  {
    id: 'tm-252',
    name: 'ジャンバ博士',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1oBD1q0jTZlHByTozFYofTOu4T5VFF8uE',
    features: ['fha-2', 'fg-1', 'fea-3', 'fi-3', 'fsk-23', 'fey-3', 'fc-8', 'fha-4', 'fi-4'],
  },
  {
    id: 'tm-253',
    name: 'プリークリー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1FL3zxcQVIJ8zcoTr-M8WbYyBF-qaRRAu',
    features: ['fi-7', 'fg-1', 'fc-5', 'fmo-1', 'fey-3', 'fsp-2', 'fsk-10'],
  },
  {
    id: 'tm-254',
    name: 'カイリ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1YjVHYwMk5k7v3fYZxPAXTwoCtQRKftat',
    features: ['fha-2', 'fc-6', 'fey-1', 'fg-2', 'fch-1', 'fsk-9', 'fey-2', 'fh-3'],
  },
  {
    id: 'tm-255',
    name: 'アクア',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1BK4zPTp3Mxe7SQ8ibcgTjzvBCYzZy_Mo',
    features: ['fi-1', 'fha-2', 'fey-1', 'fg-2', 'fc-4', 'fh-2', 'fey-2'],
  },
  {
    id: 'tm-256',
    name: 'いたずらジャック',
    imgUrl: 'http://drive.google.com/uc?export=view&id=15aaqvW8flZa2z2d-s-wmV1e_nVGTafNV',
    features: ['fn-2', 'fh-1', 'fg-1', 'fsk-7', 'fi-8', 'fmo-1', 'fi-5', 'fc-1', 'fcat-4', 'fsk-15', 'fsp-1', 'fi-4'],
  },
  {
    id: 'tm-257',
    name: 'ロック',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1r-HqYPRApE6DC08GLT6H1tLLCrXnLXvM',
    features: ['fha-2', 'fc-6', 'fh-1', 'fg-1', 'fey-1', 'fn-1', 'fmo-1', 'fcat-3', 'fea-1', 'fc-1', 'fey-3', 'fsk-9'],
  },
  {
    id: 'tm-258',
    name: 'ヴァンパイアテディ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1WSuBQrQDZ3160lRBjGfBbQZszgFwuxgz',
    features: ['fn-2', 'fh-1', 'fg-1', 'fmo-1', 'fc-2', 'fea-1', 'fc-1', 'fey-3', 'fsk-15', 'fsk-4', 'fi-9'],
  },
  {
    id: 'tm-259',
    name: 'おやすみプー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1usgf6PXo2r7aOlImN5GAIB6ivGMuR_tD',
    features: ['fi-7', 'fg-1', 'fey-1', 'fca-4', 'fc-3', 'fn-1', 'fmo-1', 'fi-6', 'fea-1', 'fc-1', 'fsk-3', 'fsk-32', 'fsp-1', 'fh-3'],
  },
  {
    id: 'tm-260',
    name: 'ゴーファー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=17ikWrhTUTQeLuRLTEnu02WWwos4ReGEu',
    features: ['fn-2', 'fha-2', 'fg-1', 'fey-1', 'fn-1', 'fmo-1', 'fc-2', 'fea-2', 'fch-2', 'fea-4'],
  },
  {
    id: 'tm-261',
    name: 'アニバーサリーミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1jFVF67YocldImH9o4vQTB0ezjjjcgeuV',
    features: ['fn-2', 'fca-1', 'fi-1', 'fh-1', 'fg-1', 'fca-4', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fc-1', 'fsk-8', 'fsp-1', 'fsk-9', 'fsk-18'],
  },
  {
    id: 'tm-262',
    name: 'クラシックミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1bY25JRRWZNUD14HASrK6Kd-0qzC88Omg',
    features: ['fn-2', 'fsk-7', 'fg-1', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fc-1', 'fey-3', 'fh-2'],
  },
  {
    id: 'tm-263',
    name: '豆の木ミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1BL0NKnANuxhtw-3cwSTYr_mR1zVXverX',
    features: ['fn-2', 'fh-1', 'fg-1', 'fca-4', 'fmo-1', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fsk-11', 'fsp-1'],
  },
  {
    id: 'tm-264',
    name: 'フィガロ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Eb3f4OZadONpMPok7M5JvFlhlDNEo902',
    features: ['fn-2', 'fha-2', 'fh-1', 'fg-1', 'fn-1', 'fc-2', 'fea-2', 'fch-2', 'fc-1', 'fsk-4', 'fea-4', 'fty-2'],
  },
  {
    id: 'tm-265',
    name: 'クレオ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1A6pAk57pA_8oFkhqEkRHa1QpxpunTVKB',
    features: ['fg-2', 'fc-3', 'fch-1', 'fmo-1', 'fsp-4', 'fey-2'],
  },
  {
    id: 'tm-266',
    name: 'ラルフ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=11dCCQ4OEuLpAFE7GzXTKbRFeIQjuqOWW',
    features: ['fha-2', 'fg-1', 'fey-1', 'fc-7', 'fc-9', 'fsk-5', 'fn-3'],
  },
  {
    id: 'tm-267',
    name: 'ヴァネロペ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1sY-vjPRk-jFC8WCAHEpd8BY701uK8SX2',
    features: ['fha-2', 'fca-1', 'fsp-1', 'fey-1', 'fg-2', 'fch-1', 'fi-8', 'fc-2', 'fsk-23', 'fea-1', 'fn-3', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-268',
    name: '雪だるまチップ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1pYNUAd4mntEnk9JJnVyxaMzO_r6kNGjl',
    features: ['fn-2', 'fh-1', 'fg-1', 'fca-4', 'fn-1', 'fea-2', 'fc-1', 'fsk-9'],
  },
  {
    id: 'tm-269',
    name: '雪だるまデール',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1MuhjWtRdqVAsKgFYou0VYJ4Ii2fMzHHl',
    features: ['fh-1', 'fg-1', 'fca-4', 'fea-2', 'fc-1', 'fn-3', 'fi-3', 'fsk-9'],
  },
  {
    id: 'tm-270',
    name: 'フェリックス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=18pystrnijkGdloEoqN7pFSzh5jKvtEoa',
    features: ['fg-1', 'fey-1', 'fca-4', 'fc-9', 'fea-1', 'fn-3', 'fc-4', 'fsp-1', 'fh-3'],
  },
  {
    id: 'tm-271',
    name: 'プンバァ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1NdhJ0Cu-LiW4-ufnsbLvZaDCcpM4kWJg',
    features: ['fha-2', 'fi-7', 'fg-1', 'fey-1', 'fc-7', 'fn-1', 'fea-2', 'fn-3', 'fsk-3', 'fh-2', 'fsk-9', 'fea-4'],
  },
  {
    id: 'tm-272',
    name: '雪の女王エルサ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1m2g4UwsSDaGh3knBL-ootdGbdza7HCjt',
    features: ['fha-2', 'fsp-1', 'fey-1', 'fg-2', 'fch-1', 'fc-9', 'fea-1', 'fey-3', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-273',
    name: '邪悪な妖精マレフィセント',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1_Rs6ajNw5HRoiLfeBtwExr-lX2U12x3Y',
    features: ['fh-1', 'fey-1', 'fca-4', 'fg-2', 'fi-5', 'fc-2', 'fcat-3', 'fc-1', 'fsp-2', 'fey-3', 'fsk-19', 'fsp-1', 'fey-2', 'fi-4'],
  },
  {
    id: 'tm-274',
    name: '王様',
    imgUrl: 'http://drive.google.com/uc?export=view&id=14_fj7Qaz1ADP9GnlgrLMUHB5iXgaWx_c',
    features: ['fn-2', 'fg-1', 'fsk-31', 'fca-4', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fh-2'],
  },
  {
    id: 'tm-275',
    name: 'ソラKH3ver.',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1hKHMzOfBeTeJFtSMnKXUYjzMc-4oSPQo',
    features: ['fha-2', 'fsk-6', 'fca-2', 'fg-1', 'fey-1', 'fc-7', 'fi-8', 'fsk-3', 'fsp-1', 'fsk-9', 'fsk-4'],
  },
  {
    id: 'tm-276',
    name: 'ゼムナス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Wj4cGHho3_lOznqwriJO86OsPwGV1MJd',
    features: ['fha-2', 'fg-1', 'fey-1', 'fc-7', 'fcat-3', 'fea-1', 'fsk-3', 'fh-2', 'fha-1'],
  },
  {
    id: 'tm-277',
    name: 'アンセム',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1EPIqGVxQQjz2rwL7cUDokZamxL3NVkXS',
    features: ['fha-2', 'fi-1', 'fh-1', 'fg-1', 'fey-1', 'fc-7', 'fcat-3', 'fsk-5', 'fea-1', 'fha-1', 'fsp-1'],
  },
  {
    id: 'tm-278',
    name: 'ビアンカ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1-h80hqXJkQ3xCY4eC9lpwueFyKA-vdLK',
    features: ['fi-2', 'fca-1', 'fh-1', 'fey-1', 'fca-4', 'fch-1', 'fg-2', 'fn-1', 'fi-5', 'fea-2', 'fea-1', 'fc-1', 'fsk-11', 'fsk-8', 'fc-8', 'fsk-10', 'fey-2', 'fea-4'],
  },
  {
    id: 'tm-279',
    name: 'カメラダンボ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1X2xuLDefJkK7Ayg6fNrC-6KlbTLYNvcV',
    features: ['fg-1', 'fca-4', 'fch-1', 'fea-3', 'fsk-3', 'fc-4', 'fi-3', 'fea-4'],
  },
  {
    id: 'tm-280',
    name: 'ドクターファシリエ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1NDVzOnV0ktg_6niDFxMdiu05qomLuX3n',
    features: ['fsk-28', 'fg-1', 'fey-1', 'fca-4', 'fc-7', 'fmo-1', 'fcat-3', 'fc-2', 'fea-2', 'fch-2', 'fsk-30', 'fi-3'],
  },
  {
    id: 'tm-281',
    name: 'ホーンドキング',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1EBILgpEYu-dWqZjEpIaxKCFQipHOai4h',
    features: ['fn-2', 'fc-6', 'fsk-7', 'fc-5', 'fg-1', 'fca-4', 'fcat-3', 'fsp-2', 'fsp-1'],
  },
  {
    id: 'tm-282',
    name: 'パルパティーン皇帝',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1D4egVlmWLk7iui7hB2xkT7Giz8BI9X6U',
    features: ['fi-7', 'fh-1', 'fg-1', 'fca-4', 'fi-8', 'fcat-3', 'fc-2', 'fsk-23', 'fc-1', 'fi-3'],
  },
  {
    id: 'tm-283',
    name: 'ダースモール',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1k-xEilis7RtAyB9wIRaIFTNKNsKmDJcp',
    features: ['fn-2', 'fsk-6', 'fc-6', 'fg-1', 'fca-4', 'fch-1', 'fcat-3', 'fc-2', 'fi-5', 'fsp-2', 'fh-2', 'fi-3'],
  },
  {
    id: 'tm-284',
    name: 'ソー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=13Xd0WrdI812dXsMyQgn_6YPeU9AN2JeH',
    features: ['fi-2', 'fha-2', 'fg-1', 'fey-1', 'fca-4', 'fc-3', 'fi-8', 'fc-1', 'fcat-2', 'fi-3', 'fi-9'],
  },
  {
    id: 'tm-285',
    name: 'トニースターク',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1wQRjlb2dpkE6qAaUQuQG1ZdC37L9YAYL',
    features: ['fi-1', 'fc-6', 'fg-1', 'fey-1', 'fca-4', 'fi-8', 'fsk-5', 'fch-2', 'fi-9'],
  },
  {
    id: 'tm-286',
    name: 'ハルク',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1q1aDMm-LV68XjINPjK4Li-ut8reOHgH1',
    features: ['fi-2', 'fha-2', 'fc-5', 'fg-1', 'fey-1', 'fsk-5', 'fea-1'],
  },
  {
    id: 'tm-287',
    name: '乗馬ソフィア',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1dMDO7dxYj4vWEZlN1YLwaE6l54Fm0i2z',
    features: ['fha-2', 'fca-2', 'fey-1', 'fc-7', 'fg-2', 'fch-1', 'fc-9', 'fi-8', 'fsk-5', 'fea-1', 'fsp-1', 'fsk-9', 'fey-2', 'fcat-1', 'fi-4'],
  },
  {
    id: 'tm-288',
    name: 'エレナ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1YGRBq3r6lhMskgq4pZUQQBqICoRHV30p',
    features: ['fha-2', 'fey-1', 'fc-7', 'fg-2', 'fch-1', 'fsk-18', 'fc-2', 'fca-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-289',
    name: 'レインボーティンク',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1S7RkfEHHTukzCk9L6UcS1GURWCKhN395',
    features: ['fey-1', 'fg-2', 'fc-3', 'fch-1', 'fea-2', 'fsk-3', 'fha-3', 'fi-9'],
  },
  {
    id: 'tm-290',
    name: 'ペリウィンクル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1deE_BsDxMuPc_j6FNj_KMRpmNrkOWqB_',
    features: ['fha-2', 'fi-7', 'fey-1', 'fg-2', 'fch-1', 'fea-2', 'fsk-11', 'fc-1', 'fha-1', 'fey-2'],
  },
  {
    id: 'tm-291',
    name: 'シルバーミスト',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1MXGlUtVk4RegJnEl5n1o_N4twXrlXpB4',
    features: ['fha-2', 'fey-1', 'fg-2', 'fch-1', 'fi-8', 'fea-2', 'fsk-3', 'fc-4', 'fey-2'],
  },
  {
    id: 'tm-292',
    name: 'ロゼッタ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1JUcopn49nk8_M1qawP9sw40Mvb5o0Rok',
    features: ['fey-1', 'fc-7', 'fg-2', 'fch-1', 'fea-2', 'fsk-5', 'fca-3', 'fey-2'],
  },
  {
    id: 'tm-293',
    name: 'ロマンスジャスミン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1cVgMZBEFaJRZ8D4bEAi1m6aAYRpNEwht',
    features: ['fca-2', 'fey-1', 'fc-7', 'fg-2', 'fc-2', 'fea-1', 'fsk-8', 'fha-3', 'fey-2', 'fcat-1', 'fi-4'],
  },
  {
    id: 'tm-294',
    name: 'ボーピープ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1yDXVLyFwHz4CvRFR1_h5tF3iiSGf9L4g',
    features: ['fi-2', 'fca-1', 'fse-1', 'fi-7', 'fey-1', 'fg-2', 'fch-1', 'fc-3', 'fea-1', 'fey-3', 'fha-3'],
  },
  {
    id: 'tm-295',
    name: 'フォーキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1I9KEBBWNxTgENTcDTFQNQZvjagXp4wqV',
    features: ['fse-1', 'fg-1', 'fey-1', 'fch-1', 'fmo-1', 'fc-1', 'fey-3'],
  },
  {
    id: 'tm-296',
    name: 'バニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1F5WamF5kUQk2kjfaEJmTLBdJF4StpjS-',
    features: ['fi-2', 'fse-1', 'fg-1', 'fmo-1', 'fea-2', 'fch-2', 'fey-3', 'fc-4', 'fty-3', 'fsk-9', 'fsk-18'],
  },
  {
    id: 'tm-297',
    name: 'パステルアリエル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1toO8LdxTdA7w7IOZC3XhfucCodak8JHA',
    features: ['fi-1', 'fi-7', 'fsk-22', 'fha-2', 'fg-2', 'fch-1', 'fsp-4', 'fea-1', 'fca-3', 'fsp-3', 'fsk-9', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-298',
    name: 'パステルフランダー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1bhTbx5zIJ61B_Ek1o9HgMQKfaRM8IEj2',
    features: ['fi-7', 'fg-1', 'fey-1', 'fch-1', 'fc-3', 'fmo-1', 'fsp-4', 'fsk-3', 'fsp-3'],
  },
  {
    id: 'tm-299',
    name: 'フレディマーキュリー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1gJdyDijl-W9UKVXJTslwW2s-6DYcmQjB',
    features: ['fg-1', 'fey-1', 'fi-5', 'fc-2', 'fea-1', 'fch-2', 'fey-3'],
  },
  {
    id: 'tm-300',
    name: 'ブライアンメイ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=19NdSA3NC4NzXU5M5-cRPEY0E1dYCijCh',
    features: ['fi-2', 'fsk-6', 'fg-1', 'fey-1', 'fc-7', 'fi-5', 'fey-3'],
  },
  {
    id: 'tm-301',
    name: 'ロジャーテイラー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1q7BBhwDM4XCnut6M4Uq33mBcmURXHKcv',
    features: ['fha-2', 'fg-1', 'fey-1', 'fsk-9', 'fc-3', 'fsk-11', 'fey-3', 'fi-9'],
  },
  {
    id: 'tm-302',
    name: 'ハクナマタタシンバ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1wGsITDXEjmDCqjtzzNS-qcs1_0riEatf',
    features: ['fha-2', 'fty-2', 'fg-1', 'fey-1', 'fc-7', 'fi-8', 'fn-1', 'fea-1', 'fch-2', 'fcat-2', 'fsk-4', 'fsk-9', 'fh-3'],
  },
  {
    id: 'tm-303',
    name: 'ヴェントゥス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1d1XsCW9ItIKZVYa8OVT3IHLxYA4PfBO2',
    features: ['fha-2', 'fg-1', 'fey-1', 'fc-3', 'fea-1', 'fsk-1', 'fsp-1', 'fsk-4'],
  },
  {
    id: 'tm-304',
    name: 'テラ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1-yDdmdKPNpa8GFNU_HrYS2uqyMO-esIB',
    features: ['fha-2', 'fg-1', 'fey-1', 'fc-7', 'fh-2', 'fi-9'],
  },
  {
    id: 'tm-305',
    name: 'チリシィ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1_rCoKrmhMn7dKaq3KbZXWkZKwxlIzX83',
    features: ['fh-1', 'fn-1', 'fea-3', 'fc-2', 'fn-3', 'fh-2', 'fsp-1', 'fsk-18'],
  },
  {
    id: 'tm-306',
    name: 'ハニーレモン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=19wZy9pY-nAmHc0ZLxFBn0eHGK1V5PCKl',
    features: ['fca-4', 'fg-2', 'fey-2', 'fey-1'],
  },
  {
    id: 'tm-307',
    name: 'フレッド',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1mfjzvoenAtJjnf5vYl9yc9KGQd62_pVO',
    features: ['fg-1', 'fey-1', 'fca-4', 'fmo-1', 'fsp-2', 'fey-3', 'fc-4'],
  },
  {
    id: 'tm-308',
    name: '勇者ミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1rqfIg_nn9dqAfejplnopBbrOUYqlQTi_',
    features: ['fn-2', 'fi-2', 'fha-2', 'fh-1', 'fg-1', 'fey-1', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fsk-5', 'fsk-3', 'fsk-11', 'fsp-1'],
  },
  {
    id: 'tm-309',
    name: '勇者ドナルド',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1tO1r1PigsVXddr22ZqmvdtHgpVbVhvuV',
    features: ['fi-2', 'fha-2', 'fh-1', 'fg-1', 'fey-1', 'fca-4', 'fch-1', 'fmo-1', 'fsp-5', 'fc-1', 'fc-4', 'fi-3', 'fsp-1', 'f-3'],
  },
  {
    id: 'tm-310',
    name: '勇者グーフィー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1PjBf18_jpJSFt4dkJTvka09T68rc9M5I',
    features: ['fi-2', 'fn-2', 'fh-1', 'fg-1', 'fc-5', 'fca-4', 'fea-3', 'fey-3', 'fty-1', 'fsp-1', 'fsk-9', 'fsk-18'],
  },
  {
    id: 'tm-311',
    name: 'パックマン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=12N5LBtyhwxknEFIEQ0bek_dPLOy4KTWo',
    features: ['fi-7', 'fg-1', 'fc-3', 'fmo-1', 'fh-3'],
  },
  {
    id: 'tm-312',
    name: 'ブリンキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1XZ3MNo_m9uQ9ofwN4eGtrjdta_zkPrv2',
    features: ['fi-2', 'fc-6', 'fg-1', 'fch-1', 'fey-3'],
  },
  {
    id: 'tm-313',
    name: 'エンチャンテッドオーロラ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Y9luK5KnkXKBTKOtNl2FP67LMKnWhems',
    features: ['fi-1', 'fca-2', 'fey-1', 'fg-2', 'fc-3', 'fch-1', 'fey-3', 'fsp-1', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-314',
    name: 'エンチャンテッドシンデレラ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1gHG0tkseJ8iFh9-ebW7H8AIS3mo1eGep',
    features: ['fsp-1', 'fey-1', 'fg-2', 'fc-3', 'fch-1', 'fi-8', 'fea-1', 'fsk-3', 'fey-3', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-315',
    name: 'ダンシングジーニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1XIEo3lh7h19-OZT-Q75EyfSaCRSk33Dv',
    features: ['fg-1', 'fey-1', 'fsk-13', 'fea-2', 'fch-2', 'fey-3', 'fc-4', 'fi-3', 'fha-3', 'fsk-9'],
  },
  {
    id: 'tm-316',
    name: 'ほっこりミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1NMgzl7cKWvSQ7PjVdb3LZhcYpmOSrYaF',
    features: ['fn-2', 'fh-1', 'fg-1', 'fey-1', 'fch-1', 'fmo-1', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fc-1', 'fsk-8', 'fsk-10'],
  },
  {
    id: 'tm-317',
    name: 'ゆるっとドナルド',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1tQHiskrMcrtmquxMP5QqaxWIOsOrX69a',
    features: ['fca-1', 'fh-1', 'fg-1', 'fca-4', 'fch-1', 'fmo-1', 'fsp-5', 'fc-1', 'fi-3', 'f-3'],
  },
  {
    id: 'tm-318',
    name: 'アドベンチャーエルサ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1r-DQndsTNEtVtAqX-c3B5sd_8qhs9KRj',
    features: ['fha-2', 'fi-1', 'fey-1', 'fg-2', 'fch-1', 'fea-1', 'fey-3', 'fsp-1', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-319',
    name: 'アドベンチャーアナ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1vaWZhdeCYTgnMXPHnMHv9IjsFcwhw3dW',
    features: ['fi-1', 'fha-2', 'fey-1', 'fc-7', 'fg-2', 'fea-1', 'fey-3', 'fsk-8', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-320',
    name: 'ジェダイトレーニングレイ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1uRBTZ9WNzW0CZqObh9l2OQa3y0H99Dvu',
    features: ['fha-2', 'fey-1', 'fc-7', 'fg-2', 'fsk-5', 'fea-1', 'fsp-1', 'fha-3', 'fey-2', 'fi-4'],
  },
  {
    id: 'tm-321',
    name: '最高指導者カイロレン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1sm-0sNfRclcwbo7Ca8eyeDAzXnFWQtyV',
    features: ['fn-2', 'fg-1', 'fca-4', 'fi-8', 'fcat-3', 'fc-2', 'fh-2', 'fsk-18'],
  },
  {
    id: 'tm-322',
    name: 'だるまミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1vQddDs4JVVY3e5KqBBrovV5hWIqu-0gL',
    features: ['fn-2', 'fc-6', 'fg-1', 'fch-1', 'fsk-13', 'fi-5', 'fc-2', 'f-1', 'fea-1', 'fi-3'],
  },
  {
    id: 'tm-323',
    name: 'フレディ75',
    imgUrl: 'http://drive.google.com/uc?export=view&id=12UAgoBKD6QpuxfpGeHVne_3xEQP5tuJJ',
    features: ['fha-2', 'fg-1', 'fey-1', 'fi-5', 'fey-3', 'fsk-9'],
  },
  {
    id: 'tm-324',
    name: 'ジョンディーコン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=141V-UezqwvNOEaMqM9QUqqA7BCgh9cjJ',
    features: ['fha-2', 'fsk-7', 'fg-1', 'fey-1', 'fc-7', 'fea-1', 'fey-3', 'fi-3', 'fsk-9', 'fi-4'],
  },
  {
    id: 'tm-325',
    name: 'アリエル(チャーム)',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1so46wlH6NAXes3E-gAzoPlyC-Ei9DjyV',
    features: ['fha-2', 'fi-1', 'fc-6', 'fey-1', 'fg-2', 'fch-1', 'fsp-4', 'fsk-11', 'fea-1', 'fsp-3', 'fsk-21', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-326',
    name: 'ベル(チャーム)',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1pPhS7X5PCEaWn0S90kKVEZQwGyB74vaU',
    features: ['fi-2', 'fha-2', 'fca-1', 'fey-1', 'fc-7', 'fg-2', 'fch-1', 'fsk-4', 'fea-1', 'fsk-1', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-327',
    name: 'ラプンツェル(チャーム)',
    imgUrl: 'http://drive.google.com/uc?export=view&id=13V6gOiIfjHfTGE6qHNWqCbIW41I1kO4h',
    features: ['fey-1', 'fg-2', 'fch-1', 'fc-3', 'fea-1', 'fca-3', 'fsk-3', 'fsk-1', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-328',
    name: 'ジャスミン(チャーム)',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1O9_clMZhcYwlmjjaE8dWbON1z9ZM7cPd',
    features: ['fha-2', 'fca-2', 'fsk-7', 'fsp-1', 'fey-1', 'fg-2', 'fch-1', 'fc-4', 'fsk-1', 'fha-3', 'fey-2', 'fcat-1', 'fi-4'],
  },
  {
    id: 'tm-329',
    name: 'MUランドール',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Z2oaS9kLoR3pPU-rZvPrR3Nvd400ofLI',
    features: ['fse-1', 'fha-2', 'fg-1', 'fmo-1', 'fey-3', 'fc-8', 'fha-4', 'fsk-10'],
  },
  {
    id: 'tm-330',
    name: 'イヴ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1NcQRxVzWeUyolurztlADJV4-9YZ5B_RJ',
    features: ['fse-1', 'fh-1', 'fg-2', 'fc-2', 'fc-1', 'fsk-1', 'fsk-4'],
  },
  {
    id: 'tm-331',
    name: 'バーリー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1TP6Ws0z4Oglda9XbxEe0WBpQcAVLa-w_',
    features: ['fse-1', 'fha-2', 'fg-1', 'fey-1', 'fca-4', 'fch-1', 'fn-1', 'fea-2', 'fch-2', 'fc-4', 'fsk-1', 'fsk-4', 'fea-4'],
  },
  {
    id: 'tm-332',
    name: 'イアン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1wXJ87H53NywY8KLxvTeN12QrQrux4kDZ',
    features: ['fse-1', 'fha-2', 'fg-1', 'fey-1', 'fch-1', 'fn-1', 'fea-2', 'fc-4', 'fea-4'],
  },
  {
    id: 'tm-333',
    name: 'メリーポピンズ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Gt9mNr4g2Hbj4nkWMTc3qP_lrNNATNay',
    features: ['fca-1', 'fi-7', 'fey-1', 'fca-4', 'fg-2', 'fch-1', 'fi-5', 'fc-1', 'fca-3', 'fsk-1', 'fsk-4', 'fsk-9', 'fey-2'],
  },
  {
    id: 'tm-334',
    name: '兵士ムーラン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=10F_nGQeeIseaOTv2FtVnydGT2Mkq9Q85',
    features: ['fha-2', 'fey-1', 'fg-2', 'fch-1', 'fi-5', 'fc-2', 'fey-3', 'fsk-1', 'fsk-4', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-335',
    name: 'ジゼル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1w-WF_O31_HEYXNsej1Uc2GUiMf9bu4N2',
    features: ['fha-2', 'fca-2', 'fsp-1', 'fey-1', 'fc-7', 'fg-2', 'fch-1', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-336',
    name: '白の女王',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1-afndSFRvdQten1eH-xigDU0hK3LTIIb',
    features: ['fey-1', 'fg-2', 'fi-8', 'fi-5', 'fc-1', 'fsk-3', 'fey-3', 'fsk-1', 'fha-1', 'fsk-9', 'fey-2'],
  },
  {
    id: 'tm-337',
    name: 'ワンダーチェシャ猫',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1mEPQhOQhhN5LyAm479Tmkzn56GZvaPkO',
    features: ['fha-2', 'fg-1', 'fn-1', 'fmo-1', 'fea-2', 'fn-3', 'fea-4', 'fty-2'],
  },
  {
    id: 'tm-338',
    name: 'ベンケノービ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1pXiETDOm_3MXnx0yd76tuEt-opqFGS1d',
    features: ['fi-2', 'fsk-7', 'fg-1', 'fey-1', 'fc-7', 'fca-4', 'fch-2', 'fsk-1', 'fha-1'],
  },
  {
    id: 'tm-339',
    name: 'マスタールーク',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1dE3VdmdH1Q-aMxiIks6kcHk4YNnUUAUP',
    features: ['fha-2', 'fsk-7', 'fg-1', 'fey-1', 'fi-8', 'fi-5', 'fch-2', 'fea-1', 'fsk-1', 'fha-1', 'fsp-1'],
  },
  {
    id: 'tm-340',
    name: 'メイスウィンドゥ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1fWEfbKhOp0AD7vVKF6qG_krG8fMGNzll',
    features: ['fg-1', 'fey-1', 'fc-7', 'fi-5', 'fsk-5', 'fea-1', 'fsk-1', 'fsp-1', 'fsk-4'],
  },
  {
    id: 'tm-341',
    name: 'アナキンスカイウォーカー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1WGYNTEn9PW6a2Ftnc33cRGNe8Ug6uOyI',
    features: ['fha-2', 'fi-1', 'fg-1', 'fey-1', 'fc-7', 'fi-8', 'fea-1', 'fh-2', 'fsk-1', 'fsp-1'],
  },
  {
    id: 'tm-342',
    name: 'パドメアミダラ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1j-pFyLKrAoCYAjJF4-xJcnINitKU2f-1',
    features: ['fi-1', 'fi-7', 'fey-1', 'fc-7', 'fg-2', 'fsk-4', 'fea-1', 'fsk-8', 'fsk-1', 'fsp-1', 'fsk-9', 'fey-2'],
  },
  {
    id: 'tm-343',
    name: 'リロイ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1UumtCaNEqyg4UohYIXW-T2W7GXq-fo2r',
    features: ['fha-2', 'fc-6', 'fg-1', 'fch-1', 'fmo-1', 'fcat-3', 'fea-2', 'fsp-2', 'fsk-1'],
  },
  {
    id: 'tm-344',
    name: 'ハムスターヴィール博士',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1n165ZjvzETG72-T72r0uww_ByPuKVqJK',
    features: ['fha-2', 'fh-1', 'fg-1', 'fey-1', 'fn-1', 'fmo-1', 'fcat-3', 'fc-1', 'fn-3', 'fsp-1', 'fea-4'],
  },
  {
    id: 'tm-345',
    name: '忍者ミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1--SOmCBwgWoW1Y6iS79tAN1zecGOdf_R',
    features: ['fn-2', 'fg-1', 'fi-5', 'fc-2', 'fsk-5', 'fea-1', 'f-1', 'fh-2', 'fsk-1'],
  },
  {
    id: 'tm-346',
    name: '着物ミニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1OmqCL18ZDKlNe2ouP6rPGAifxGF7Hq6E',
    features: ['fn-2', 'fca-1', 'fh-1', 'fg-2', 'fch-1', 'fi-5', 'fc-2', 'fsk-11', 'fea-1', 'fsp-1', 'fey-2'],
  },
  {
    id: 'tm-347',
    name: 'エルササラマンダー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1JSA3xGIcow54XYua11knI_7U7-Ee1W6W',
    features: ['fha-2', 'fey-1', 'fch-1', 'fg-2', 'fi-8', 'fmo-1', 'fea-1', 'fey-3', 'fc-4', 'fsk-10', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-348',
    name: 'お祭りドナルド',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1hrRIxLIlypY6CY76GD5q80rxm0EGJKtj',
    features: ['fh-1', 'fg-1', 'fch-1', 'fmo-1', 'fsp-5', 'fc-1', 'fi-3', 'fsp-1', 'f-3'],
  },
  {
    id: 'tm-349',
    name: 'ガイコツミゲル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1v0w8v3BgkgzfeJuGA7Ew2R3y30vxztFE',
    features: ['fn-2', 'fse-1', 'fh-1', 'fg-1', 'fca-4', 'fch-1', 'fi-5', 'fc-2', 'fsk-11', 'fc-1'],
  },
  {
    id: 'tm-350',
    name: 'ラグビーミッキー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1_oH-dMTOpU_fn2KsQWsLlZQo0gJ43Nzy',
    features: ['fn-2', 'fc-6', 'fh-1', 'fg-1', 'fey-1', 'fca-4', 'fi-5', 'fc-2', 'fsk-11', 'fea-1', 'f-1', 'fsk-3', 'fsk-1', 'fsp-1'],
  },
  {
    id: 'tm-351',
    name: '波乗りスティッチ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1FW0LpUH2tgyatKNN-n2gk4iKZtI00HO_',
    features: ['fha-2', 'fg-1', 'fi-8', 'fmo-1', 'fi-6', 'fea-2', 'fc-4', 'fsk-1', 'fsk-4'],
  },
  {
    id: 'tm-352',
    name: 'ホームランプー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1gvzHhHAMjl6-bQz1p4X3-iE1-HRt65Cw',
    features: ['fi-7', 'fg-1', 'fey-1', 'fca-4', 'fc-3', 'fn-1', 'fsk-5', 'fea-1', 'fsk-1', 'fh-3'],
  },
  {
    id: 'tm-353',
    name: '魔女マレフィセント',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1WLinJKjki-kakiM332Cd9ui_VVZ4h5Ag',
    features: ['fey-1', 'fca-4', 'fg-2', 'fi-5', 'fc-2', 'fcat-3', 'fsp-2', 'fc-4', 'fsp-1', 'fey-2'],
  },
  {
    id: 'tm-354',
    name: '死者の国の神ハデス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1O-37KDAezmfji_8eEhsOIRlB6BPVKBmk',
    features: ['fha-2', 'fg-1', 'fey-1', 'fi-8', 'fmo-1', 'fcat-3', 'fea-2', 'fey-3', 'fc-4', 'fsk-1'],
  },
  {
    id: 'tm-355',
    name: 'マイクサリー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1ZN2-RQQS_0WI9tzAqoJxyTV3rykZzWgA',
    features: ['fse-1', 'fc-5', 'fg-1', 'fey-1', 'fn-1', 'fmo-1', 'fi-8', 'fi-5', 'fsk-13', 'fsk-5', 'fsp-2', 'fey-3', 'fc-4', 'fsk-1', 'fsk-9'],
  },
  {
    id: 'tm-356',
    name: 'パイレーツソラ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1YJYsGm_ZAZXbss6V5mLiIXzLeqEx3SKn',
    features: ['fha-2', 'fi-7', 'fca-2', 'fg-1', 'fey-1', 'fc-7', 'fca-4', 'fi-8', 'fsk-5', 'fsk-3', 'fsk-1', 'fsp-1', 'fsk-4'],
  },
  {
    id: 'tm-357',
    name: '少年ゼアノート',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1R7K10UaP3jKwtPASq0_viIlRlJhAbH5V',
    features: ['fha-2', 'fg-1', 'fey-1', 'fc-7', 'fi-8', 'fcat-3', 'fea-1', 'fc-1', 'fsk-1', 'fha-1', 'fsp-1'],
  },
  {
    id: 'tm-358',
    name: 'マスカレードラプンツェル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1hka8WbOvbLyj_w_v_lPylutR8gsAMayj',
    features: ['fey-1', 'fg-2', 'fc-3', 'fch-1', 'fi-5', 'fea-1', 'fca-3', 'fsk-3', 'fsk-30', 'fsk-1', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-359',
    name: 'マスカレードシンデレラ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1oJL6XYm6jAoT1JpyM3ivjSBTCaAfqCqn',
    features: ['fey-1', 'fg-2', 'fch-1', 'fc-3', 'fi-8', 'fi-5', 'fea-1', 'fsk-30', 'fsk-8', 'fsp-1', 'fsk-10', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-360',
    name: 'マスカレードエスメラルダ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1-GWWUv2V8Rp-Vgu36c1bECIuNSvF2RIs',
    features: ['fha-2', 'fca-1', 'fey-1', 'fc-7', 'fg-2', 'fc-3', 'fi-5', 'fc-2', 'fea-1', 'fsk-30', 'fey-2'],
  },
  {
    id: 'tm-361',
    name: 'ジミニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1UMMR8qrjleXcfhS5OEITWK8jueFi2MQ8',
    features: ['fh-1', 'fc-5', 'fg-1', 'fca-4', 'fey-1', 'fsk-5', 'fi-4'],
  },
  {
    id: 'tm-362',
    name: 'マックス',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1-7-VmlqkGLuOUewcs4ht0WemginLRm2B',
    features: ['fn-2', 'fha-2', 'fh-1', 'fg-1', 'fea-3', 'fc-2', 'fi-5', 'fey-3', 'fty-1', 'fsk-4'],
  },
  {
    id: 'tm-363',
    name: 'アーロ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1y9CBfj0Ga0Dh2cGdQ8gj9aJrPo6yWY1M',
    features: ['fse-1', 'fi-1', 'fc-5', 'fg-1', 'fey-3', 'fsk-19', 'fsk-9'],
  },
  {
    id: 'tm-364',
    name: 'スフレ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1HybgDxvPW_y44MNJthq-UjNe8oFMssw9',
    features: ['fha-2', 'fg-1', 'fch-1', 'fi-8', 'fmo-1', 'fsk-13', 'fea-1', 'fn-3', 'fea-4', 'fc-10'],
  },
  {
    id: 'tm-365',
    name: 'うさぎどん',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1z7QFmIaHOiofEU0RHXe2LUqA-9fDffZi',
    features: ['fi-2', 'fha-2', 'fg-1', 'fey-1', 'fc-7', 'fmo-1', 'fea-2', 'fsk-5', 'fn-3', 'fty-3'],
  },
  {
    id: 'tm-366',
    name: 'スクルージ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=10NZpkvQAjkLLMJ0fROn9qfaH2RRN5vF_',
    features: ['fha-2', 'fh-1', 'fg-1', 'fca-4', 'fi-8', 'fmo-1', 'fi-5', 'fsk-5', 'fsp-5', 'fc-1', 'fsp-1'],
  },
  {
    id: 'tm-367',
    name: 'ストームトルーパー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1n7OXcuA4oPobFDntnejkodt7-X3ANyyE',
    features: ['fg-1', 'fca-4', 'fsk-9', 'fi-8', 'fmo-1', 'fcat-3', 'fc-1', 'fh-2', 'fi-9'],
  },
  {
    id: 'tm-368',
    name: 'ピート',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1ur0NAgQqCwfcD4BubrZg1Dn5VFcC6Met',
    features: ['fn-2', 'fha-2', 'fi-7', 'fh-1', 'fg-1', 'fcat-3', 'fc-2', 'fea-2', 'fey-3', 'fsk-3', 'fty-2'],
  },
  {
    id: 'tm-369',
    name: 'ほねほねプルート',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1EqqCXVHyYmnAV7A_6Ld9Aj31VHawVozj',
    features: ['fi-2', 'fn-2', 'fca-1', 'fi-7', 'fg-1', 'fca-4', 'fch-1', 'fc-3', 'fea-3', 'fc-1', 'fey-3', 'fcat-4', 'fsk-15', 'fty-1', 'fsk-4', 'fh-3'],
  },
  {
    id: 'tm-370',
    name: 'ラビット',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1UXeqOp_63jAUGBz-9pU3kQle9f09Y5Zp',
    features: ['fha-2', 'fg-1', 'fey-1', 'fc-3', 'fn-1', 'fch-2', 'fn-3', 'fty-3', 'fea-4', 'fh-3'],
  },
  {
    id: 'tm-371',
    name: 'リロ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=16mhKiDJ46RkdBKbeM6_fO6TJB5GhnH-U',
    features: ['fey-1', 'fc-7', 'fg-2', 'fch-1', 'fc-9', 'fc-2', 'fea-1', 'fca-3'],
  },
  {
    id: 'tm-372',
    name: 'サンタジャック',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1UkdmnDkSxAvN5LJivE65boMs3RdLsJmt',
    features: ['fn-2', 'fh-1', 'fg-1', 'fca-4', 'fi-8', 'fmo-1', 'fch-2', 'fc-1', 'fcat-4', 'fsk-20', 'fi-4'],
  },
  {
    id: 'tm-373',
    name: 'スカットル',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1USAc1z8Flr3-qpEjyBbSlumg5rO7LLuG',
    features: ['fha-2', 'fh-1', 'fg-1', 'fey-1', 'fch-1', 'fi-8', 'fmo-1', 'fsp-5', 'fc-1', 'fsp-3', 'fsk-4', 'fsk-9'],
  },
  {
    id: 'tm-374',
    name: 'アブー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1zdj-rLV8Fkf8s1zR0NdI8BGTKugjRwny',
    features: ['fi-1', 'fha-2', 'fg-1', 'fey-1', 'fc-7', 'fca-4', 'fc-3', 'fn-1', 'fea-1'],
  },
  {
    id: 'tm-375',
    name: 'C-3PO',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1xilt8ZqrAmo3Z3rCH8-1q6SrQPyIANoD',
    features: ['fg-1', 'fc-3', 'fmo-1', 'fsk-4', 'fsk-9', 'fh-3'],
  },
  {
    id: 'tm-376',
    name: 'レイア姫',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1ifjRH1mczHgqwcWs2CUkVU9JMKDsEogQ',
    features: ['fi-7', 'fey-1', 'fc-7', 'fg-2', 'fch-1', 'fc-9', 'fsk-18', 'fc-2', 'fha-3', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-377',
    name: 'ザズー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1OXBTI4Bi_XmIs0t9R-QenAWHd4psZCCE',
    features: ['fha-2', 'fg-1', 'fey-1', 'fmo-1', 'fsp-5', 'fc-4', 'fha-4', 'fsk-4'],
  },
  {
    id: 'tm-378',
    name: 'プリンスチャーミング',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1g17PDL-x8zNyhsuOala1eLx_Nnl4Kpep',
    features: ['fi-7', 'fh-1', 'fg-1', 'fey-1', 'fsp-1', 'fc-9', 'fc-2', 'fea-1', 'fsk-8', 'fcat-2', 'fsk-4'],
  },
  {
    id: 'tm-379',
    name: '3月うさぎ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1LxAacRqhCP4bHAym-qAqwk2S_dk5Z9XF',
    features: ['fha-2', 'fg-1', 'fey-1', 'fc-7', 'fc-3', 'fn-1', 'fmo-1', 'fi-8', 'fi-5', 'fea-2', 'fch-2', 'fsk-5', 'fn-3', 'fty-3', 'fea-4', 'fh-3'],
  },
  {
    id: 'tm-380',
    name: 'ジョーカーグーフィー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1qJHTa1W9-w00CZxCXycnBDi4a4Iyh5PY',
    features: ['fn-2', 'fsk-7', 'fg-1', 'fsk-14', 'fca-4', 'fea-3', 'fc-2', 'fey-3', 'fcat-4', 'fty-1', 'fh-2', 'fi-4'],
  },
  {
    id: 'tm-381',
    name: 'デストルーパー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1aM-aJi4OFK00DsnrGFTISCJRRm1iCtjG',
    features: ['fn-2', 'fg-1', 'fca-4', 'fcat-3', 'fc-2', 'fh-2', 'fi-3', 'fi-9'],
  },
  {
    id: 'tm-382',
    name: 'ミニー姫',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1YblxYQGityTp_LJ80Wd0vNNImOYFJxpP',
    features: ['fn-2', 'fi-7', 'fca-2', 'fh-1', 'fg-2', 'fch-1', 'f-2', 'fi-5', 'fc-2', 'fea-1', 'fsk-8', 'fsp-1', 'fsk-10', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-383',
    name: 'メグ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1swyHQO-RLWVzNoqnE5SOE7Yy5ibsNUwt',
    features: ['fha-2', 'fc-6', 'fsk-17', 'fey-1', 'fg-2', 'fc-9', 'fi-5', 'fea-1', 'fsk-8', 'fha-3', 'fsk-10', 'fey-2'],
  },
  {
    id: 'tm-384',
    name: 'ポット夫人',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1VSjTwmEFhjdowPwggcLU46YJcUJ4lCQL',
    features: ['fi-7', 'fey-1', 'fg-2', 'fch-1', 'fi-5', 'fc-1', 'fsk-10', 'fey-2'],
  },
  {
    id: 'tm-385',
    name: 'バットハットミニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1Jbi8GrB7KHkcOrYmvfE-vsQo_nCSVsHB',
    features: ['fi-2', 'fn-2', 'fca-1', 'fh-1', 'fsk-14', 'fca-4', 'fg-2', 'fch-1', 'f-2', 'fi-5', 'fc-2', 'fea-1', 'fcat-4', 'fsp-1', 'fey-2'],
  },
  {
    id: 'tm-386',
    name: 'カバレロドナルド',
    imgUrl: 'http://drive.google.com/uc?export=view&id=18_NQ7vIwbRqs_QLW9YzJyWJKUQ-86Qn3',
    features: ['fha-2', 'fca-1', 'fh-1', 'fg-1', 'fca-4', 'fch-1', 'fmo-1', 'fsp-5', 'fc-1', 'f-3', 'fi-3', 'fsk-9', 'fsk-18'],
  },
  {
    id: 'tm-387',
    name: 'アニバーサリーミニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1iizWWCll0PfDBbn6NdrU3qSig8h8mwbd',
    features: ['fn-2', 'fi-1', 'fh-1', 'fg-2', 'f-2', 'fi-5', 'fc-2', 'fea-1', 'fc-1', 'fca-3', 'fsk-8', 'fsk-10', 'fsp-1', 'fsk-9', 'fey-2', 'fsk-16'],
  },
  {
    id: 'tm-388',
    name: 'シャドウ',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1RtTVlDUMMEI7YB2hnrPvG1eMgQ7lPDZj',
    features: ['fn-2', 'fi-8', 'fcat-3', 'fc-2', 'fsp-2', 'fh-2'],
  },
  {
    id: 'tm-389',
    name: 'だるまミニー',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1rzsX7bYUbueyJF9cuuYeLmAviYaTeYUd',
    features: ['fn-2', 'fca-1', 'fg-2', 'fch-1', 'f-2', 'fi-5', 'fc-2', 'fsk-13', 'fea-1', 'fc-1', 'fi-3', 'fey-2'],
  },
  {
    id: 'tm-390',
    name: 'フィン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=15SQQNejA4aU1kn6WmMNQXRkhOFrIcfrL',
    features: ['fg-1', 'fey-1', 'fc-7', 'fc-2', 'fea-1', 'fsk-1', 'fsp-1'],
  },
  {
    id: 'tm-391',
    name: 'リトルグリーンメン',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1oeGgpXWByGByQXwF8nW9eR9Bvlp7bpBk',
    features: ['fse-1', 'fi-1', 'fc-5', 'fsp-6', 'fmo-1', 'fea-2', 'fsp-2', 'fey-3'],
  },
  {
    id: 'tm-392',
    name: 'オズワルド',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1VpgEOuHqky2YlQ_z_G0Pxtwbf6NDARcu',
    features: ['fn-2', 'fg-1', 'fea-3', 'fc-2', 'fc-1', 'fh-2', 'fty-3'],
  },
  {
    id: 'tm-393',
    name: 'コグスワース',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1a5oQkU-kpZ8kFCfieNlt8BZZFjRP21tY',
    features: ['fg-1', 'fey-1', 'fc-7', 'fch-2', 'fsk-9', 'fh-3'],
  },
  {
    id: 'tm-394',
    name: 'ガジェット',
    imgUrl: 'http://drive.google.com/uc?export=view&id=1BkCYXNB4288Q0yNS2UeeGlxEWESqRMll',
    features: ['fey-1', 'fc-7', 'fg-2', 'fch-1', 'fn-1', 'fmo-1', 'fea-2', 'fn-3', 'fey-2', 'fsk-4', 'fea-4'],
  },

];

const initialData = {
  data: tsumuData,
  features,
};

export default initialData;
