const features: TsumuFeature = {
  'fg-1': '男の子のツム',
  'fg-2': '女の子のツム',
  'fhp-1': 'ハピネスツム',
  'fcat-1': 'プリンセスのツム',
  'fcat-2': 'プリンスのツム',
  'fcat-3': 'ヴィランズツム',
  'fcat-4': 'ハロウィンのツム',
  'fc-1': '白いツム',
  'fc-2': '黒いツム',
  'fc-3': '黄色いツム',
  'fc-4': '青いツム',
  'fc-5': '緑のツム',
  'fc-6': '赤いツム',
  'fc-7': '茶色いツム',
  'fc-8': '紫のツム',
  'fc-9': '肌色のツム',
  'fc-10': 'ピンクのツム',
  'fh-1': '白い手のツム',
  'fh-2': '黒い手のツム',
  'fh-3': '黄色い手のツム',
  'fsp-1': 'えりが見えるツム',
  'fsp-2': 'ツノのあるツム',
  'fsp-3': '海に住むツム',
  'fsp-4': 'ヒレのあるツム',
  'fsp-5': 'くちばしのあるツム',
  'fsp-6': '三つ目の宇宙人',
  'fha-1': '白い髪のツム',
  'fha-2': '毛のはねたツム',
  'fha-3': '毛を結んだツム',
  'fha-4': '毛が3本のツム',
  'fca-1': 'リボンをつけたツム',
  'fca-2': '冠をつけたツム',
  'fca-3': '花をつけたツム',
  'fca-4': '帽子をかぶったツム',
  'fey-1': 'まゆ毛のあるツム',
  'fey-2': 'まつ毛のあるツム',
  'fey-3': '白目が見えるツム',
  'fea-1': '耳が丸いツム',
  'fea-2': '耳がとがったツム',
  'fea-3': '耳が垂れたツム',
  'fea-4': '耳がピンクのツム',
  'fn-1': '鼻が三角のツム',
  'fn-2': '鼻が黒いツム',
  'fn-3': '鼻がピンクのツム',
  'fch-1': 'ほっぺが赤いツム',
  'fch-2': 'ヒゲのあるツム',
  'fmo-1': '口が見えるツム',
  'fty-1': 'イヌのツム',
  'fty-2': 'ネコ科のツム',
  'fty-3': 'うさぎのツム',
  'fty-4': 'トリのツム',
  'f-1': 'ミッキーのツム',
  'f-2': 'ミニーのツム',
  'f-3': 'ドナルドのツム',
  'fse-0': 'ミッキー＆フレンズのツム',
  'fse-1': 'ピクサーの仲間のツム',
  'fse-2': 'チップとデールのツム',
  'fse-3': 'トイストーリーシリーズ',
  'fse-4': 'モンスターズインクシリーズ',
  'fse-5': 'スターウォーズシリーズ',
  'fse-6': 'マーベルシリーズ',
  'fse-7': 'アナと雪の女王シリーズ',
  'fse-8': 'くまのプーさんシリーズ',
  'fse-9': '美女と野獣シリーズ',
  'fse-10': 'アラジンシリーズ',
  'fse-11': 'リロ＆スティッチシリーズ',
  'fse-12': 'リトルマーメイドシリーズ',
  'fse-13': 'ラプンツェルシリーズ',
  'fse-14': 'キングダムハーツシリーズ',
  'fi-1': 'イニシャルAのツム',
  'fi-2': 'イニシャルBのツム',
  'fi-3': 'イニシャルDのツム',
  'fi-4': 'イニシャルJのツム',
  'fi-5': 'イニシャルMのツム',
  'fi-6': 'イニシャルNのツム',
  'fi-7': 'イニシャルPのツム',
  'fi-8': 'イニシャルSのツム',
  'fi-9': 'イニシャルTのツム',
  'fsk-1': '消去系スキルのツム',
  'fsk-2': '画面中央消去スキルのツム',
  'fsk-3': '画面中央',
  'fsk-4': '横ライン消去スキルのツム',
  'fsk-5': '縦ライン消去スキルのツム',
  'fsk-6': '斜め消去スキルのツム',
  'fsk-7': 'ランダム消去スキルのツム',
  'fsk-8': '恋人を呼ぶスキルのツム',
  'fsk-9': '友だちを呼ぶスキルのツム',
  'fsk-10': 'ハートが出るスキルのツム',
  'fsk-11': 'ボムを出すスキルのツム',
  'fsk-12': '変化系スキルのツム',
  'fsk-13': '大ツムを発生させるツム',
  'fsk-14': 'コウモリが出るツム',
  'fsk-15': 'かぼちゃが出るツム',
  'fsk-16': 'クロスライン消去スキルのツム',
  'fsk-17': '逆T字消去数キルのツム',
  'fsk-18': '数カ所消去するスキルツム',
  'fsk-19': '特殊消去系スキルのツム',
  'fsk-20': '時間を止めるスキルのツム',
  'fsk-21': 'しっぽを振るスキルのツム',
  'fsk-22': 'サークル消去スキルのツム',
  'fsk-23': 'ジグザグ消去スキルのツム',
  'fsk-24': 'Z字消去スキルのツム',
  'fsk-25': '3方向消去スキルのツム',
  'fsk-26': 'アーチ消去スキルのツム',
  'fsk-27': 'S字消去スキルのツム',
  'fsk-28': 'Vライン消去スキルのツム',
  'fsk-29': '十字消去スキルのツム',
  'fsk-30': 'フィーバーに突入できるツム',
  'fsk-31': 'タップ消去スキルのツム',
  'fsk-34': '何が起こるかわからない',
};

const tsumuData: TsumuType[] = [
  {
    id: 'tm-1',
    name: 'ミッキー',
    imgUrl: '/images/tm-1.jpg',
    features: ['fh-1', 'fi-5', 'fsk-3', 'fg-1', 'f-1', 'fn-2', 'fea-1', 'fc-2'],
  },
  {
    id: 'tm-2',
    name: 'ミニー',
    imgUrl: '/images/tm-2.jpg',
    features: ['fh-1', 'fi-5', 'f-2', 'fsk-10', 'fg-2', 'fn-2', 'fsk-8', 'fea-1', 'fch-1', 'fey-2', 'fc-2', 'fca-1'],
  },
  {
    id: 'tm-3',
    name: 'ドナルド',
    imgUrl: '/images/tm-3.jpg',
    features: ['fh-1', 'fi-3', 'fg-1', 'fsp-5', 'f-3', 'fca-4', 'fc-1', 'fha-2', 'fch-1', 'fmo-1', 'fca-1'],
  },
  {
    id: 'tm-4',
    name: 'デイジー',
    imgUrl: '/images/tm-4.jpg',
    features: ['fh-1', 'fsp-5', 'fi-3', 'fc-1', 'fsk-10', 'fg-2', 'fsk-8', 'fch-1', 'fey-2', 'fmo-1', 'fca-1'],
  },
  {
    id: 'tm-5',
    name: 'グーフィー',
    imgUrl: '/images/tm-5.jpg',
    features: ['fh-1', 'fsk-7', 'fha-4', 'fg-1', 'fca-4', 'fty-1', 'fha-2', 'fea-3', 'fey-3', 'fn-2', 'fc-2'],
  },
  {
    id: 'tm-6',
    name: 'プルート',
    imgUrl: '/images/tm-6.jpg',
    features: ['fc-3', 'fsk-4', 'fg-1', 'fh-3', 'fty-1', 'fi-7', 'fea-3', 'fey-3', 'fn-2'],
  },
  {
    id: 'tm-7',
    name: 'チップ',
    imgUrl: '/images/tm-7.jpg',
    features: ['fn-1', 'fg-1', 'fsk-10', 'fsk-9', 'fc-7', 'fn-2', 'fch-1', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-8',
    name: 'デール',
    imgUrl: '/images/tm-8.jpg',
    features: ['fc-3', 'fi-3', 'fg-1', 'fea-4', 'fsk-10', 'fsk-9', 'fc-7', 'fch-1', 'fea-2', 'fn-3'],
  },
  {
    id: 'tm-9',
    name: 'プー',
    imgUrl: '/images/tm-9.jpg',
    features: ['fn-1', 'fc-3', 'fg-1', 'fsk-20', 'fh-3', 'fi-7', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-10',
    name: 'ピグレット',
    imgUrl: '/images/tm-10.jpg',
    features: ['fc-10', 'fn-1', 'fg-1', 'fea-4', 'fi-7', 'fch-1', 'fey-1', 'fea-2', 'fn-3'],
  },
  {
    id: 'tm-11',
    name: 'ティガー',
    imgUrl: '/images/tm-11.jpg',
    features: ['fty-2', 'fsk-7', 'fn-1', 'fsk-21', 'fc-3', 'fg-1', 'fh-3', 'fea-1', 'fch-2', 'fi-9', 'fey-1', 'fn-3'],
  },
  {
    id: 'tm-12',
    name: 'イーヨー',
    imgUrl: '/images/tm-12.jpg',
    features: ['fc-4', 'fg-1', 'fha-2', 'fea-3', 'fey-1', 'fc-8', 'fea-4'],
  },
  {
    id: 'tm-13',
    name: 'ルー',
    imgUrl: '/images/tm-13.jpg',
    features: ['fn-1', 'fg-1', 'fha-2', 'fsk-5', 'fc-7', 'fea-1', 'fey-1', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-14',
    name: 'クリストファーロビン',
    imgUrl: '/images/tm-14.jpg',
    features: ['fc-9', 'fg-1', 'fc-7', 'fea-1', 'fch-1', 'fey-1'],
  },
  {
    id: 'tm-15',
    name: 'スティッチ',
    imgUrl: '/images/tm-15.jpg',
    features: ['fc-4', 'fg-1', 'fi-8', 'fha-2', 'fsk-5', 'fmo-1', 'fea-2'],
  },
  {
    id: 'tm-16',
    name: 'スクランプ',
    imgUrl: '/images/tm-16.jpg',
    features: ['fc-4', 'fc-5', 'fi-8', 'fha-2', 'fsk-34', 'fg-2', 'fmo-1', 'fha-3', 'fca-1'],
  },
  {
    id: 'tm-17',
    name: 'エンジェル',
    imgUrl: '/images/tm-17.jpg',
    features: ['fc-10', 'fi-1', 'fsk-10', 'fg-2', 'fsk-8', 'fch-1', 'fey-2', 'fmo-1', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-18',
    name: 'ウッディ',
    imgUrl: '/images/tm-18.jpg',
    features: ['fsk-3', 'fc-9', 'fg-1', 'fca-4', 'fse-1', 'fi-7', 'fc-7', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-19',
    name: 'バズライトイヤー',
    imgUrl: '/images/tm-19.jpg',
    features: ['fh-1', 'fc-9', 'fg-1', 'fse-1', 'fsk-29', 'fey-1', 'fc-8', 'fi-2'],
  },
  {
    id: 'tm-20',
    name: 'ジェシー',
    imgUrl: '/images/tm-20.jpg',
    features: ['fey-1', 'fsk-3', 'fi-4', 'fc-9', 'fca-4', 'fea-1', 'fse-1', 'fg-2', 'fc-6', 'fch-1', 'fey-2', 'fha-3', 'fca-1'],
  },
  {
    id: 'tm-21',
    name: 'ロッツォ',
    imgUrl: '/images/tm-21.jpg',
    features: ['fc-10', 'fn-1', 'fc-6', 'fsk-4', 'fg-1', 'fse-1', 'fch-1', 'fea-1', 'fcat-3', 'fey-1', 'fea-4'],
  },
  {
    id: 'tm-22',
    name: 'レックス',
    imgUrl: '/images/tm-22.jpg',
    features: ['fg-1', 'fc-5', 'fse-1', 'fmo-1', 'fsk-18'],
  },
  {
    id: 'tm-23',
    name: 'アリス',
    imgUrl: '/images/tm-23.jpg',
    features: ['fc-3', 'fc-9', 'fi-1', 'fsk-13', 'fg-2', 'fea-1', 'fch-1', 'fey-2', 'fca-1'],
  },
  {
    id: 'tm-24',
    name: '白うさぎ',
    imgUrl: '/images/tm-24.jpg',
    features: ['fh-1', 'fn-1', 'fg-1', 'fty-3', 'fi-8', 'fc-1', 'fha-2', 'fea-4', 'fsk-20', 'fch-1', 'fea-2', 'fn-3'],
  },
  {
    id: 'tm-25',
    name: 'チェシャ猫',
    imgUrl: '/images/tm-25.jpg',
    features: ['fty-2', 'fsk-7', 'fc-10', 'fn-1', 'fsk-21', 'fg-1', 'fha-2', 'fea-4', 'fc-6', 'fch-1', 'fey-1', 'fea-2', 'fn-3'],
  },
  {
    id: 'tm-26',
    name: 'ヤングオイスター',
    imgUrl: '/images/tm-26.jpg',
    features: ['fey-1', 'fc-10', 'fsp-3', 'fca-4', 'fch-1', 'fmo-1', 'fc-8'],
  },
  {
    id: 'tm-27',
    name: 'マイク',
    imgUrl: '/images/tm-27.jpg',
    features: ['fi-5', 'fg-1', 'fc-5', 'fsk-9', 'fsk-5', 'fey-3', 'fse-1', 'fsp-2'],
  },
  {
    id: 'tm-28',
    name: 'サリー',
    imgUrl: '/images/tm-28.jpg',
    features: ['fn-1', 'fc-4', 'fg-1', 'fi-8', 'fsk-13', 'fse-1', 'fsp-2', 'fey-1'],
  },
  {
    id: 'tm-29',
    name: 'ランドール',
    imgUrl: '/images/tm-29.jpg',
    features: ['fha-4', 'fc-4', 'fg-1', 'fha-2', 'fey-3', 'fse-1', 'fcat-3', 'fmo-1', 'fc-8'],
  },
  {
    id: 'tm-30',
    name: 'バンビ',
    imgUrl: '/images/tm-30.jpg',
    features: ['fc-3', 'fcat-2', 'fg-1', 'fh-3', 'fha-2', 'fsk-18', 'fc-7', 'fn-2', 'fey-2', 'fi-2'],
  },
  {
    id: 'tm-31',
    name: 'とんすけ',
    imgUrl: '/images/tm-31.jpg',
    features: ['fh-1', 'fn-1', 'fsk-3', 'fg-1', 'fty-3', 'fsk-10', 'fsk-8', 'fi-9', 'fea-4', 'fn-3'],
  },
  {
    id: 'tm-32',
    name: 'ミスバニー',
    imgUrl: '/images/tm-32.jpg',
    features: ['fi-5', 'fn-1', 'fc-3', 'fty-3', 'fh-3', 'fea-4', 'fg-2', 'fsk-11', 'fch-1', 'fey-2', 'fi-2', 'fn-3'],
  },
  {
    id: 'tm-33',
    name: 'エルサ',
    imgUrl: '/images/tm-33.jpg',
    features: ['fey-1', 'fca-2', 'fc-9', 'fha-2', 'fey-3', 'fg-2', 'fea-1', 'fey-2', 'fha-3', 'fcat-1'],
  },
  {
    id: 'tm-34',
    name: 'アナ',
    imgUrl: '/images/tm-34.jpg',
    features: ['fey-1', 'fc-9', 'fi-1', 'fsk-10', 'fey-3', 'fg-2', 'fc-7', 'fea-1', 'fey-2', 'fha-3', 'fcat-1'],
  },
  {
    id: 'tm-35',
    name: 'オラフ',
    imgUrl: '/images/tm-35.jpg',
    features: ['fey-1', 'fsk-6', 'fha-4', 'fg-1', 'fc-1', 'fha-2', 'fmo-1'],
  },
  {
    id: 'tm-36',
    name: 'スヴェン',
    imgUrl: '/images/tm-36.jpg',
    features: ['fey-1', 'fsk-4', 'fg-1', 'fi-8', 'fc-7', 'fsp-2', 'fmo-1', 'fea-2'],
  },
  {
    id: 'tm-37',
    name: 'サプライズエルサ',
    imgUrl: '/images/tm-37.jpg',
    features: ['fey-1', 'fc-9', 'fi-8', 'fha-2', 'fca-3', 'fey-3', 'fg-2', 'fea-1', 'fey-2', 'fha-3', 'fcat-1'],
  },
  {
    id: 'tm-38',
    name: 'バースデーアナ',
    imgUrl: '/images/tm-38.jpg',
    features: ['fey-1', 'fc-9', 'fi-1', 'fsk-10', 'fca-3', 'fey-3', 'fg-2', 'fc-7', 'fea-1', 'fey-2', 'fha-3', 'fcat-1', 'fi-2', 'fca-1'],
  },
  {
    id: 'tm-39',
    name: 'アリエル',
    imgUrl: '/images/tm-39.jpg',
    features: ['fsp-3', 'fc-9', 'fsk-22', 'fea-1', 'fi-1', 'fha-2', 'fsp-4', 'fg-2', 'fc-6', 'fch-1', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-40',
    name: 'フランダー',
    imgUrl: '/images/tm-40.jpg',
    features: ['fc-3', 'fsp-3', 'fsk-4', 'fg-1', 'fmo-1', 'fsk-9', 'fsp-4', 'fch-1', 'fey-1'],
  },
  {
    id: 'tm-41',
    name: 'セバスチャン',
    imgUrl: '/images/tm-41.jpg',
    features: ['fsk-7', 'fsp-3', 'fg-1', 'fmo-1', 'fi-8', 'fc-6', 'fch-1', 'fey-1'],
  },
  {
    id: 'tm-42',
    name: 'トリトン王',
    imgUrl: '/images/tm-42.jpg',
    features: ['fsp-3', 'fca-2', 'fc-9', 'fg-1', 'fc-1', 'fsp-4', 'fsk-5', 'fha-1', 'fch-2', 'fi-9', 'fey-1', 'fn-3'],
  },
  {
    id: 'tm-43',
    name: 'ラプンツェル',
    imgUrl: '/images/tm-43.jpg',
    features: ['fc-3', 'fc-9', 'fca-3', 'fg-2', 'fsk-8', 'fea-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3'],
  },
  {
    id: 'tm-44',
    name: 'パスカル',
    imgUrl: '/images/tm-44.jpg',
    features: ['fg-1', 'fc-5', 'fey-3', 'fi-7', 'fmo-1'],
  },
  {
    id: 'tm-45',
    name: '野獣',
    imgUrl: '/images/tm-45.jpg',
    features: ['fsk-6', 'fc-3', 'fcat-2', 'fg-1', 'fh-3', 'fea-3', 'fc-7', 'fch-2', 'fsp-2', 'fey-1', 'fi-2', 'fea-4'],
  },
  {
    id: 'tm-46',
    name: 'ベル',
    imgUrl: '/images/tm-46.jpg',
    features: ['fey-1', 'fc-9', 'fsk-10', 'fc-7', 'fg-2', 'fsk-8', 'fea-1', 'fch-1', 'fey-2', 'fha-3', 'fcat-1', 'fi-2'],
  },
  {
    id: 'tm-47',
    name: 'マックィーン',
    imgUrl: '/images/tm-47.jpg',
    features: ['fi-5', 'fg-1', 'fh-2', 'fse-1', 'fey-3', 'fsk-31', 'fc-6', 'fch-1'],
  },
  {
    id: 'tm-48',
    name: 'メーター',
    imgUrl: '/images/tm-48.jpg',
    features: ['fi-5', 'fsk-7', 'fsk-21', 'fg-1', 'fh-2', 'fey-3', 'fc-7', 'fse-1', 'fmo-1'],
  },
  {
    id: 'tm-49',
    name: 'ジャスミン',
    imgUrl: '/images/tm-49.jpg',
    features: ['fey-1', 'fi-4', 'fca-2', 'fc-9', 'fsk-4', 'fc-2', 'fg-2', 'fc-7', 'fsk-8', 'fea-1', 'fch-1', 'fey-2', 'fha-3', 'fcat-1'],
  },
  {
    id: 'tm-50',
    name: 'アラジン',
    imgUrl: '/images/tm-50.jpg',
    features: ['fcat-2', 'fc-9', 'fg-1', 'fca-4', 'fi-1', 'fsk-9', 'fea-1', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-51',
    name: 'ジーニー',
    imgUrl: '/images/tm-51.jpg',
    features: ['fc-4', 'fg-1', 'fha-2', 'fsk-34', 'fch-2', 'fea-2', 'fey-1', 'fha-3'],
  },
  {
    id: 'tm-52',
    name: 'ピノキオ',
    imgUrl: '/images/tm-52.jpg',
    features: ['fc-3', 'fc-9', 'fg-1', 'fca-4', 'fi-7', 'fea-1', 'fch-1', 'fey-1'],
  },
  {
    id: 'tm-53',
    name: 'ベイマックス',
    imgUrl: '/images/tm-53.jpg',
    features: ['fh-1', 'fg-1', 'fc-1', 'fsk-13', 'fi-2'],
  },
  {
    id: 'tm-54',
    name: 'マレフィセント',
    imgUrl: '/images/tm-54.jpg',
    features: ['fi-5', 'fh-1', 'fca-4', 'fc-1', 'fg-2', 'fcat-3', 'fsp-2', 'fey-2', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-55',
    name: 'ダンボ',
    imgUrl: '/images/tm-55.jpg',
    features: ['fc-4', 'fi-3', 'fg-1', 'fca-4', 'fsk-5', 'fea-3', 'fch-1', 'fea-4'],
  },
  {
    id: 'tm-56',
    name: 'ティンカーベル',
    imgUrl: '/images/tm-56.jpg',
    features: ['fc-3', 'fi-2', 'fc-9', 'fsk-4', 'fg-2', 'fea-1', 'fi-9', 'fey-2', 'fey-1', 'fha-3'],
  },
  {
    id: 'tm-57',
    name: 'レディ',
    imgUrl: '/images/tm-57.jpg',
    features: ['fn-1', 'fc-3', 'fh-3', 'fty-1', 'fea-3', 'fg-2', 'fn-2', 'fch-1', 'fey-2'],
  },
  {
    id: 'tm-58',
    name: 'マリー',
    imgUrl: '/images/tm-58.jpg',
    features: ['fi-5', 'fh-1', 'fty-2', 'fn-1', 'fn-3', 'fc-1', 'fha-2', 'fea-4', 'fg-2', 'fsk-11', 'fch-2', 'fch-1', 'fey-2', 'fha-3', 'fea-2', 'fca-1'],
  },
  {
    id: 'tm-59',
    name: 'オーロラ姫',
    imgUrl: '/images/tm-59.jpg',
    features: ['fc-3', 'fca-2', 'fc-9', 'fi-1', 'fsk-10', 'fi-7', 'fg-2', 'fsk-8', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fi-2'],
  },
  {
    id: 'tm-60',
    name: '白雪姫',
    imgUrl: '/images/tm-60.jpg',
    features: ['fc-9', 'fc-2', 'fi-8', 'fsk-9', 'fg-2', 'fea-1', 'fch-1', 'fey-2', 'fcat-1', 'fca-1'],
  },
  {
    id: 'tm-61',
    name: 'ナラ',
    imgUrl: '/images/tm-61.jpg',
    features: ['fty-2', 'fi-6', 'fc-3', 'fh-3', 'fsk-10', 'fsk-9', 'fg-2', 'fc-7', 'fsk-8', 'fea-1', 'fey-1', 'fn-3'],
  },
  {
    id: 'tm-62',
    name: 'シンバ',
    imgUrl: '/images/tm-62.jpg',
    features: ['fty-2', 'fsk-3', 'fc-3', 'fcat-2', 'fg-1', 'fh-3', 'fha-2', 'fi-8', 'fc-7', 'fea-1', 'fey-1', 'fn-3'],
  },
  {
    id: 'tm-63',
    name: 'スカー',
    imgUrl: '/images/tm-63.jpg',
    features: ['fty-2', 'fsk-4', 'fg-1', 'fea-1', 'fha-2', 'fi-8', 'fc-7', 'fn-2', 'fch-2', 'fcat-3', 'fey-1'],
  },
  {
    id: 'tm-64',
    name: 'アースラ',
    imgUrl: '/images/tm-64.jpg',
    features: ['fsp-3', 'fsk-22', 'fc-1', 'fha-2', 'fi-1', 'fg-2', 'fha-1', 'fea-1', 'fcat-3', 'fey-2', 'fey-1', 'fc-8'],
  },
  {
    id: 'tm-65',
    name: '女王',
    imgUrl: '/images/tm-65.jpg',
    features: ['fsp-1', 'fi-4', 'fca-2', 'fc-9', 'fg-2', 'fsk-11', 'fcat-3', 'fey-2', 'fey-1'],
  },
  {
    id: 'tm-66',
    name: 'マレフィセントドラゴン',
    imgUrl: '/images/tm-66.jpg',
    features: ['fi-5', 'fcat-3', 'fi-3', 'fh-2', 'fg-2', 'fn-2', 'fch-2', 'fsp-2', 'fmo-1', 'fc-2'],
  },
  {
    id: 'tm-67',
    name: 'フィニック',
    imgUrl: '/images/tm-67.jpg',
    features: ['fn-1', 'fc-3', 'fg-1', 'fsk-5', 'fc-7', 'fn-2', 'fsp-1', 'fey-1', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-68',
    name: 'ニック',
    imgUrl: '/images/tm-68.jpg',
    features: ['fi-6', 'fsk-7', 'fn-1', 'fg-1', 'fc-7', 'fn-2', 'fsp-1', 'fey-1', 'fea-2'],
  },
  {
    id: 'tm-69',
    name: 'ジュディ',
    imgUrl: '/images/tm-69.jpg',
    features: ['fh-1', 'fea-2', 'fsk-3', 'fc-4', 'fi-4', 'fty-3', 'fca-4', 'fh-2', 'fg-2', 'fey-2', 'fey-1', 'fc-2', 'fea-4', 'fn-3'],
  },
  {
    id: 'tm-70',
    name: 'シンデレラ',
    imgUrl: '/images/tm-70.jpg',
    features: ['fh-1', 'fc-3', 'fc-9', 'fi-8', 'fg-2', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3'],
  },
  {
    id: 'tm-71',
    name: 'フェアリーゴッドマザー',
    imgUrl: '/images/tm-71.jpg',
    features: ['fc-4', 'fc-9', 'fca-4', 'fsk-10', 'fsk-9', 'fg-2', 'fha-1', 'fch-1', 'fey-1', 'fca-1'],
  },
  {
    id: 'tm-72',
    name: 'マッドハッター',
    imgUrl: '/images/tm-72.jpg',
    features: ['fi-5', 'fc-4', 'fc-9', 'fg-1', 'fc-5', 'fca-4', 'fha-2', 'fha-1', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-73',
    name: 'ハートの女王',
    imgUrl: '/images/tm-73.jpg',
    features: ['fca-2', 'fc-9', 'fha-2', 'fg-2', 'fsp-1', 'fea-1', 'fcat-3', 'fey-1', 'fha-3'],
  },
  {
    id: 'tm-74',
    name: 'ドリー',
    imgUrl: '/images/tm-74.jpg',
    features: ['fc-4', 'fsp-3', 'fi-3', 'fh-3', 'fsp-4', 'fey-3', 'fg-2', 'fse-1', 'fmo-1', 'fsk-24'],
  },
  {
    id: 'tm-75',
    name: 'ニモ',
    imgUrl: '/images/tm-75.jpg',
    features: ['fi-6', 'fsp-3', 'fsk-4', 'fg-1', 'fsp-4', 'fey-3', 'fse-1', 'fmo-1'],
  },
  {
    id: 'tm-76',
    name: 'クラッシュ',
    imgUrl: '/images/tm-76.jpg',
    features: ['fsp-3', 'fc-5', 'fsk-9', 'fsp-4', 'fey-3', 'fsk-5', 'fse-1', 'fmo-1'],
  },
  {
    id: 'tm-77',
    name: 'クルエラ',
    imgUrl: '/images/tm-77.jpg',
    features: ['fc-9', 'fi-3', 'fc-1', 'fha-2', 'fch-1', 'fg-2', 'fha-1', 'fsk-27', 'fcat-3', 'fey-2', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-78',
    name: 'フック船長',
    imgUrl: '/images/tm-78.jpg',
    features: ['fc-6', 'fc-9', 'fg-1', 'fca-4', 'fsk-5', 'fch-2', 'fcat-3', 'fey-1'],
  },
  {
    id: 'tm-79',
    name: 'ジャファー',
    imgUrl: '/images/tm-79.jpg',
    features: ['fc-6', 'fi-4', 'fc-9', 'fg-1', 'fca-4', 'fsk-16', 'fch-2', 'fcat-3', 'fey-1'],
  },
  {
    id: 'tm-80',
    name: 'モアナ',
    imgUrl: '/images/tm-80.jpg',
    features: ['fi-5', 'fcat-1', 'fc-9', 'fsk-4', 'fha-2', 'fca-3', 'fg-2', 'fc-7', 'fsk-11', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-81',
    name: 'マウイ',
    imgUrl: '/images/tm-81.jpg',
    features: ['fi-5', 'fc-9', 'fg-1', 'fha-2', 'fsk-5', 'fsk-34', 'fc-7', 'fea-1', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-82',
    name: 'ヘラクレス',
    imgUrl: '/images/tm-82.jpg',
    features: ['fc-3', 'fc-9', 'fg-1', 'fsk-4', 'fha-2', 'fc-7', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-83',
    name: 'フィリップ王子',
    imgUrl: '/images/tm-83.jpg',
    features: ['fsk-3', 'fcat-2', 'fc-9', 'fg-1', 'fca-4', 'fea-1', 'fi-7', 'fsp-1', 'fc-6', 'fey-1'],
  },
  {
    id: 'tm-84',
    name: 'ハデス',
    imgUrl: '/images/tm-84.jpg',
    features: ['fc-4', 'fg-1', 'fha-2', 'fey-3', 'fcat-3', 'fsk-29', 'fey-1', 'fea-2'],
  },
  {
    id: 'tm-85',
    name: 'ガストン',
    imgUrl: '/images/tm-85.jpg',
    features: ['fc-9', 'fg-1', 'fsk-4', 'fsp-1', 'fea-1', 'fcat-3', 'fey-1', 'fc-2', 'fha-3', 'fca-1'],
  },
  {
    id: 'tm-86',
    name: 'ルミエール',
    imgUrl: '/images/tm-86.jpg',
    features: ['fh-1', 'fsk-7', 'fc-3', 'fg-1', 'fsk-30', 'fh-3', 'fc-1', 'fey-1'],
  },
  {
    id: 'tm-87',
    name: 'フリンライダー',
    imgUrl: '/images/tm-87.jpg',
    features: ['fcat-2', 'fc-9', 'fg-1', 'fea-1', 'fc-7', 'fsk-8', 'fsp-1', 'fch-2', 'fey-1'],
  },
  {
    id: 'tm-88',
    name: 'マキシマス',
    imgUrl: '/images/tm-88.jpg',
    features: ['fi-5', 'fh-1', 'fsk-6', 'fg-1', 'fc-1', 'fha-1', 'fey-1', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-89',
    name: 'ムーラン',
    imgUrl: '/images/tm-89.jpg',
    features: ['fi-5', 'fc-9', 'fc-2', 'fg-2', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1'],
  },
  {
    id: 'tm-90',
    name: 'ポカホンタス',
    imgUrl: '/images/tm-90.jpg',
    features: ['fcat-1', 'fc-9', 'fea-1', 'fi-7', 'fg-2', 'fc-7', 'fsk-8', 'fsk-20', 'fch-1', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-91',
    name: 'クルーズラミレス',
    imgUrl: '/images/tm-91.jpg',
    features: ['fsk-6', 'fc-3', 'fh-2', 'fsk-9', 'fey-3', 'fg-2', 'fse-1'],
  },
  {
    id: 'tm-92',
    name: 'ピーターパン',
    imgUrl: '/images/tm-92.jpg',
    features: ['fc-3', 'fc-9', 'fg-1', 'fc-5', 'fca-4', 'fsk-9', 'fsk-5', 'fi-7', 'fc-7', 'fea-1', 'fch-1', 'fey-1'],
  },
  {
    id: 'tm-93',
    name: 'トランプ',
    imgUrl: '/images/tm-93.jpg',
    features: ['fn-1', 'fsk-4', 'fg-1', 'fty-1', 'fsk-10', 'fha-2', 'fea-3', 'fn-2', 'fsk-8', 'fi-9', 'fey-1', 'fc-2', 'fea-4'],
  },
  {
    id: 'tm-94',
    name: 'ブルーフェアリー',
    imgUrl: '/images/tm-94.jpg',
    features: ['fc-3', 'fc-9', 'fg-2', 'fsk-11', 'fch-1', 'fey-2', 'fey-1', 'fi-2'],
  },
  {
    id: 'tm-95',
    name: 'ティモシー',
    imgUrl: '/images/tm-95.jpg',
    features: ['fh-1', 'fi-5', 'fn-1', 'fg-1', 'fca-4', 'fea-1', 'fsk-9', 'fc-7', 'fn-2', 'fsk-11', 'fch-2', 'fi-9', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-96',
    name: 'パッチ',
    imgUrl: '/images/tm-96.jpg',
    features: ['fh-1', 'fsk-4', 'fg-1', 'fty-1', 'fc-1', 'fea-3', 'fi-7', 'fn-2', 'fch-1', 'fey-1', 'fea-4'],
  },
  {
    id: 'tm-97',
    name: '王子',
    imgUrl: '/images/tm-97.jpg',
    features: ['fc-4', 'fcat-2', 'fc-9', 'fg-1', 'fca-4', 'fsk-10', 'fi-7', 'fsk-8', 'fsp-1', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-98',
    name: 'ブー',
    imgUrl: '/images/tm-98.jpg',
    features: ['fi-5', 'fc-9', 'fmo-1', 'fca-4', 'fh-3', 'fsk-9', 'fsk-13', 'fey-3', 'fg-2', 'fse-1', 'fch-1', 'fey-2', 'fey-1', 'fi-2'],
  },
  {
    id: 'tm-99',
    name: 'フラワー',
    imgUrl: '/images/tm-99.jpg',
    features: ['fn-1', 'fg-1', 'fh-2', 'fha-2', 'fn-2', 'fea-1', 'fch-1', 'fey-2', 'fc-2'],
  },
  {
    id: 'tm-100',
    name: 'ダッチェス',
    imgUrl: '/images/tm-100.jpg',
    features: ['fh-1', 'fty-2', 'fn-1', 'fn-3', 'fi-3', 'fc-1', 'fha-2', 'fg-2', 'fsk-8', 'fch-2', 'fch-1', 'fey-2', 'fey-1', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-101',
    name: 'ロビンフッド',
    imgUrl: '/images/tm-101.jpg',
    features: ['fn-1', 'fg-1', 'fca-4', 'fha-2', 'fsk-5', 'fc-7', 'fn-2', 'fsp-1', 'fea-2'],
  },
  {
    id: 'tm-102',
    name: 'ゴーテル',
    imgUrl: '/images/tm-102.jpg',
    features: ['fcat-3', 'fi-5', 'fha-2', 'fey-3', 'fg-2', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-103',
    name: 'ハム',
    imgUrl: '/images/tm-103.jpg',
    features: ['fn-3', 'fsk-4', 'fg-1', 'fse-1', 'fch-1', 'fey-1', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-104',
    name: 'ティモン',
    imgUrl: '/images/tm-104.jpg',
    features: ['fg-1', 'fsk-9', 'fsk-13', 'fey-3', 'fc-7', 'fea-3', 'fi-9', 'fey-1'],
  },
  {
    id: 'tm-105',
    name: 'ラフィキ',
    imgUrl: '/images/tm-105.jpg',
    features: ['fn-1', 'fg-1', 'fha-2', 'fha-1', 'fch-2', 'fsk-18'],
  },
  {
    id: 'tm-106',
    name: 'クリストフ',
    imgUrl: '/images/tm-106.jpg',
    features: ['fc-3', 'fsk-4', 'fg-1', 'fc-9', 'fea-1', 'fch-1', 'fey-1', 'fi-2'],
  },
  {
    id: 'tm-107',
    name: 'ラジャー',
    imgUrl: '/images/tm-107.jpg',
    features: ['fh-1', 'fsk-1', 'fty-2', 'fn-1', 'fc-3', 'fsk-4', 'fg-1', 'fha-2', 'fey-1', 'fea-2', 'fn-3'],
  },
  {
    id: 'tm-108',
    name: 'レミー',
    imgUrl: '/images/tm-108.jpg',
    features: ['fch-2', 'fn-3', 'fg-1', 'fsk-30', 'fca-4', 'fse-1', 'fea-1', 'fmo-1', 'fc-2', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-109',
    name: 'フリック',
    imgUrl: '/images/tm-109.jpg',
    features: ['fey-1', 'fc-4', 'fg-1', 'fsk-10', 'fse-1', 'fmo-1'],
  },
  {
    id: 'tm-110',
    name: 'ガントゥ',
    imgUrl: '/images/tm-110.jpg',
    features: ['fsk-1', 'fsk-4', 'fg-1', 'fh-2', 'fea-3', 'fcat-3', 'fsp-2', 'fmo-1', 'fc-2'],
  },
  {
    id: 'tm-111',
    name: 'ワート',
    imgUrl: '/images/tm-111.jpg',
    features: ['fsk-1', 'fc-3', 'fg-1', 'fha-2', 'fi-1', 'fsk-5', 'fsp-1', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-112',
    name: 'マーリン',
    imgUrl: '/images/tm-112.jpg',
    features: ['fi-5', 'fch-2', 'fc-4', 'fg-1', 'fca-4', 'fha-2', 'fha-1', 'fsp-1', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-113',
    name: 'ダンテ',
    imgUrl: '/images/tm-113.jpg',
    features: ['fsk-1', 'fey-1', 'fn-1', 'fi-3', 'fg-1', 'fh-2', 'fty-1', 'fha-2', 'fea-3', 'fn-2', 'fse-1', 'fmo-1', 'fc-2', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-114',
    name: 'ジョン',
    imgUrl: '/images/tm-114.jpg',
    features: ['fsk-1', 'fsk-7', 'fg-1', 'fca-4', 'fsk-9', 'fc-7', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-115',
    name: 'ウェンディ',
    imgUrl: '/images/tm-115.jpg',
    features: ['fi-5', 'fsk-1', 'fsk-3', 'fsk-9', 'fg-2', 'fc-7', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fha-3', 'fca-1'],
  },
  {
    id: 'tm-116',
    name: 'フロロー',
    imgUrl: '/images/tm-116.jpg',
    features: ['fsk-1', 'fg-1', 'fca-4', 'fsk-5', 'fha-1', 'fsp-1', 'fea-1', 'fcat-3', 'fey-1'],
  },
  {
    id: 'tm-117',
    name: 'クリスマスミッキー',
    imgUrl: '/images/tm-117.jpg',
    features: ['fi-5', 'fh-1', 'fsk-3', 'fg-1', 'fca-4', 'f-1', 'fn-2', 'fea-1', 'fc-2'],
  },
  {
    id: 'tm-118',
    name: 'クリスマスミニー',
    imgUrl: '/images/tm-118.jpg',
    features: ['fh-1', 'fi-5', 'f-2', 'fsk-10', 'fg-2', 'fn-2', 'fsk-8', 'fea-1', 'fch-1', 'fey-2', 'fc-2', 'fca-1'],
  },
  {
    id: 'tm-119',
    name: 'コンサートミッキー',
    imgUrl: '/images/tm-119.jpg',
    features: ['fi-5', 'fh-1', 'fg-1', 'fca-4', 'fc-1', 'f-1', 'fn-2', 'fsp-1', 'fea-1', 'fc-2'],
  },
  {
    id: 'tm-120',
    name: 'クリスマスデイジー',
    imgUrl: '/images/tm-120.jpg',
    features: ['fh-1', 'fsp-5', 'fi-3', 'fca-4', 'fc-1', 'fsk-10', 'fg-2', 'fsk-8', 'fch-1', 'fey-2', 'fmo-1', 'fca-1'],
  },
  {
    id: 'tm-121',
    name: 'クリスマスドナルド',
    imgUrl: '/images/tm-121.jpg',
    features: ['fh-1', 'fsp-5', 'fg-1', 'fi-3', 'f-3', 'fca-4', 'fc-1', 'fha-2', 'fch-1', 'fmo-1', 'fca-1'],
  },
  {
    id: 'tm-122',
    name: 'クリスマスプルート',
    imgUrl: '/images/tm-122.jpg',
    features: ['fc-3', 'fsk-4', 'fg-1', 'fca-4', 'fty-1', 'fh-3', 'fea-3', 'fi-7', 'fey-3', 'fsp-2', 'fca-1'],
  },
  {
    id: 'tm-123',
    name: 'クリスマスグーフィー',
    imgUrl: '/images/tm-123.jpg',
    features: ['fsk-7', 'fha-4', 'fg-1', 'fca-4', 'fha-2', 'fty-1', 'fea-3', 'fey-3', 'fn-2', 'fsp-1', 'fch-2', 'fc-2'],
  },
  {
    id: 'tm-124',
    name: 'バレンタインミニー',
    imgUrl: '/images/tm-124.jpg',
    features: ['fh-1', 'fi-5', 'f-2', 'fsk-10', 'fg-2', 'fc-7', 'fsk-8', 'fea-1', 'fch-1', 'fey-2', 'fca-1'],
  },
  {
    id: 'tm-125',
    name: 'バレンタインデイジー',
    imgUrl: '/images/tm-125.jpg',
    features: ['fc-3', 'fsp-5', 'fi-3', 'fh-3', 'fsk-10', 'fg-2', 'fc-7', 'fsk-8', 'fch-1', 'fey-2', 'fmo-1', 'fca-1'],
  },
  {
    id: 'tm-126',
    name: 'かぼちゃミッキー',
    imgUrl: '/images/tm-126.jpg',
    features: ['fh-1', 'fi-5', 'fc-3', 'fsk-15', 'fg-1', 'fsk-30', 'fca-4', 'f-1', 'fi-7', 'fn-2', 'fea-1', 'fcat-4'],
  },
  {
    id: 'tm-127',
    name: 'かぼちゃミニー',
    imgUrl: '/images/tm-127.jpg',
    features: ['fh-1', 'fi-5', 'fc-10', 'f-2', 'fsk-15', 'fca-4', 'fi-7', 'fg-2', 'fn-2', 'fcat-4', 'fea-1', 'fch-1', 'fey-2', 'fea-4', 'fca-1'],
  },
  {
    id: 'tm-128',
    name: 'ホーンハットミッキー',
    imgUrl: '/images/tm-128.jpg',
    features: ['fh-1', 'fi-5', 'fc-6', 'fsk-15', 'fg-1', 'fca-4', 'f-1', 'fsk-14', 'fsp-2', 'fn-2', 'fsk-11', 'fea-1', 'fi-9', 'fmo-1', 'fc-2'],
  },
  {
    id: 'tm-129',
    name: 'キャットハットミニー',
    imgUrl: '/images/tm-129.jpg',
    features: ['fh-1', 'fi-5', 'fty-2', 'f-2', 'fsk-15', 'fca-4', 'fea-4', 'fsk-10', 'fsk-14', 'fg-2', 'fn-2', 'fsk-8', 'fch-2', 'fch-1', 'fey-2', 'fc-8', 'fea-2', 'fca-1'],
  },
  {
    id: 'tm-130',
    name: 'かぼちゃチップ',
    imgUrl: '/images/tm-130.jpg',
    features: ['fn-1', 'fc-3', 'fsk-15', 'fg-1', 'fca-4', 'fsk-10', 'fsk-9', 'fc-7', 'fn-2', 'fch-1', 'fcat-4', 'fmo-1'],
  },
  {
    id: 'tm-131',
    name: 'おばけデール',
    imgUrl: '/images/tm-131.jpg',
    features: ['fi-3', 'fg-1', 'fsk-15', 'fc-1', 'fsk-10', 'fsk-9', 'fsk-14', 'fcat-4', 'fea-2', 'fn-3'],
  },
  {
    id: 'tm-132',
    name: 'ウサプー',
    imgUrl: '/images/tm-132.jpg',
    features: ['fn-1', 'fc-3', 'fc-4', 'fg-1', 'fty-3', 'fh-3', 'fca-4', 'fi-7', 'fsk-11', 'fey-1', 'fi-2'],
  },
  {
    id: 'tm-133',
    name: 'ウサティガー',
    imgUrl: '/images/tm-133.jpg',
    features: ['fty-2', 'fn-1', 'fc-3', 'fg-1', 'fty-3', 'fca-4', 'fh-3', 'fea-4', 'fsk-26', 'fch-2', 'fi-9', 'fey-1', 'fi-2', 'fn-3'],
  },
  {
    id: 'tm-134',
    name: 'ハチプー',
    imgUrl: '/images/tm-134.jpg',
    features: ['fn-1', 'fc-3', 'fg-1', 'fsk-20', 'fca-4', 'fh-3', 'fi-7', 'fea-1', 'fsp-2', 'fey-1', 'fi-2'],
  },
  {
    id: 'tm-135',
    name: 'ハワイアンスティッチ',
    imgUrl: '/images/tm-135.jpg',
    features: ['fc-4', 'fg-1', 'fi-8', 'fha-2', 'fca-3', 'fsk-26', 'fsp-1', 'fmo-1', 'fea-2'],
  },
  {
    id: 'tm-136',
    name: 'ジャック',
    imgUrl: '/images/tm-136.jpg',
    features: ['fh-1', 'fi-4', 'fg-1', 'fi-8', 'fc-1', 'fsk-14', 'fn-2', 'fcat-4', 'fmo-1'],
  },
  {
    id: 'tm-137',
    name: 'サリー(NBC)',
    imgUrl: '/images/tm-137.jpg',
    features: ['fc-4', 'fc-5', 'fi-8', 'fsk-16', 'fg-2', 'fcat-4', 'fc-6', 'fey-2', 'fmo-1'],
  },
  {
    id: 'tm-138',
    name: 'ゼロ',
    imgUrl: '/images/tm-138.jpg',
    features: ['fg-1', 'fc-1', 'fty-1', 'fcat-4', 'fea-2'],
  },
  {
    id: 'tm-139',
    name: 'ロマンスアリエル',
    imgUrl: '/images/tm-139.jpg',
    features: ['fsp-3', 'fc-9', 'fea-1', 'fi-1', 'fsk-10', 'fha-2', 'fsp-4', 'fg-2', 'fsk-8', 'fc-6', 'fch-1', 'fey-2', 'fha-3', 'fcat-1', 'fca-1'],
  },
  {
    id: 'tm-140',
    name: 'ソーサラーミッキー',
    imgUrl: '/images/tm-140.jpg',
    features: ['fi-5', 'fh-1', 'fg-1', 'fca-4', 'fi-8', 'f-1', 'fsk-31', 'fn-2', 'fsp-1', 'fea-1', 'fc-2', 'fca-1'],
  },
  {
    id: 'tm-141',
    name: 'ペリー',
    imgUrl: '/images/tm-141.jpg',
    features: ['fha-4', 'fc-4', 'fsp-5', 'fg-1', 'fc-5', 'fha-2', 'fi-7', 'fey-3', 'fmo-1', 'fsk-18'],
  },
  {
    id: 'tm-142',
    name: 'ヨーダ',
    imgUrl: '/images/tm-142.jpg',
    features: ['fsk-20', 'fg-1', 'fc-5', 'fea-2'],
  },
  {
    id: 'tm-143',
    name: 'R2-D2',
    imgUrl: '/images/tm-143.jpg',
    features: ['fh-1', 'fc-4', 'fg-1', 'fc-1', 'fsk-33'],
  },
  {
    id: 'tm-144',
    name: 'ルーク',
    imgUrl: '/images/tm-144.jpg',
    features: ['fc-3', 'fc-9', 'fg-1', 'fca-4', 'fc-1', 'fi-8', 'fh-2', 'fsk-16'],
  },
  {
    id: 'tm-145',
    name: 'ダースベイダー',
    imgUrl: '/images/tm-145.jpg',
    features: ['fi-3', 'fg-1', 'fca-4', 'fh-2', 'fn-2', 'fcat-3', 'fmo-1', 'fc-2'],
  },
  {
    id: 'tm-146',
    name: 'BB-8',
    imgUrl: '/images/tm-146.jpg',
    features: ['fsk-32', 'fsk-4', 'fg-1', 'fc-1', 'fi-2'],
  },
  {
    id: 'tm-147',
    name: 'クラリス',
    imgUrl: '/images/tm-147.jpg',
    features: ['fn-1', 'fc-3', 'fh-3', 'fsk-10', 'fsk-9', 'fca-3', 'fg-2', 'fc-7', 'fch-1', 'fey-2', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-148',
    name: 'モカ',
    imgUrl: '/images/tm-148.jpg',
    features: ['fi-5', 'fg-1', 'fc-7', 'fn-2', 'fea-1', 'fmo-1'],
  },
  {
    id: 'tm-149',
    name: 'プリン',
    imgUrl: '/images/tm-149.jpg',
    features: ['fsk-3', 'fsk-10', 'fi-7', 'fg-2', 'fc-7', 'fn-2', 'fsk-8', 'fea-1', 'fey-2', 'fmo-1', 'fca-1'],
  },
  {
    id: 'tm-150',
    name: 'ブライドラプンツェル',
    imgUrl: '/images/tm-150.jpg',
    features: ['fca-2', 'fc-9', 'fsk-5', 'fg-2', 'fc-7', 'fea-1', 'fey-2', 'fey-1', 'fcat-1', 'fi-2'],
  },
  {
    id: 'tm-151',
    name: 'カイロレン',
    imgUrl: '/images/tm-151.jpg',
    features: ['fg-1', 'fca-4', 'fh-2', 'fn-2', 'fsk-17', 'fcat-3', 'fc-2'],
  },
  {
    id: 'tm-152',
    name: 'レイ',
    imgUrl: '/images/tm-152.jpg',
    features: ['fc-9', 'fsk-4', 'fca-4', 'fg-2', 'fc-7', 'fey-2', 'fey-1'],
  },
  {
    id: 'tm-153',
    name: 'おしゃれマッドハッター',
    imgUrl: '/images/tm-153.jpg',
    features: ['fh-1', 'fi-5', 'fsk-25', 'fg-1', 'fca-4', 'fha-2', 'fc-1', 'fc-6', 'fi-9', 'fey-1', 'fca-1'],
  },
  {
    id: 'tm-154',
    name: 'ワンダーランドアリス',
    imgUrl: '/images/tm-154.jpg',
    features: ['fc-3', 'fc-9', 'fg-2', 'fea-1', 'fch-1', 'fey-2', 'fca-1'],
  },
  {
    id: 'tm-155',
    name: 'モーグリ',
    imgUrl: '/images/tm-155.jpg',
    features: ['fi-5', 'fc-9', 'fg-1', 'fsk-4', 'fha-2', 'fsk-9', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-156',
    name: 'エリザベススワン',
    imgUrl: '/images/tm-156.jpg',
    features: ['fc-9', 'fca-4', 'fha-2', 'fsk-10', 'fi-8', 'fg-2', 'fc-7', 'fsk-8', 'fsp-1', 'fea-1', 'fch-1', 'fey-2', 'fey-1'],
  },
  {
    id: 'tm-157',
    name: 'ジャックスパロウ',
    imgUrl: '/images/tm-157.jpg',
    features: ['fsk-6', 'fi-4', 'fc-9', 'fg-1', 'fca-4', 'fi-8', 'fc-7', 'fch-2', 'fey-1', 'fha-3'],
  },
  {
    id: 'tm-158',
    name: 'デイヴィジョーンズ',
    imgUrl: '/images/tm-158.jpg',
    features: ['fsk-3', 'fsp-3', 'fi-4', 'fi-3', 'fg-1', 'fca-4', 'fc-7', 'fch-2', 'fcat-3'],
  },
  {
    id: 'tm-159',
    name: 'パレードミッキー',
    imgUrl: '/images/tm-159.jpg',
    features: ['fi-5', 'fh-1', 'fsk-4', 'fg-1', 'fsk-30', 'f-1', 'fi-7', 'fn-2', 'fsp-1', 'fea-1', 'fc-2', 'fca-1'],
  },
  {
    id: 'tm-160',
    name: 'パレードティンク',
    imgUrl: '/images/tm-160.jpg',
    features: ['fey-1', 'fc-3', 'fc-9', 'fsk-30', 'fsk-4', 'fi-9', 'fg-2', 'fi-7', 'fsk-11', 'fea-1', 'fch-1', 'fey-2', 'fha-3', 'fca-1'],
  },
  {
    id: 'tm-161',
    name: '蒸気船ミッキー',
    imgUrl: '/images/tm-161.jpg',
    features: ['fi-5', 'fi-4', 'fsk-32', 'fg-1', 'fca-4', 'fc-1', 'fi-8', 'f-1', 'fh-2', 'fn-2', 'fea-1', 'fc-2'],
  },
  {
    id: 'tm-162',
    name: '蒸気船ピート',
    imgUrl: '/images/tm-162.jpg',
    features: ['fty-2', 'fi-4', 'fg-1', 'fca-4', 'fc-1', 'fi-8', 'fh-2', 'fsk-5', 'fi-7', 'fn-2', 'fch-2', 'fcat-3', 'fc-2', 'fea-2'],
  },
  {
    id: 'tm-163',
    name: '蒸気船ミニー',
    imgUrl: '/images/tm-163.jpg',
    features: ['fi-5', 'fsk-7', 'fi-4', 'f-2', 'fca-4', 'fc-1', 'fi-8', 'fh-2', 'fca-3', 'fg-2', 'fn-2', 'fsk-8', 'fea-1', 'fey-2', 'fc-2'],
  },
  {
    id: 'tm-164',
    name: 'K2SO',
    imgUrl: '/images/tm-164.jpg',
    features: ['fsk-3', 'fg-1', 'fh-2', 'fn-2', 'fmo-1', 'fc-2'],
  },
  {
    id: 'tm-165',
    name: 'ジェダイルーク',
    imgUrl: '/images/tm-165.jpg',
    features: ['fi-4', 'fc-9', 'fg-1', 'fca-4', 'fh-2', 'fsk-9', 'fc-7', 'fey-1'],
  },
  {
    id: 'tm-166',
    name: 'ハンソロ',
    imgUrl: '/images/tm-166.jpg',
    features: ['fsk-3', 'fc-9', 'fg-1', 'fi-8', 'fsk-9', 'fc-7', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-167',
    name: 'チューバッカ',
    imgUrl: '/images/tm-167.jpg',
    features: ['fn-1', 'fsk-4', 'fg-1', 'fha-2', 'fc-7', 'fn-2', 'fch-2', 'fmo-1'],
  },
  {
    id: 'tm-168',
    name: 'ベイマックス2.0',
    imgUrl: '/images/tm-168.jpg',
    features: ['fsk-4', 'fg-1', 'fca-4', 'fc-6', 'fi-2'],
  },
  {
    id: 'tm-169',
    name: 'ヒロ',
    imgUrl: '/images/tm-169.jpg',
    features: ['fsk-4', 'fg-1', 'fca-4', 'fsk-9', 'fey-1', 'fc-8'],
  },
  {
    id: 'tm-170',
    name: 'ホイップ',
    imgUrl: '/images/tm-170.jpg',
    features: ['fh-1', 'fsk-7', 'fn-1', 'fg-1', 'fc-1', 'fsk-8', 'fea-1', 'fmo-1'],
  },
  {
    id: 'tm-171',
    name: 'パフィー',
    imgUrl: '/images/tm-171.jpg',
    features: ['fh-1', 'fn-1', 'fc-1', 'fsk-10', 'fi-7', 'fg-2', 'fsk-8', 'fea-1', 'fey-2', 'fmo-1', 'fca-1'],
  },
  {
    id: 'tm-172',
    name: '三銃士ミッキー',
    imgUrl: '/images/tm-172.jpg',
    features: ['fi-5', 'fh-1', 'fsk-6', 'fg-1', 'fca-4', 'fi-8', 'f-1', 'fsk-9', 'fsk-5', 'fn-2', 'fsp-1', 'fea-1', 'fc-2'],
  },
  {
    id: 'tm-173',
    name: '三銃士ドナルド',
    imgUrl: '/images/tm-173.jpg',
    features: ['fi-5', 'fh-1', 'fsk-7', 'fsp-5', 'fg-1', 'fi-3', 'f-3', 'fca-4', 'fha-2', 'fi-8', 'fc-1', 'fsp-1', 'fch-1', 'fmo-1'],
  },
  {
    id: 'tm-174',
    name: '三銃士グーフィー',
    imgUrl: '/images/tm-174.jpg',
    features: ['fi-5', 'fh-1', 'fg-1', 'fca-4', 'fi-8', 'fty-1', 'fey-3', 'fea-3', 'fn-2', 'fsp-1', 'fc-2', 'fsk-24'],
  },
  {
    id: 'tm-175',
    name: 'お姫様デイジー',
    imgUrl: '/images/tm-175.jpg',
    features: ['fh-1', 'fca-2', 'fi-3', 'fsp-5', 'fc-2', 'fc-1', 'fi-7', 'fg-2', 'fsk-8', 'fsp-1', 'fch-1', 'fey-2', 'fmo-1', 'fcat-1', 'fha-3', 'fca-1'],
  },
  {
    id: 'tm-176',
    name: '忍者ドナルド',
    imgUrl: '/images/tm-176.jpg',
    features: ['fh-1', 'fi-6', 'fsp-5', 'fi-3', 'fg-1', 'f-3', 'fha-2', 'fc-1', 'fsk-23', 'fsk-11', 'fch-1', 'fmo-1', 'fha-3', 'fca-1'],
  },
  {
    id: 'tm-177',
    name: 'キュートアナ',
    imgUrl: '/images/tm-177.jpg',
    features: ['fc-9', 'fsk-4', 'fi-1', 'fey-3', 'fg-2', 'fc-7', 'fea-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3'],
  },
  {
    id: 'tm-178',
    name: 'キュートエルサ',
    imgUrl: '/images/tm-178.jpg',
    features: ['fc-9', 'fey-3', 'fg-2', 'fsk-19', 'fea-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3'],
  },
  {
    id: 'tm-179',
    name: 'サマーオラフ',
    imgUrl: '/images/tm-179.jpg',
    features: ['fg-1', 'fmo-1', 'fi-8', 'fca-4', 'fc-1', 'fey-1'],
  },
  {
    id: 'tm-180',
    name: 'ファンタズミックミッキー',
    imgUrl: '/images/tm-180.jpg',
    features: ['fh-1', 'fi-5', 'fg-1', 'fsk-30', 'fca-4', 'f-1', 'fn-2', 'fsp-1', 'fea-1', 'fey-1', 'fc-2', 'fca-1'],
  },
  {
    id: 'tm-181',
    name: 'ソラ',
    imgUrl: '/images/tm-181.jpg',
    features: ['fh-1', 'fca-2', 'fc-9', 'fg-1', 'fi-8', 'fha-2', 'fsk-10', 'fc-7', 'fsp-1', 'fey-1'],
  },
  {
    id: 'tm-182',
    name: 'リク',
    imgUrl: '/images/tm-182.jpg',
    features: ['fc-9', 'fg-1', 'fh-2', 'fha-2', 'fsk-10', 'fc-1', 'fsk-31', 'fha-1', 'fsp-1', 'fey-1'],
  },
  {
    id: 'tm-183',
    name: 'ロマンス野獣',
    imgUrl: '/images/tm-183.jpg',
    features: ['fsk-3', 'fcat-2', 'fg-1', 'fha-2', 'fc-7', 'fch-2', 'fsp-2', 'fey-1', 'fi-2'],
  },
  {
    id: 'tm-184',
    name: 'ロマンスベル',
    imgUrl: '/images/tm-184.jpg',
    features: ['fi-2', 'fc-9', 'fha-2', 'fg-2', 'fsk-8', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3', 'fca-1'],
  },
  {
    id: 'tm-185',
    name: 'ハッピーラプンツェル',
    imgUrl: '/images/tm-185.jpg',
    features: ['fc-3', 'fc-9', 'fca-3', 'fg-2', 'fea-1', 'fey-2', 'fey-1', 'fcat-1'],
  },
  {
    id: 'tm-186',
    name: 'ヤングジャックスパロウ',
    imgUrl: '/images/tm-186.jpg',
    features: ['fc-9', 'fg-1', 'fc-5', 'fca-4', 'fi-8', 'fha-2', 'fsk-31', 'fch-2', 'fey-1', 'fha-3'],
  },
  {
    id: 'tm-187',
    name: 'サラザール',
    imgUrl: '/images/tm-187.jpg',
    features: ['fh-1', 'fsk-6', 'fsp-3', 'fg-1', 'fi-8', 'fha-2', 'fi-1', 'fea-1', 'fcat-3', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-188',
    name: '鍵犬',
    imgUrl: '/images/tm-188.jpg',
    features: ['fh-1', 'fsk-3', 'fi-3', 'fg-1', 'fty-1', 'fc-1', 'fha-2', 'fea-3', 'fn-2', 'fch-2', 'fey-1'],
  },
  {
    id: 'tm-189',
    name: 'パイレーツミッキー',
    imgUrl: '/images/tm-189.jpg',
    features: ['fh-1', 'fi-5', 'fsk-3', 'fc-6', 'fg-1', 'fca-4', 'f-1', 'fi-7', 'fn-2', 'fsp-1', 'fea-1', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-190',
    name: 'パイレーツスティッチ',
    imgUrl: '/images/tm-190.jpg',
    features: ['fc-4', 'fg-1', 'fca-4', 'fi-8', 'fsk-5', 'fi-7', 'fmo-1', 'fc-2', 'fea-2'],
  },
  {
    id: 'tm-191',
    name: 'パイレーツクラリス',
    imgUrl: '/images/tm-191.jpg',
    features: ['fsk-7', 'fn-1', 'fc-3', 'fh-3', 'fca-4', 'fsk-9', 'fca-3', 'fi-7', 'fg-2', 'fch-1', 'fey-2', 'fc-8', 'fn-3'],
  },
  {
    id: 'tm-192',
    name: 'MUマイク',
    imgUrl: '/images/tm-192.jpg',
    features: ['fi-5', 'fg-1', 'fc-5', 'fca-4', 'fsk-5', 'fey-3', 'fse-1', 'fsp-2'],
  },
  {
    id: 'tm-193',
    name: 'ジェットパックエイリアン',
    imgUrl: '/images/tm-193.jpg',
    features: ['fsp-6', 'fi-4', 'fc-5', 'fi-1', 'fey-3', 'fse-1', 'fsp-2', 'fmo-1', 'fea-2'],
  },
  {
    id: 'tm-194',
    name: 'ウォーリー',
    imgUrl: '/images/tm-194.jpg',
    features: ['fh-1', 'fc-3', 'fg-1', 'fey-3', 'fse-1'],
  },
  {
    id: 'tm-195',
    name: 'カールじいさん',
    imgUrl: '/images/tm-195.jpg',
    features: ['fc-9', 'fg-1', 'fsk-4', 'fea-1', 'fha-2', 'fc-1', 'fha-1', 'fse-1', 'fey-1', 'fca-1'],
  },
  {
    id: 'tm-196',
    name: 'ハロウィンソラ',
    imgUrl: '/images/tm-196.jpg',
    features: ['fh-1', 'fsp-1', 'fca-2', 'fsk-15', 'fg-1', 'fc-9', 'fi-8', 'fha-2', 'fsk-10', 'fsk-14', 'fc-7', 'fsk-11', 'fsp-2', 'fcat-4', 'fmo-1'],
  },
  {
    id: 'tm-197',
    name: 'まきまきドナルド',
    imgUrl: '/images/tm-197.jpg',
    features: ['fh-1', 'fi-5', 'fc-3', 'fsk-15', 'fg-1', 'fi-3', 'fsp-5', 'f-3', 'fha-2', 'fc-1', 'fsk-10', 'fsk-13', 'fcat-4', 'fmo-1'],
  },
  {
    id: 'tm-198',
    name: 'ねじねじグーフィー',
    imgUrl: '/images/tm-198.jpg',
    features: ['fi-6', 'fsk-15', 'fg-1', 'fsk-4', 'fh-2', 'fty-1', 'fha-2', 'fsk-10', 'fea-3', 'fey-3', 'fcat-4', 'fc-2'],
  },
  {
    id: 'tm-199',
    name: 'パンプキンキング',
    imgUrl: '/images/tm-199.jpg',
    features: ['fn-1', 'fsk-15', 'fg-1', 'fsk-14', 'fi-7', 'fc-7', 'fcat-4', 'fmo-1'],
  },
  {
    id: 'tm-200',
    name: 'ブギー',
    imgUrl: '/images/tm-200.jpg',
    features: ['fh-1', 'fsk-7', 'fg-1', 'fc-1', 'fsk-10', 'fcat-3', 'fcat-4', 'fmo-1', 'fi-2'],
  },
  {
    id: 'tm-201',
    name: 'ごきげんプー',
    imgUrl: '/images/tm-201.jpg',
    features: ['fn-1', 'fc-3', 'fg-1', 'fmo-1', 'fh-3', 'fsk-10', 'fi-7', 'fsp-1', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-202',
    name: 'さむがりピグレット',
    imgUrl: '/images/tm-202.jpg',
    features: ['fc-10', 'fn-1', 'fg-1', 'fi-8', 'fea-4', 'fi-7', 'fch-1', 'fey-1', 'fea-2', 'fn-3'],
  },
  {
    id: 'tm-203',
    name: 'オウル',
    imgUrl: '/images/tm-203.jpg',
    features: ['fc-3', 'fsp-5', 'fg-1', 'fmo-1', 'fc-7', 'fsk-11', 'fey-1'],
  },
  {
    id: 'tm-204',
    name: 'ランピー',
    imgUrl: '/images/tm-204.jpg',
    features: ['fc-10', 'fg-1', 'fha-2', 'fsk-9', 'fsk-13', 'fea-3', 'fey-1', 'fc-8', 'fsk-18', 'fea-4'],
  },
  {
    id: 'tm-205',
    name: 'ドロッセル',
    imgUrl: '/images/tm-205.jpg',
    features: ['fh-1', 'fsk-3', 'fi-3', 'fc-1', 'fsk-9', 'fg-2', 'fha-1', 'fha-3'],
  },
  {
    id: 'tm-206',
    name: 'ハッピー白雪姫',
    imgUrl: '/images/tm-206.jpg',
    features: ['fsk-3', 'fc-9', 'fc-2', 'fi-8', 'fsk-9', 'fg-2', 'fsp-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fca-1'],
  },
  {
    id: 'tm-207',
    name: 'ホリデーベイマックス',
    imgUrl: '/images/tm-207.jpg',
    features: ['fh-1', 'fg-1', 'fca-4', 'fc-1', 'fc-6', 'fi-2'],
  },
  {
    id: 'tm-208',
    name: 'ホリデーマリー',
    imgUrl: '/images/tm-208.jpg',
    features: ['fi-5', 'fty-2', 'fn-1', 'fn-3', 'fey-2', 'fca-4', 'fc-1', 'fha-2', 'fsk-10', 'fg-2', 'fsk-11', 'fch-2', 'fch-1', 'fea-2', 'fha-3', 'fea-4', 'fca-1'],
  },
  {
    id: 'tm-209',
    name: 'ホリデードナルド',
    imgUrl: '/images/tm-209.jpg',
    features: ['fh-1', 'fc-6', 'fsp-5', 'fg-1', 'fi-3', 'f-3', 'fca-4', 'fc-1', 'fha-2', 'fch-2', 'fch-1', 'fmo-1'],
  },
  {
    id: 'tm-210',
    name: 'ウィンターシンデレラ',
    imgUrl: '/images/tm-210.jpg',
    features: ['fc-3', 'fc-9', 'fi-8', 'fg-2', 'fsk-8', 'fsp-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3'],
  },
  {
    id: 'tm-211',
    name: 'ウィンターオーロラ姫',
    imgUrl: '/images/tm-211.jpg',
    features: ['fc-3', 'fca-2', 'fc-9', 'fi-1', 'fi-7', 'fg-2', 'fsp-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fi-2'],
  },
  {
    id: 'tm-212',
    name: 'ウィンターベル',
    imgUrl: '/images/tm-212.jpg',
    features: ['fha-3', 'fc-9', 'fca-4', 'fsk-10', 'fg-2', 'fsk-8', 'fc-6', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fi-2'],
  },
  {
    id: 'tm-213',
    name: 'アイドルチップ',
    imgUrl: '/images/tm-213.jpg',
    features: ['fca-1', 'fn-1', 'fc-4', 'fi-3', 'fg-1', 'fsk-30', 'fi-1', 'fsk-9', 'fsk-5', 'fn-2', 'fch-1', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-214',
    name: 'アイドルデール',
    imgUrl: '/images/tm-214.jpg',
    features: ['fca-1', 'fn-3', 'fi-3', 'fg-1', 'fsk-30', 'fsk-4', 'fi-1', 'fsk-9', 'fch-1', 'fc-8', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-215',
    name: 'プラクティカル',
    imgUrl: '/images/tm-215.jpg',
    features: ['fh-1', 'fc-10', 'fn-1', 'fn-3', 'fg-1', 'fca-4', 'fi-7', 'fch-1', 'fey-1', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-216',
    name: 'ビッグバッドウルフ',
    imgUrl: '/images/tm-216.jpg',
    features: ['fh-1', 'fc-3', 'fg-1', 'fca-4', 'fha-2', 'fc-7', 'fn-2', 'fsk-19', 'fch-2', 'fcat-3', 'fea-2', 'fi-2'],
  },
  {
    id: 'tm-217',
    name: 'イェンシッド',
    imgUrl: '/images/tm-217.jpg',
    features: ['fc-4', 'fc-9', 'fg-1', 'fca-4', 'fi-8', 'fea-1', 'fch-2', 'fey-1'],
  },
  {
    id: 'tm-218',
    name: 'チェルナボーグ',
    imgUrl: '/images/tm-218.jpg',
    features: ['fn-1', 'fc-4', 'fg-1', 'fmo-1', 'fsk-5', 'fcat-3', 'fsp-2', 'fey-1', 'fea-2'],
  },
  {
    id: 'tm-219',
    name: 'D23スペシャルミッキー',
    imgUrl: '/images/tm-219.jpg',
    features: ['fi-5', 'fh-1', 'fsk-7', 'fc-4', 'fi-3', 'fg-1', 'fsk-30', 'fca-4', 'f-1', 'fsk-9', 'fn-2', 'fsk-8', 'fsp-1', 'fea-1', 'fc-2', 'fca-1'],
  },
  {
    id: 'tm-220',
    name: 'ウッディ保安官',
    imgUrl: '/images/tm-220.jpg',
    features: ['fc-9', 'fg-1', 'fca-4', 'fse-1', 'fi-8', 'fsk-9', 'fsk-5', 'fi-7', 'fc-7', 'fea-1', 'fch-1', 'fey-1'],
  },
  {
    id: 'tm-221',
    name: 'スペースレンジャーバズ',
    imgUrl: '/images/tm-221.jpg',
    features: ['fh-1', 'fey-1', 'fc-9', 'fg-1', 'fi-8', 'fsk-9', 'fsk-13', 'fse-1', 'fsk-22', 'fmo-1', 'fc-8', 'fi-2'],
  },
  {
    id: 'tm-222',
    name: 'ザーグ',
    imgUrl: '/images/tm-222.jpg',
    features: ['fh-1', 'fg-1', 'fsp-2', 'fsp-1', 'fse-1', 'fcat-3', 'fmo-1', 'fc-8', 'fsk-18'],
  },
  {
    id: 'tm-223',
    name: 'ミゲル',
    imgUrl: '/images/tm-223.jpg',
    features: ['fi-5', 'fsk-3', 'fc-9', 'fg-1', 'fea-1', 'fha-2', 'fc-7', 'fse-1', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-224',
    name: 'ホリデーオラフ',
    imgUrl: '/images/tm-224.jpg',
    features: ['fey-1', 'fha-4', 'fsk-4', 'fg-1', 'fc-1', 'fha-2', 'fmo-1'],
  },
  {
    id: 'tm-225',
    name: '警察官ジュディ',
    imgUrl: '/images/tm-225.jpg',
    features: ['fh-1', 'fsk-3', 'fi-4', 'fn-3', 'fty-3', 'fmo-1', 'fh-2', 'fsk-9', 'fi-7', 'fg-2', 'fsp-1', 'fey-2', 'fey-1', 'fc-2', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-226',
    name: '警察官ニック',
    imgUrl: '/images/tm-226.jpg',
    features: ['fi-6', 'fn-1', 'fsk-3', 'fg-1', 'fmo-1', 'fsk-9', 'fi-7', 'fc-7', 'fn-2', 'fsp-1', 'fey-1', 'fea-2'],
  },
  {
    id: 'tm-227',
    name: 'クロウハウザー',
    imgUrl: '/images/tm-227.jpg',
    features: ['fty-2', 'fc-3', 'fg-1', 'fh-3', 'fsk-10', 'fsp-1', 'fey-1', 'fea-2'],
  },
  {
    id: 'tm-228',
    name: 'フラッシュ',
    imgUrl: '/images/tm-228.jpg',
    features: ['fey-3', 'fg-1', 'fey-1', 'fha-2'],
  },
  {
    id: 'tm-229',
    name: 'スプリングミスバニー',
    imgUrl: '/images/tm-229.jpg',
    features: ['fea-2', 'fi-5', 'fn-1', 'fc-3', 'fn-3', 'fca-2', 'fty-3', 'fh-3', 'fi-8', 'fsk-10', 'fca-3', 'fsk-13', 'fg-2', 'fsk-11', 'fch-1', 'fey-2', 'fi-2', 'fea-4'],
  },
  {
    id: 'tm-230',
    name: 'アイアンマン',
    imgUrl: '/images/tm-230.jpg',
    features: ['fsk-7', 'fc-3', 'fg-1', 'fca-4', 'fi-1', 'fc-6', 'fmo-1'],
  },
  {
    id: 'tm-231',
    name: 'スパイダーマン',
    imgUrl: '/images/tm-231.jpg',
    features: ['fg-1', 'fca-4', 'fi-8', 'fc-6', 'fch-1'],
  },
  {
    id: 'tm-232',
    name: 'キャプテンアメリカ',
    imgUrl: '/images/tm-232.jpg',
    features: ['fc-4', 'fg-1', 'fca-4', 'fi-1', 'fsk-23', 'fea-1'],
  },
  {
    id: 'tm-233',
    name: 'サノス',
    imgUrl: '/images/tm-233.jpg',
    features: ['fsk-3', 'fc-4', 'fc-3', 'fg-1', 'fh-3', 'fca-4', 'fi-8', 'fi-9', 'fcat-3', 'fc-8'],
  },
  {
    id: 'tm-234',
    name: 'ホセ',
    imgUrl: '/images/tm-234.jpg',
    features: ['fi-4', 'fsp-5', 'fg-1', 'fc-5', 'fca-4', 'fh-3', 'fha-2', 'fsk-9', 'fmo-1', 'fca-1'],
  },
  {
    id: 'tm-235',
    name: 'パンチート',
    imgUrl: '/images/tm-235.jpg',
    features: ['fh-1', 'fha-4', 'fsp-5', 'fg-1', 'fsk-4', 'fca-4', 'fha-2', 'fsk-9', 'fi-7', 'fc-6', 'fmo-1'],
  },
  {
    id: 'tm-236',
    name: 'ブライドアリエル',
    imgUrl: '/images/tm-236.jpg',
    features: ['fca-2', 'fc-9', 'fea-1', 'fi-1', 'fsk-10', 'fg-2', 'fsk-8', 'fc-6', 'fch-1', 'fey-2', 'fcat-1', 'fi-2'],
  },
  {
    id: 'tm-237',
    name: 'ティアナ',
    imgUrl: '/images/tm-237.jpg',
    features: ['fca-2', 'fc-9', 'fc-2', 'fha-2', 'fsk-5', 'fg-2', 'fc-7', 'fsk-8', 'fea-1', 'fi-9', 'fey-2', 'fey-1', 'fcat-1', 'fha-3'],
  },
  {
    id: 'tm-238',
    name: 'ブライドジャスミン',
    imgUrl: '/images/tm-238.jpg',
    features: ['fi-4', 'fi-2', 'fc-9', 'fc-2', 'fsk-18', 'fsk-10', 'fca-3', 'fg-2', 'fc-7', 'fsk-8', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3'],
  },
  {
    id: 'tm-239',
    name: 'メリダ',
    imgUrl: '/images/tm-239.jpg',
    features: ['fi-5', 'fc-9', 'fha-2', 'fg-2', 'fse-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1'],
  },
  {
    id: 'tm-240',
    name: 'エスメラルダ',
    imgUrl: '/images/tm-240.jpg',
    features: ['fsk-1', 'fsk-6', 'fha-2', 'fg-2', 'fc-7', 'fea-1', 'fey-2', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-241',
    name: 'トップハットジーニー',
    imgUrl: '/images/tm-241.jpg',
    features: ['fc-4', 'fg-1', 'fca-4', 'fsp-1', 'fch-2', 'fi-9', 'fey-1', 'fea-2', 'fca-1'],
  },
  {
    id: 'tm-242',
    name: '魔人ジャファー',
    imgUrl: '/images/tm-242.jpg',
    features: ['fi-5', 'fcat-3', 'fc-6', 'fi-4', 'fg-1', 'fsk-5', 'fch-2', 'fch-1', 'fea-2', 'fey-1', 'fha-3'],
  },
  {
    id: 'tm-243',
    name: 'アリ王子',
    imgUrl: '/images/tm-243.jpg',
    features: ['fcat-2', 'fg-1', 'fca-4', 'fi-1', 'fc-1', 'fi-7', 'fsk-8', 'fsk-17', 'fey-1'],
  },
  {
    id: 'tm-244',
    name: 'ソフィア',
    imgUrl: '/images/tm-244.jpg',
    features: ['fca-2', 'fc-9', 'fi-8', 'fha-2', 'fsk-10', 'fsk-9', 'fg-2', 'fc-7', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1'],
  },
  {
    id: 'tm-245',
    name: 'ユーモラスドロッセル',
    imgUrl: '/images/tm-245.jpg',
    features: ['fh-1', 'fi-3', 'fc-1', 'fsk-9', 'fsk-13', 'fg-2', 'fha-1', 'fsk-11', 'fea-1'],
  },
  {
    id: 'tm-246',
    name: '怖がらせ屋サリー',
    imgUrl: '/images/tm-246.jpg',
    features: ['fn-1', 'fc-4', 'fg-1', 'fmo-1', 'fi-8', 'fse-1', 'fsp-2', 'fey-1'],
  },
  {
    id: 'tm-247',
    name: 'ハッピーマイク',
    imgUrl: '/images/tm-247.jpg',
    features: ['fi-5', 'fsk-4', 'fg-1', 'fc-5', 'fsk-9', 'fey-3', 'fse-1', 'fsp-2', 'fmo-1'],
  },
  {
    id: 'tm-248',
    name: 'ミスターインクレディブル',
    imgUrl: '/images/tm-248.jpg',
    features: ['fi-5', 'fsk-3', 'fc-3', 'fc-9', 'fg-1', 'fea-1', 'fh-2', 'fha-2', 'fey-3', 'fi-7', 'fse-1'],
  },
  {
    id: 'tm-249',
    name: 'ミセスインクレディブル',
    imgUrl: '/images/tm-249.jpg',
    features: ['fi-5', 'fc-9', 'fea-1', 'fh-2', 'fha-2', 'fey-3', 'fg-2', 'fc-7', 'fi-7', 'fsk-16', 'fse-1'],
  },
  {
    id: 'tm-250',
    name: 'ジャックジャック',
    imgUrl: '/images/tm-250.jpg',
    features: ['fi-4', 'fc-9', 'fg-1', 'fea-1', 'fha-2', 'fey-3', 'fi-7', 'fse-1', 'fch-1'],
  },
  {
    id: 'tm-251',
    name: 'あばれんぼスティッチ',
    imgUrl: '/images/tm-251.jpg',
    features: ['fc-4', 'fg-1', 'fi-8', 'fha-2', 'fi-1', 'fsp-1', 'fsp-2', 'fmo-1', 'fea-2'],
  },
  {
    id: 'tm-252',
    name: 'ジャンバ博士',
    imgUrl: '/images/tm-252.jpg',
    features: ['fha-4', 'fi-4', 'fi-3', 'fg-1', 'fha-2', 'fey-3', 'fea-3', 'fsk-23', 'fc-8'],
  },
  {
    id: 'tm-253',
    name: 'プリークリー',
    imgUrl: '/images/tm-253.jpg',
    features: ['fg-1', 'fc-5', 'fsk-10', 'fey-3', 'fi-7', 'fsp-2', 'fmo-1'],
  },
  {
    id: 'tm-254',
    name: 'カイリ',
    imgUrl: '/images/tm-254.jpg',
    features: ['fh-3', 'fha-2', 'fsk-9', 'fg-2', 'fc-6', 'fch-1', 'fey-2', 'fey-1'],
  },
  {
    id: 'tm-255',
    name: 'アクア',
    imgUrl: '/images/tm-255.jpg',
    features: ['fc-4', 'fh-2', 'fi-1', 'fha-2', 'fg-2', 'fey-2', 'fey-1'],
  },
  {
    id: 'tm-256',
    name: 'いたずらジャック',
    imgUrl: '/images/tm-256.jpg',
    features: ['fh-1', 'fi-5', 'fsk-7', 'fi-4', 'fsk-15', 'fg-1', 'fi-8', 'fc-1', 'fn-2', 'fsp-1', 'fcat-4', 'fmo-1'],
  },
  {
    id: 'tm-257',
    name: 'ロック',
    imgUrl: '/images/tm-257.jpg',
    features: ['fh-1', 'fey-1', 'fn-1', 'fg-1', 'fea-1', 'fc-1', 'fha-2', 'fsk-9', 'fey-3', 'fc-6', 'fcat-3', 'fmo-1'],
  },
  {
    id: 'tm-258',
    name: 'ヴァンパイアテディ',
    imgUrl: '/images/tm-258.jpg',
    features: ['fh-1', 'fsk-15', 'fg-1', 'fsk-4', 'fc-1', 'fey-3', 'fn-2', 'fea-1', 'fi-9', 'fmo-1', 'fc-2'],
  },
  {
    id: 'tm-259',
    name: 'おやすみプー',
    imgUrl: '/images/tm-259.jpg',
    features: ['fi-6', 'fn-1', 'fc-3', 'fsk-3', 'fsk-32', 'fg-1', 'fmo-1', 'fca-4', 'fh-3', 'fc-1', 'fi-7', 'fsp-1', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-260',
    name: 'ゴーファー',
    imgUrl: '/images/tm-260.jpg',
    features: ['fn-1', 'fg-1', 'fmo-1', 'fha-2', 'fn-2', 'fch-2', 'fey-1', 'fc-2', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-261',
    name: 'アニバーサリーミッキー',
    imgUrl: '/images/tm-261.jpg',
    features: ['fh-1', 'fi-5', 'fg-1', 'fca-4', 'fi-1', 'f-1', 'fsk-9', 'fc-1', 'fn-2', 'fsk-8', 'fsp-1', 'fea-1', 'fc-2', 'fsk-18', 'fca-1'],
  },
  {
    id: 'tm-262',
    name: 'クラシックミッキー',
    imgUrl: '/images/tm-262.jpg',
    features: ['fi-5', 'fsk-7', 'fg-1', 'fh-2', 'fc-1', 'f-1', 'fey-3', 'fn-2', 'fea-1', 'fc-2'],
  },
  {
    id: 'tm-263',
    name: '豆の木ミッキー',
    imgUrl: '/images/tm-263.jpg',
    features: ['fh-1', 'fi-5', 'fsp-1', 'fg-1', 'fca-4', 'f-1', 'fn-2', 'fsk-11', 'fea-1', 'fmo-1', 'fc-2'],
  },
  {
    id: 'tm-264',
    name: 'フィガロ',
    imgUrl: '/images/tm-264.jpg',
    features: ['fh-1', 'fty-2', 'fn-1', 'fsk-4', 'fg-1', 'fc-1', 'fha-2', 'fn-2', 'fch-2', 'fc-2', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-265',
    name: 'クレオ',
    imgUrl: '/images/tm-265.jpg',
    features: ['fc-3', 'fsp-4', 'fg-2', 'fch-1', 'fey-2', 'fmo-1'],
  },
  {
    id: 'tm-266',
    name: 'ラルフ',
    imgUrl: '/images/tm-266.jpg',
    features: ['fc-9', 'fg-1', 'fha-2', 'fsk-5', 'fc-7', 'fey-1', 'fn-3'],
  },
  {
    id: 'tm-267',
    name: 'ヴァネロペ',
    imgUrl: '/images/tm-267.jpg',
    features: ['fn-3', 'fc-2', 'fi-8', 'fha-2', 'fg-2', 'fsk-23', 'fsp-1', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3', 'fca-1'],
  },
  {
    id: 'tm-268',
    name: '雪だるまチップ',
    imgUrl: '/images/tm-268.jpg',
    features: ['fh-1', 'fn-1', 'fg-1', 'fca-4', 'fc-1', 'fsk-9', 'fn-2', 'fea-2'],
  },
  {
    id: 'tm-269',
    name: '雪だるまデール',
    imgUrl: '/images/tm-269.jpg',
    features: ['fh-1', 'fi-3', 'fg-1', 'fca-4', 'fc-1', 'fsk-9', 'fea-2', 'fn-3'],
  },
  {
    id: 'tm-270',
    name: 'フェリックス',
    imgUrl: '/images/tm-270.jpg',
    features: ['fc-4', 'fc-9', 'fg-1', 'fca-4', 'fh-3', 'fsp-1', 'fea-1', 'fey-1', 'fn-3'],
  },
  {
    id: 'tm-271',
    name: 'プンバァ',
    imgUrl: '/images/tm-271.jpg',
    features: ['fn-1', 'fsk-3', 'fg-1', 'fh-2', 'fha-2', 'fsk-9', 'fi-7', 'fc-7', 'fea-2', 'fey-1', 'fea-4', 'fn-3'],
  },
  {
    id: 'tm-272',
    name: '雪の女王エルサ',
    imgUrl: '/images/tm-272.jpg',
    features: ['fc-9', 'fha-2', 'fey-3', 'fg-2', 'fsp-1', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3'],
  },
  {
    id: 'tm-273',
    name: '邪悪な妖精マレフィセント',
    imgUrl: '/images/tm-273.jpg',
    features: ['fh-1', 'fi-5', 'fi-4', 'fca-4', 'fc-1', 'fey-3', 'fg-2', 'fsk-19', 'fsp-1', 'fcat-3', 'fsp-2', 'fey-2', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-274',
    name: '王様',
    imgUrl: '/images/tm-274.jpg',
    features: ['fi-5', 'fg-1', 'fh-2', 'fca-4', 'f-1', 'fsk-31', 'fn-2', 'fea-1', 'fc-2'],
  },
  {
    id: 'tm-275',
    name: 'ソラKH3ver.',
    imgUrl: '/images/tm-275.jpg',
    features: ['fsk-6', 'fsk-3', 'fca-2', 'fsk-4', 'fg-1', 'fi-8', 'fha-2', 'fsk-9', 'fc-7', 'fsp-1', 'fey-1'],
  },
  {
    id: 'tm-276',
    name: 'ゼムナス',
    imgUrl: '/images/tm-276.jpg',
    features: ['fsk-3', 'fg-1', 'fh-2', 'fha-2', 'fc-7', 'fha-1', 'fea-1', 'fcat-3', 'fey-1'],
  },
  {
    id: 'tm-277',
    name: 'アンセム',
    imgUrl: '/images/tm-277.jpg',
    features: ['fh-1', 'fg-1', 'fha-2', 'fi-1', 'fsk-5', 'fc-7', 'fha-1', 'fsp-1', 'fea-1', 'fcat-3', 'fey-1'],
  },
  {
    id: 'tm-278',
    name: 'ビアンカ',
    imgUrl: '/images/tm-278.jpg',
    features: ['fh-1', 'fi-5', 'fea-2', 'fn-1', 'fca-4', 'fc-1', 'fea-4', 'fsk-10', 'fg-2', 'fsk-8', 'fsk-11', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fc-8', 'fi-2', 'fca-1'],
  },
  {
    id: 'tm-279',
    name: 'カメラダンボ',
    imgUrl: '/images/tm-279.jpg',
    features: ['fsk-3', 'fc-4', 'fi-3', 'fg-1', 'fca-4', 'fea-3', 'fch-1', 'fea-4'],
  },
  {
    id: 'tm-280',
    name: 'ドクターファシリエ',
    imgUrl: '/images/tm-280.jpg',
    features: ['fsk-28', 'fi-3', 'fg-1', 'fsk-30', 'fmo-1', 'fca-4', 'fc-7', 'fch-2', 'fcat-3', 'fey-1', 'fc-2', 'fea-2'],
  },
  {
    id: 'tm-281',
    name: 'ホーンドキング',
    imgUrl: '/images/tm-281.jpg',
    features: ['fsk-7', 'fg-1', 'fc-5', 'fca-4', 'fsp-2', 'fn-2', 'fsp-1', 'fc-6', 'fcat-3'],
  },
  {
    id: 'tm-282',
    name: 'パルパティーン皇帝',
    imgUrl: '/images/tm-282.jpg',
    features: ['fh-1', 'fi-3', 'fg-1', 'fca-4', 'fc-1', 'fi-8', 'fi-7', 'fsk-23', 'fcat-3', 'fc-2'],
  },
  {
    id: 'tm-283',
    name: 'ダースモール',
    imgUrl: '/images/tm-283.jpg',
    features: ['fi-5', 'fsk-6', 'fi-3', 'fg-1', 'fca-4', 'fh-2', 'fch-1', 'fsp-2', 'fn-2', 'fc-6', 'fcat-3', 'fc-2'],
  },
  {
    id: 'tm-284',
    name: 'ソー',
    imgUrl: '/images/tm-284.jpg',
    features: ['fc-3', 'fcat-2', 'fi-3', 'fg-1', 'fi-8', 'fca-4', 'fha-2', 'fc-1', 'fi-9', 'fey-1', 'fi-2'],
  },
  {
    id: 'tm-285',
    name: 'トニースターク',
    imgUrl: '/images/tm-285.jpg',
    features: ['fc-6', 'fg-1', 'fca-4', 'fi-8', 'fi-1', 'fsk-5', 'fch-2', 'fi-9', 'fey-1'],
  },
  {
    id: 'tm-286',
    name: 'ハルク',
    imgUrl: '/images/tm-286.jpg',
    features: ['fg-1', 'fc-5', 'fha-2', 'fsk-5', 'fea-1', 'fey-1', 'fi-2'],
  },
  {
    id: 'tm-287',
    name: '乗馬ソフィア',
    imgUrl: '/images/tm-287.jpg',
    features: ['fi-4', 'fca-2', 'fc-9', 'fi-8', 'fha-2', 'fsk-9', 'fsk-5', 'fg-2', 'fc-7', 'fsp-1', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1'],
  },
  {
    id: 'tm-288',
    name: 'エレナ',
    imgUrl: '/images/tm-288.jpg',
    features: ['fc-2', 'fha-2', 'fca-3', 'fg-2', 'fc-7', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fsk-18'],
  },
  {
    id: 'tm-289',
    name: 'レインボーティンク',
    imgUrl: '/images/tm-289.jpg',
    features: ['fey-1', 'fsk-3', 'fc-3', 'fch-1', 'fg-2', 'fi-9', 'fha-3', 'fea-2'],
  },
  {
    id: 'tm-290',
    name: 'ペリウィンクル',
    imgUrl: '/images/tm-290.jpg',
    features: ['fha-2', 'fc-1', 'fi-7', 'fg-2', 'fha-1', 'fsk-11', 'fch-1', 'fey-2', 'fey-1', 'fea-2'],
  },
  {
    id: 'tm-291',
    name: 'シルバーミスト',
    imgUrl: '/images/tm-291.jpg',
    features: ['fsk-3', 'fc-4', 'fi-8', 'fha-2', 'fg-2', 'fch-1', 'fey-2', 'fey-1', 'fea-2'],
  },
  {
    id: 'tm-292',
    name: 'ロゼッタ',
    imgUrl: '/images/tm-292.jpg',
    features: ['fca-3', 'fsk-5', 'fg-2', 'fc-7', 'fch-1', 'fey-2', 'fey-1', 'fea-2'],
  },
  {
    id: 'tm-293',
    name: 'ロマンスジャスミン',
    imgUrl: '/images/tm-293.jpg',
    features: ['fi-4', 'fca-2', 'fc-2', 'fg-2', 'fc-7', 'fsk-8', 'fea-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3'],
  },
  {
    id: 'tm-294',
    name: 'ボーピープ',
    imgUrl: '/images/tm-294.jpg',
    features: ['fc-3', 'fi-2', 'fea-1', 'fi-7', 'fg-2', 'fey-3', 'fse-1', 'fch-1', 'fey-1', 'fha-3', 'fca-1'],
  },
  {
    id: 'tm-295',
    name: 'フォーキー',
    imgUrl: '/images/tm-295.jpg',
    features: ['fg-1', 'fmo-1', 'fc-1', 'fey-3', 'fse-1', 'fch-1', 'fey-1'],
  },
  {
    id: 'tm-296',
    name: 'バニー',
    imgUrl: '/images/tm-296.jpg',
    features: ['fch-2', 'fc-4', 'fi-2', 'fty-3', 'fg-1', 'fsk-18', 'fsk-9', 'fey-3', 'fse-1', 'fmo-1', 'fea-2'],
  },
  {
    id: 'tm-297',
    name: 'パステルアリエル',
    imgUrl: '/images/tm-297.jpg',
    features: ['fsp-3', 'fsk-22', 'fi-1', 'fha-2', 'fsk-9', 'fca-3', 'fi-7', 'fg-2', 'fsp-4', 'fea-1', 'fch-1', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-298',
    name: 'パステルフランダー',
    imgUrl: '/images/tm-298.jpg',
    features: ['fey-1', 'fsk-3', 'fc-3', 'fsp-3', 'fg-1', 'fsp-4', 'fi-7', 'fch-1', 'fmo-1'],
  },
  {
    id: 'tm-299',
    name: 'フレディマーキュリー',
    imgUrl: '/images/tm-299.jpg',
    features: ['fi-5', 'fg-1', 'fea-1', 'fey-3', 'fch-2', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-300',
    name: 'ブライアンメイ',
    imgUrl: '/images/tm-300.jpg',
    features: ['fi-5', 'fsk-6', 'fg-1', 'fey-3', 'fc-7', 'fey-1', 'fi-2'],
  },
  {
    id: 'tm-301',
    name: 'ロジャーテイラー',
    imgUrl: '/images/tm-301.jpg',
    features: ['fc-3', 'fg-1', 'fha-2', 'fsk-9', 'fey-3', 'fsk-11', 'fi-9', 'fey-1'],
  },
  {
    id: 'tm-302',
    name: 'ハクナマタタシンバ',
    imgUrl: '/images/tm-302.jpg',
    features: ['fty-2', 'fn-1', 'fch-2', 'fcat-2', 'fsk-4', 'fg-1', 'fi-8', 'fh-3', 'fha-2', 'fsk-9', 'fc-7', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-303',
    name: 'ヴェントゥス',
    imgUrl: '/images/tm-303.jpg',
    features: ['fsk-1', 'fc-3', 'fsk-4', 'fg-1', 'fha-2', 'fsp-1', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-304',
    name: 'テラ',
    imgUrl: '/images/tm-304.jpg',
    features: ['fg-1', 'fh-2', 'fha-2', 'fc-7', 'fi-9', 'fey-1'],
  },
  {
    id: 'tm-305',
    name: 'チリシィ',
    imgUrl: '/images/tm-305.jpg',
    features: ['fh-1', 'fn-1', 'fh-2', 'fea-3', 'fsp-1', 'fc-2', 'fsk-18', 'fn-3'],
  },
  {
    id: 'tm-306',
    name: 'ハニーレモン',
    imgUrl: '/images/tm-306.jpg',
    features: ['fey-2', 'fg-2', 'fey-1', 'fca-4'],
  },
  {
    id: 'tm-307',
    name: 'フレッド',
    imgUrl: '/images/tm-307.jpg',
    features: ['fey-1', 'fc-4', 'fg-1', 'fca-4', 'fey-3', 'fsp-2', 'fmo-1'],
  },
  {
    id: 'tm-308',
    name: '勇者ミッキー',
    imgUrl: '/images/tm-308.jpg',
    features: ['fi-5', 'fh-1', 'fsk-3', 'fg-1', 'fha-2', 'f-1', 'fsk-5', 'fsk-11', 'fn-2', 'fsp-1', 'fea-1', 'fey-1', 'fc-2', 'fi-2'],
  },
  {
    id: 'tm-309',
    name: '勇者ドナルド',
    imgUrl: '/images/tm-309.jpg',
    features: ['fh-1', 'fey-1', 'fc-4', 'fsp-5', 'fg-1', 'fi-3', 'f-3', 'fca-4', 'fc-1', 'fha-2', 'fsp-1', 'fch-1', 'fmo-1', 'fi-2'],
  },
  {
    id: 'tm-310',
    name: '勇者グーフィー',
    imgUrl: '/images/tm-310.jpg',
    features: ['fh-1', 'fi-2', 'fg-1', 'fc-5', 'fca-4', 'fty-1', 'fsk-9', 'fey-3', 'fea-3', 'fn-2', 'fsp-1', 'fsk-18'],
  },
  {
    id: 'tm-311',
    name: 'パックマン',
    imgUrl: '/images/tm-311.jpg',
    features: ['fc-3', 'fg-1', 'fh-3', 'fi-7', 'fmo-1'],
  },
  {
    id: 'tm-312',
    name: 'ブリンキー',
    imgUrl: '/images/tm-312.jpg',
    features: ['fg-1', 'fey-3', 'fc-6', 'fch-1', 'fi-2'],
  },
  {
    id: 'tm-313',
    name: 'エンチャンテッドオーロラ',
    imgUrl: '/images/tm-313.jpg',
    features: ['fc-3', 'fca-2', 'fi-1', 'fey-3', 'fg-2', 'fsp-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1'],
  },
  {
    id: 'tm-314',
    name: 'エンチャンテッドシンデレラ',
    imgUrl: '/images/tm-314.jpg',
    features: ['fsk-3', 'fc-3', 'fi-8', 'fey-3', 'fg-2', 'fsp-1', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3'],
  },
  {
    id: 'tm-315',
    name: 'ダンシングジーニー',
    imgUrl: '/images/tm-315.jpg',
    features: ['fc-4', 'fha-3', 'fi-3', 'fg-1', 'fsk-9', 'fsk-13', 'fey-3', 'fch-2', 'fey-1', 'fea-2'],
  },
  {
    id: 'tm-316',
    name: 'ほっこりミッキー',
    imgUrl: '/images/tm-316.jpg',
    features: ['fi-5', 'fh-1', 'fg-1', 'fmo-1', 'fc-1', 'f-1', 'fsk-10', 'fn-2', 'fsk-8', 'fea-1', 'fch-1', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-317',
    name: 'ゆるっとドナルド',
    imgUrl: '/images/tm-317.jpg',
    features: ['fh-1', 'fsp-5', 'fg-1', 'fi-3', 'f-3', 'fca-4', 'fc-1', 'fch-1', 'fmo-1', 'fca-1'],
  },
  {
    id: 'tm-318',
    name: 'アドベンチャーエルサ',
    imgUrl: '/images/tm-318.jpg',
    features: ['fha-2', 'fi-1', 'fey-3', 'fg-2', 'fsp-1', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3'],
  },
  {
    id: 'tm-319',
    name: 'アドベンチャーアナ',
    imgUrl: '/images/tm-319.jpg',
    features: ['fi-1', 'fha-2', 'fey-3', 'fg-2', 'fc-7', 'fsk-8', 'fea-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3'],
  },
  {
    id: 'tm-320',
    name: 'ジェダイトレーニングレイ',
    imgUrl: '/images/tm-320.jpg',
    features: ['fi-4', 'fha-2', 'fsk-5', 'fg-2', 'fc-7', 'fsp-1', 'fea-1', 'fey-2', 'fey-1', 'fha-3'],
  },
  {
    id: 'tm-321',
    name: '最高指導者カイロレン',
    imgUrl: '/images/tm-321.jpg',
    features: ['fg-1', 'fca-4', 'fh-2', 'fi-8', 'fn-2', 'fcat-3', 'fc-2', 'fsk-18'],
  },
  {
    id: 'tm-322',
    name: 'だるまミッキー',
    imgUrl: '/images/tm-322.jpg',
    features: ['fi-5', 'fc-6', 'fi-3', 'fg-1', 'f-1', 'fsk-13', 'fn-2', 'fea-1', 'fch-1', 'fc-2'],
  },
  {
    id: 'tm-323',
    name: 'フレディ75',
    imgUrl: '/images/tm-323.jpg',
    features: ['fi-5', 'fg-1', 'fha-2', 'fsk-9', 'fey-3', 'fey-1'],
  },
  {
    id: 'tm-324',
    name: 'ジョンディーコン',
    imgUrl: '/images/tm-324.jpg',
    features: ['fsk-7', 'fi-4', 'fi-3', 'fg-1', 'fha-2', 'fsk-9', 'fey-3', 'fc-7', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-325',
    name: 'アリエル(チャーム)',
    imgUrl: '/images/tm-325.jpg',
    features: ['fc-6', 'fsk-21', 'fsp-3', 'fha-2', 'fi-1', 'fsp-4', 'fg-2', 'fsk-11', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1'],
  },
  {
    id: 'tm-326',
    name: 'ベル(チャーム)',
    imgUrl: '/images/tm-326.jpg',
    features: ['fsk-1', 'fi-2', 'fsk-4', 'fha-2', 'fg-2', 'fc-7', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3', 'fca-1'],
  },
  {
    id: 'tm-327',
    name: 'ラプンツェル(チャーム)',
    imgUrl: '/images/tm-327.jpg',
    features: ['fsk-1', 'fsk-3', 'fc-3', 'fca-3', 'fg-2', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3'],
  },
  {
    id: 'tm-328',
    name: 'ジャスミン(チャーム)',
    imgUrl: '/images/tm-328.jpg',
    features: ['fsk-1', 'fsk-7', 'fey-1', 'fc-4', 'fi-4', 'fca-2', 'fha-2', 'fg-2', 'fsp-1', 'fch-1', 'fey-2', 'fha-3', 'fcat-1'],
  },
  {
    id: 'tm-329',
    name: 'MUランドール',
    imgUrl: '/images/tm-329.jpg',
    features: ['fha-4', 'fg-1', 'fha-2', 'fsk-10', 'fey-3', 'fse-1', 'fmo-1', 'fc-8'],
  },
  {
    id: 'tm-330',
    name: 'イヴ',
    imgUrl: '/images/tm-330.jpg',
    features: ['fh-1', 'fsk-1', 'fsk-4', 'fc-1', 'fg-2', 'fse-1', 'fc-2'],
  },
  {
    id: 'tm-331',
    name: 'バーリー',
    imgUrl: '/images/tm-331.jpg',
    features: ['fsk-1', 'fn-1', 'fc-4', 'fsk-4', 'fg-1', 'fca-4', 'fse-1', 'fha-2', 'fch-2', 'fch-1', 'fey-1', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-332',
    name: 'イアン',
    imgUrl: '/images/tm-332.jpg',
    features: ['fn-1', 'fc-4', 'fg-1', 'fha-2', 'fse-1', 'fch-1', 'fey-1', 'fea-2', 'fea-4'],
  },
  {
    id: 'tm-333',
    name: 'メリーポピンズ',
    imgUrl: '/images/tm-333.jpg',
    features: ['fi-5', 'fsk-1', 'fsk-4', 'fca-4', 'fc-1', 'fsk-9', 'fca-3', 'fi-7', 'fg-2', 'fch-1', 'fey-2', 'fey-1', 'fca-1'],
  },
  {
    id: 'tm-334',
    name: '兵士ムーラン',
    imgUrl: '/images/tm-334.jpg',
    features: ['fi-5', 'fsk-1', 'fsk-4', 'fc-2', 'fha-2', 'fey-3', 'fg-2', 'fch-1', 'fey-2', 'fey-1', 'fcat-1'],
  },
  {
    id: 'tm-335',
    name: 'ジゼル',
    imgUrl: '/images/tm-335.jpg',
    features: ['fca-2', 'fha-2', 'fg-2', 'fc-7', 'fsp-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3'],
  },
  {
    id: 'tm-336',
    name: '白の女王',
    imgUrl: '/images/tm-336.jpg',
    features: ['fi-5', 'fsk-1', 'fsk-3', 'fi-8', 'fc-1', 'fsk-9', 'fey-3', 'fg-2', 'fha-1', 'fey-2', 'fey-1'],
  },
  {
    id: 'tm-337',
    name: 'ワンダーチェシャ猫',
    imgUrl: '/images/tm-337.jpg',
    features: ['fty-2', 'fn-1', 'fg-1', 'fha-2', 'fea-4', 'fmo-1', 'fea-2', 'fn-3'],
  },
  {
    id: 'tm-338',
    name: 'ベンケノービ',
    imgUrl: '/images/tm-338.jpg',
    features: ['fsk-1', 'fsk-7', 'fg-1', 'fca-4', 'fc-7', 'fha-1', 'fch-2', 'fey-1', 'fi-2'],
  },
  {
    id: 'tm-339',
    name: 'マスタールーク',
    imgUrl: '/images/tm-339.jpg',
    features: ['fi-5', 'fsk-1', 'fsk-7', 'fg-1', 'fea-1', 'fha-2', 'fi-8', 'fha-1', 'fsp-1', 'fch-2', 'fey-1'],
  },
  {
    id: 'tm-340',
    name: 'メイスウィンドゥ',
    imgUrl: '/images/tm-340.jpg',
    features: ['fi-5', 'fsk-1', 'fsk-4', 'fg-1', 'fsk-5', 'fc-7', 'fsp-1', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-341',
    name: 'アナキンスカイウォーカー',
    imgUrl: '/images/tm-341.jpg',
    features: ['fsk-1', 'fg-1', 'fi-8', 'fha-2', 'fi-1', 'fh-2', 'fc-7', 'fsp-1', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-342',
    name: 'パドメアミダラ',
    imgUrl: '/images/tm-342.jpg',
    features: ['fsk-1', 'fsk-4', 'fi-1', 'fsk-9', 'fi-7', 'fg-2', 'fc-7', 'fsk-8', 'fsp-1', 'fea-1', 'fey-2', 'fey-1'],
  },
  {
    id: 'tm-343',
    name: 'リロイ',
    imgUrl: '/images/tm-343.jpg',
    features: ['fcat-3', 'fsk-1', 'fg-1', 'fha-2', 'fch-1', 'fc-6', 'fsp-2', 'fmo-1', 'fea-2'],
  },
  {
    id: 'tm-344',
    name: 'ハムスターヴィール博士',
    imgUrl: '/images/tm-344.jpg',
    features: ['fh-1', 'fey-1', 'fn-1', 'fn-3', 'fg-1', 'fc-1', 'fha-2', 'fsp-1', 'fcat-3', 'fmo-1', 'fea-4'],
  },
  {
    id: 'tm-345',
    name: '忍者ミッキー',
    imgUrl: '/images/tm-345.jpg',
    features: ['fi-5', 'fsk-1', 'fg-1', 'fh-2', 'f-1', 'fsk-5', 'fn-2', 'fea-1', 'fc-2'],
  },
  {
    id: 'tm-346',
    name: '着物ミニー',
    imgUrl: '/images/tm-346.jpg',
    features: ['fh-1', 'fi-5', 'fsk-11', 'fg-2', 'fn-2', 'fsp-1', 'fea-1', 'fch-1', 'fey-2', 'fc-2', 'fca-1'],
  },
  {
    id: 'tm-347',
    name: 'エルササラマンダー',
    imgUrl: '/images/tm-347.jpg',
    features: ['fc-4', 'fmo-1', 'fi-8', 'fha-2', 'fsk-10', 'fey-3', 'fg-2', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1'],
  },
  {
    id: 'tm-348',
    name: 'お祭りドナルド',
    imgUrl: '/images/tm-348.jpg',
    features: ['fh-1', 'fsp-5', 'fg-1', 'fi-3', 'f-3', 'fc-1', 'fsp-1', 'fch-1', 'fmo-1'],
  },
  {
    id: 'tm-349',
    name: 'ガイコツミゲル',
    imgUrl: '/images/tm-349.jpg',
    features: ['fh-1', 'fi-5', 'fg-1', 'fca-4', 'fc-1', 'fn-2', 'fsk-11', 'fse-1', 'fch-1', 'fc-2'],
  },
  {
    id: 'tm-350',
    name: 'ラグビーミッキー',
    imgUrl: '/images/tm-350.jpg',
    features: ['fh-1', 'fi-5', 'fsk-1', 'fsk-3', 'fc-6', 'fg-1', 'fca-4', 'f-1', 'fsk-11', 'fn-2', 'fsp-1', 'fea-1', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-351',
    name: '波乗りスティッチ',
    imgUrl: '/images/tm-351.jpg',
    features: ['fsk-1', 'fi-6', 'fc-4', 'fsk-4', 'fg-1', 'fi-8', 'fha-2', 'fmo-1', 'fea-2'],
  },
  {
    id: 'tm-352',
    name: 'ホームランプー',
    imgUrl: '/images/tm-352.jpg',
    features: ['fsk-1', 'fn-1', 'fc-3', 'fg-1', 'fca-4', 'fh-3', 'fsk-5', 'fi-7', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-353',
    name: '魔女マレフィセント',
    imgUrl: '/images/tm-353.jpg',
    features: ['fi-5', 'fc-4', 'fca-4', 'fg-2', 'fsp-1', 'fcat-3', 'fsp-2', 'fey-2', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-354',
    name: '死者の国の神ハデス',
    imgUrl: '/images/tm-354.jpg',
    features: ['fsk-1', 'fc-4', 'fg-1', 'fmo-1', 'fi-8', 'fha-2', 'fey-3', 'fcat-3', 'fey-1', 'fea-2'],
  },
  {
    id: 'tm-355',
    name: 'マイクサリー',
    imgUrl: '/images/tm-355.jpg',
    features: ['fi-5', 'fsk-1', 'fey-1', 'fn-1', 'fc-4', 'fg-1', 'fc-5', 'fi-8', 'fsk-9', 'fsk-13', 'fey-3', 'fsk-5', 'fse-1', 'fsp-2', 'fmo-1'],
  },
  {
    id: 'tm-356',
    name: 'パイレーツソラ',
    imgUrl: '/images/tm-356.jpg',
    features: ['fsk-1', 'fsk-3', 'fca-2', 'fsk-4', 'fg-1', 'fi-8', 'fha-2', 'fca-4', 'fsk-5', 'fi-7', 'fc-7', 'fsp-1', 'fey-1'],
  },
  {
    id: 'tm-357',
    name: '少年ゼアノート',
    imgUrl: '/images/tm-357.jpg',
    features: ['fsk-1', 'fg-1', 'fi-8', 'fha-2', 'fc-1', 'fc-7', 'fha-1', 'fsp-1', 'fea-1', 'fcat-3', 'fey-1'],
  },
  {
    id: 'tm-358',
    name: 'マスカレードラプンツェル',
    imgUrl: '/images/tm-358.jpg',
    features: ['fi-5', 'fsk-1', 'fsk-3', 'fc-3', 'fsk-30', 'fca-3', 'fg-2', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1'],
  },
  {
    id: 'tm-359',
    name: 'マスカレードシンデレラ',
    imgUrl: '/images/tm-359.jpg',
    features: ['fi-5', 'fc-3', 'fsk-30', 'fi-8', 'fsk-10', 'fg-2', 'fsk-8', 'fsp-1', 'fea-1', 'fch-1', 'fey-2', 'fey-1', 'fcat-1'],
  },
  {
    id: 'tm-360',
    name: 'マスカレードエスメラルダ',
    imgUrl: '/images/tm-360.jpg',
    features: ['fi-5', 'fc-3', 'fsk-30', 'fha-2', 'fg-2', 'fc-7', 'fea-1', 'fey-2', 'fey-1', 'fc-2', 'fca-1'],
  },
  {
    id: 'tm-361',
    name: 'ジミニー',
    imgUrl: '/images/tm-361.jpg',
    features: ['fh-1', 'fi-4', 'fg-1', 'fc-5', 'fca-4', 'fsk-5', 'fey-1'],
  },
  {
    id: 'tm-362',
    name: 'マックス',
    imgUrl: '/images/tm-362.jpg',
    features: ['fh-1', 'fi-5', 'fsk-4', 'fg-1', 'fha-2', 'fty-1', 'fea-3', 'fey-3', 'fn-2', 'fc-2'],
  },
  {
    id: 'tm-363',
    name: 'アーロ',
    imgUrl: '/images/tm-363.jpg',
    features: ['fg-1', 'fc-5', 'fi-1', 'fsk-9', 'fey-3', 'fsk-19', 'fse-1'],
  },
  {
    id: 'tm-364',
    name: 'スフレ',
    imgUrl: '/images/tm-364.jpg',
    features: ['fc-10', 'fn-3', 'fg-1', 'fi-8', 'fha-2', 'fsk-13', 'fea-1', 'fch-1', 'fmo-1', 'fea-4'],
  },
  {
    id: 'tm-365',
    name: 'うさぎどん',
    imgUrl: '/images/tm-365.jpg',
    features: ['fey-1', 'fi-2', 'fty-3', 'fg-1', 'fha-2', 'fsk-5', 'fc-7', 'fmo-1', 'fea-2', 'fn-3'],
  },
  {
    id: 'tm-366',
    name: 'スクルージ',
    imgUrl: '/images/tm-366.jpg',
    features: ['fh-1', 'fi-5', 'fsp-5', 'fg-1', 'fca-4', 'fha-2', 'fc-1', 'fi-8', 'fsk-5', 'fsp-1', 'fmo-1'],
  },
  {
    id: 'tm-367',
    name: 'ストームトルーパー',
    imgUrl: '/images/tm-367.jpg',
    features: ['fg-1', 'fi-8', 'fca-4', 'fc-1', 'fsk-9', 'fh-2', 'fcat-3', 'fi-9', 'fmo-1'],
  },
  {
    id: 'tm-368',
    name: 'ピート',
    imgUrl: '/images/tm-368.jpg',
    features: ['fh-1', 'fty-2', 'fsk-3', 'fg-1', 'fha-2', 'fi-7', 'fey-3', 'fn-2', 'fcat-3', 'fc-2', 'fea-2'],
  },
  {
    id: 'tm-369',
    name: 'ほねほねプルート',
    imgUrl: '/images/tm-369.jpg',
    features: ['fc-3', 'fsk-15', 'fg-1', 'fsk-4', 'fca-4', 'fty-1', 'fc-1', 'fh-3', 'fea-3', 'fi-7', 'fey-3', 'fn-2', 'fch-1', 'fcat-4', 'fi-2', 'fca-1'],
  },
  {
    id: 'tm-370',
    name: 'ラビット',
    imgUrl: '/images/tm-370.jpg',
    features: ['fn-1', 'fc-3', 'fg-1', 'fty-3', 'fh-3', 'fha-2', 'fch-2', 'fey-1', 'fea-4', 'fn-3'],
  },
  {
    id: 'tm-371',
    name: 'リロ',
    imgUrl: '/images/tm-371.jpg',
    features: ['fc-9', 'fca-3', 'fg-2', 'fc-7', 'fea-1', 'fch-1', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-372',
    name: 'サンタジャック',
    imgUrl: '/images/tm-372.jpg',
    features: ['fh-1', 'fi-4', 'fg-1', 'fsk-20', 'fca-4', 'fc-1', 'fi-8', 'fn-2', 'fch-2', 'fcat-4', 'fmo-1'],
  },
  {
    id: 'tm-373',
    name: 'スカットル',
    imgUrl: '/images/tm-373.jpg',
    features: ['fh-1', 'fsp-3', 'fsp-5', 'fg-1', 'fsk-4', 'fmo-1', 'fi-8', 'fc-1', 'fha-2', 'fsk-9', 'fch-1', 'fey-1'],
  },
  {
    id: 'tm-374',
    name: 'アブー',
    imgUrl: '/images/tm-374.jpg',
    features: ['fn-1', 'fc-3', 'fg-1', 'fca-4', 'fi-1', 'fha-2', 'fc-7', 'fea-1', 'fey-1'],
  },
  {
    id: 'tm-375',
    name: 'C-3PO',
    imgUrl: '/images/tm-375.jpg',
    features: ['fc-3', 'fsk-4', 'fg-1', 'fh-3', 'fsk-9', 'fmo-1'],
  },
  {
    id: 'tm-376',
    name: 'レイア姫',
    imgUrl: '/images/tm-376.jpg',
    features: ['fc-9', 'fc-2', 'fsk-18', 'fi-7', 'fg-2', 'fc-7', 'fch-1', 'fey-2', 'fey-1', 'fcat-1', 'fha-3'],
  },
  {
    id: 'tm-377',
    name: 'ザズー',
    imgUrl: '/images/tm-377.jpg',
    features: ['fha-4', 'fc-4', 'fsp-5', 'fg-1', 'fsk-4', 'fmo-1', 'fha-2', 'fey-1'],
  },
  {
    id: 'tm-378',
    name: 'プリンスチャーミング',
    imgUrl: '/images/tm-378.jpg',
    features: ['fh-1', 'fcat-2', 'fc-9', 'fg-1', 'fsk-4', 'fi-7', 'fsk-8', 'fsp-1', 'fea-1', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-379',
    name: '3月うさぎ',
    imgUrl: '/images/tm-379.jpg',
    features: ['fi-5', 'fn-1', 'fc-3', 'fg-1', 'fty-3', 'fmo-1', 'fi-8', 'fha-2', 'fh-3', 'fea-4', 'fsk-5', 'fc-7', 'fch-2', 'fey-1', 'fea-2', 'fn-3'],
  },
  {
    id: 'tm-380',
    name: 'ジョーカーグーフィー',
    imgUrl: '/images/tm-380.jpg',
    features: ['fsk-7', 'fi-4', 'fg-1', 'fca-4', 'fty-1', 'fh-2', 'fsk-14', 'fea-3', 'fey-3', 'fn-2', 'fcat-4', 'fc-2'],
  },
  {
    id: 'tm-381',
    name: 'デストルーパー',
    imgUrl: '/images/tm-381.jpg',
    features: ['fi-3', 'fg-1', 'fca-4', 'fh-2', 'fi-9', 'fn-2', 'fcat-3', 'fc-2'],
  },
  {
    id: 'tm-382',
    name: 'ミニー姫',
    imgUrl: '/images/tm-382.jpg',
    features: ['fi-5', 'fh-1', 'f-2', 'fca-2', 'fc-2', 'fsk-10', 'fi-7', 'fg-2', 'fn-2', 'fsk-8', 'fsp-1', 'fea-1', 'fch-1', 'fey-2', 'fcat-1'],
  },
  {
    id: 'tm-383',
    name: 'メグ',
    imgUrl: '/images/tm-383.jpg',
    features: ['fi-5', 'fc-9', 'fea-1', 'fha-2', 'fsk-10', 'fg-2', 'fsk-8', 'fsk-17', 'fc-6', 'fey-2', 'fey-1', 'fha-3'],
  },
  {
    id: 'tm-384',
    name: 'ポット夫人',
    imgUrl: '/images/tm-384.jpg',
    features: ['fi-5', 'fc-1', 'fsk-10', 'fi-7', 'fg-2', 'fch-1', 'fey-2', 'fey-1'],
  },
  {
    id: 'tm-385',
    name: 'バットハットミニー',
    imgUrl: '/images/tm-385.jpg',
    features: ['fi-5', 'fh-1', 'f-2', 'fey-2', 'fca-4', 'fsk-14', 'fg-2', 'fn-2', 'fsp-1', 'fea-1', 'fch-1', 'fcat-4', 'fc-2', 'fi-2', 'fca-1'],
  },
  {
    id: 'tm-386',
    name: 'カバレロドナルド',
    imgUrl: '/images/tm-386.jpg',
    features: ['fh-1', 'fsp-5', 'fg-1', 'fi-3', 'f-3', 'fca-4', 'fc-1', 'fha-2', 'fsk-9', 'fch-1', 'fmo-1', 'fsk-18', 'fca-1'],
  },
  {
    id: 'tm-387',
    name: 'アニバーサリーミニー',
    imgUrl: '/images/tm-387.jpg',
    features: ['fh-1', 'fi-5', 'f-2', 'fc-1', 'fi-1', 'fsk-9', 'fca-3', 'fsk-10', 'fg-2', 'fsk-16', 'fn-2', 'fsk-8', 'fsp-1', 'fea-1', 'fey-2', 'fc-2'],
  },
  {
    id: 'tm-388',
    name: 'シャドウ',
    imgUrl: '/images/tm-388.jpg',
    features: ['fi-8', 'fh-2', 'fsp-2', 'fn-2', 'fcat-3', 'fc-2'],
  },
  {
    id: 'tm-389',
    name: 'だるまミニー',
    imgUrl: '/images/tm-389.jpg',
    features: ['fi-5', 'f-2', 'fi-3', 'fc-1', 'fsk-13', 'fg-2', 'fn-2', 'fea-1', 'fch-1', 'fey-2', 'fc-2', 'fca-1'],
  },
  {
    id: 'tm-390',
    name: 'フィン',
    imgUrl: '/images/tm-390.jpg',
    features: ['fsk-1', 'fg-1', 'fc-7', 'fsp-1', 'fea-1', 'fey-1', 'fc-2'],
  },
  {
    id: 'tm-391',
    name: 'リトルグリーンメン',
    imgUrl: '/images/tm-391.jpg',
    features: ['fsp-6', 'fc-5', 'fi-1', 'fey-3', 'fse-1', 'fsp-2', 'fmo-1', 'fea-2'],
  },
  {
    id: 'tm-392',
    name: 'オズワルド',
    imgUrl: '/images/tm-392.jpg',
    features: ['fg-1', 'fty-3', 'fh-2', 'fc-1', 'fea-3', 'fn-2', 'fc-2'],
  },
  {
    id: 'tm-393',
    name: 'コグスワース',
    imgUrl: '/images/tm-393.jpg',
    features: ['fg-1', 'fh-3', 'fsk-9', 'fc-7', 'fch-2', 'fey-1'],
  },
  {
    id: 'tm-394',
    name: 'ガジェット',
    imgUrl: '/images/tm-394.jpg',
    features: ['fea-2', 'fn-1', 'fsk-4', 'fmo-1', 'fg-2', 'fc-7', 'fch-1', 'fey-2', 'fey-1', 'fea-4', 'fn-3'],
  },
];

const initialData = {
  data: tsumuData,
  features,
};

export default initialData;
